Adc12_b_api
Adc12_b_api
Functions
bool ADC12_B_init (uint16_t baseAddress, uint16_t sampleHoldSignalSourceSelect, uint8_t clockSourceSelect, uint16_t clockSourceDivider, uint16_t clockSourcePredivider, uint16_t internalChannelMap)
DEPRECATED - Initializes the ADC12B Module.
bool ADC12_B_initialize (uint16_t baseAddress, ADC12_B_initializeParam *param)
Initializes the ADC12B Module.
void ADC12_B_enable (uint16_t baseAddress)
Enables the ADC12B block.
void ADC12_B_disable (uint16_t baseAddress)
Disables the ADC12B block.
void ADC12_B_setupSamplingTimer (uint16_t baseAddress, uint16_t clockCycleHoldCountLowMem, uint16_t clockCycleHoldCountHighMem, uint16_t multipleSamplesEnabled)
Sets up and enables the Sampling Timer Pulse Mode.
void ADC12_B_disableSamplingTimer (uint16_t baseAddress)
Disables Sampling Timer Pulse Mode.
void ADC12_B_memoryConfigure (uint16_t baseAddress, uint8_t memoryBufferControlIndex, uint8_t inputSourceSelect, uint16_t refVoltageSourceSelect, uint16_t endOfSequence, uint16_t windowComparatorSelect, uint16_t differentialModeSelect)
DEPRECATED - Configures the controls of the selected memory buffer.
void ADC12_B_configureMemory (uint16_t baseAddress, ADC12_B_configureMemoryParam *param)
Configures the controls of the selected memory buffer.
void ADC12_B_setWindowCompAdvanced (uint16_t baseAddress, uint16_t highThreshold, uint16_t lowThreshold)
Sets the high and low threshold for the window comparator feature.
void ADC12_B_enableInterrupt (uint16_t baseAddress, uint16_t interruptMask0, uint16_t interruptMask1, uint16_t interruptMask2)
Enables selected ADC12B interrupt sources.
void ADC12_B_disableInterrupt (uint16_t baseAddress, uint16_t interruptMask0, uint16_t interruptMask1, uint16_t interruptMask2)
Disables selected ADC12B interrupt sources.
void ADC12_B_clearInterrupt (uint16_t baseAddress, uint8_t interruptRegisterChoice, uint16_t memoryInterruptFlagMask)
Clears ADC12B selected interrupt flags.
uint16_t ADC12_B_getInterruptStatus (uint16_t baseAddress, uint8_t interruptRegisterChoice, uint16_t memoryInterruptFlagMask)
Returns the status of the selected memory interrupt flags.
void ADC12_B_startConversion (uint16_t baseAddress, uint16_t startingMemoryBufferIndex, uint8_t conversionSequenceModeSelect)
Enables/Starts an Analog-to-Digital Conversion.
void ADC12_B_disableConversions (uint16_t baseAddress, bool preempt)
Disables the ADC from converting any more signals.
uint16_t ADC12_B_getResults (uint16_t baseAddress, uint8_t memoryBufferIndex)
Returns the raw contents of the specified memory buffer.
void ADC12_B_setResolution (uint16_t baseAddress, uint8_t resolutionSelect)
Use to change the resolution of the converted data.
void ADC12_B_setSampleHoldSignalInversion (uint16_t baseAddress, uint16_t invertedSignal)
Use to invert or un-invert the sample/hold signal.
void ADC12_B_setDataReadBackFormat (uint16_t baseAddress, uint8_t readBackFormat)
Use to set the read-back format of the converted data.
void ADC12_B_setAdcPowerMode (uint16_t baseAddress, uint8_t powerMode)
Use to set the ADC's power conservation mode if the sampling rate is at 50-ksps or less.
uint32_t ADC12_B_getMemoryAddressForDMA (uint16_t baseAddress, uint8_t memoryIndex)
Returns the address of the specified memory buffer for the DMA module.
uint8_t ADC12_B_isBusy (uint16_t baseAddress)
Returns the busy status of the ADC12B core.
Detailed Description
Function Documentation
bool ADC12_B_init (uint16_t baseAddress, uint16_t sampleHoldSignalSourceSelect, uint8_t clockSourceSelect, uint16_t clockSourceDivider, uint16_t clockSourcePredivider, uint16_t internalChannelMap)
DEPRECATED - Initializes the ADC12B Module.
This function initializes the ADC module to allow for analog-to-digital conversions. Specifically this function sets up the sample-and-hold signal and clock sources for the ADC core to use for conversions. Upon successful completion of the initialization all of the ADC control registers will be reset, excluding the memory controls and reference module bits, the given parameters will be set, and the ADC core will be turned on (Note, that the ADC core only draws power during conversions and remains off when not converting).Note that sample/hold signal sources are device dependent. Note that if re-initializing the ADC after starting a conversion with the startConversion() function, the disableConversion() must be called BEFORE this function can be called.
Parameters
baseAddress is the base address of the ADC12B module.
sampleHoldSignalSourceSelect is the signal that will trigger a sample-and-hold for an input signal to be converted. Valid values are:
ADC12_B_SAMPLEHOLDSOURCE_SC [Default]
ADC12_B_SAMPLEHOLDSOURCE_1
ADC12_B_SAMPLEHOLDSOURCE_2
ADC12_B_SAMPLEHOLDSOURCE_3
ADC12_B_SAMPLEHOLDSOURCE_4
ADC12_B_SAMPLEHOLDSOURCE_5
ADC12_B_SAMPLEHOLDSOURCE_6
ADC12_B_SAMPLEHOLDSOURCE_7 - This parameter is device specific and sources should be found in the device's datasheet.
Modified bits are ADC12SHSx of ADC12CTL1 register.
clockSourceSelect selects the clock that will be used by the ADC12B core, and the sampling timer if a sampling pulse mode is enabled. Valid values are:
ADC12_B_CLOCKSOURCE_ADC12OSC [Default] - MODOSC 5 MHz oscillator from the UCS
ADC12_B_CLOCKSOURCE_ACLK - The Auxiliary Clock
ADC12_B_CLOCKSOURCE_MCLK - The Master Clock
ADC12_B_CLOCKSOURCE_SMCLK - The Sub-Master Clock
Modified bits are ADC12SSELx of ADC12CTL1 register.
clockSourceDivider selects the amount that the clock will be divided. Valid values are:
ADC12_B_CLOCKDIVIDER_1 [Default]
ADC12_B_CLOCKDIVIDER_2
ADC12_B_CLOCKDIVIDER_3
ADC12_B_CLOCKDIVIDER_4
ADC12_B_CLOCKDIVIDER_5
ADC12_B_CLOCKDIVIDER_6
ADC12_B_CLOCKDIVIDER_7
ADC12_B_CLOCKDIVIDER_8
Modified bits are ADC12DIVx of ADC12CTL1 register.
clockSourcePredivider selects the amount that the clock will be predivided. Valid values are:
ADC12_B_CLOCKPREDIVIDER__1 [Default]
ADC12_B_CLOCKPREDIVIDER__4
ADC12_B_CLOCKPREDIVIDER__32
ADC12_B_CLOCKPREDIVIDER__64
Modified bits are ADC12PDIV of ADC12CTL1 register.
internalChannelMap selects what internal channel to map for ADC input channels Valid values are:
ADC12_B_MAPINTCH3
ADC12_B_MAPINTCH2
ADC12_B_MAPINTCH1
ADC12_B_MAPINTCH0
ADC12_B_TEMPSENSEMAP
ADC12_B_BATTMAP
ADC12_B_NOINTCH
Modified bits of ADC12CTL3 register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the initialization process.
References ADC12_B_initialize(), ADC12_B_initializeParam::clockSourceDivider, ADC12_B_initializeParam::clockSourcePredivider, ADC12_B_initializeParam::clockSourceSelect, ADC12_B_initializeParam::internalChannelMap, and ADC12_B_initializeParam::sampleHoldSignalSourceSelect.
bool ADC12_B_initialize (uint16_t baseAddress, ADC12_B_initializeParam * param)
Initializes the ADC12B Module.
This function initializes the ADC module to allow for analog-to-digital conversions. Specifically this function sets up the sample-and-hold signal and clock sources for the ADC core to use for conversions. Upon successful completion of the initialization all of the ADC control registers will be reset, excluding the memory controls and reference module bits, the given parameters will be set, and the ADC core will be turned on (Note, that the ADC core only draws power during conversions and remains off when not converting).Note that sample/hold signal sources are device dependent. Note that if re-initializing the ADC after starting a conversion with the startConversion() function, the disableConversion() must be called BEFORE this function can be called.
Parameters
baseAddress is the base address of the ADC12B module.
param is the pointer to struct for initialization.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the initialization process.
References ADC12_B_BATTMAP, ADC12_B_CLOCKDIVIDER_8, ADC12_B_CLOCKPREDIVIDER__1, ADC12_B_CLOCKPREDIVIDER__32, ADC12_B_CLOCKPREDIVIDER__4, ADC12_B_CLOCKPREDIVIDER__64, ADC12_B_CLOCKSOURCE_SMCLK, ADC12_B_SAMPLEHOLDSOURCE_3, ADC12DIV_7, ADC12ENC, ADC12ON, ADC12PDIV__64, ADC12RES_2, ADC12SC, ADC12_B_initializeParam::clockSourceDivider, ADC12_B_initializeParam::clockSourcePredivider, ADC12_B_initializeParam::clockSourceSelect, HWREG16, HWREG8, ADC12_B_initializeParam::internalChannelMap, OFS_ADC12CTL0, OFS_ADC12CTL0_L, OFS_ADC12CTL1, OFS_ADC12CTL2, OFS_ADC12CTL3, OFS_ADC12IER0, OFS_ADC12IER1, OFS_ADC12IER2, OFS_ADC12IFGR0, OFS_ADC12IFGR1, OFS_ADC12IFGR2, ADC12_B_initializeParam::sampleHoldSignalSourceSelect, and STATUS_SUCCESS.
Referenced by ADC12_B_init().
void ADC12_B_enable (uint16_t baseAddress)
Enables the ADC12B block.
This will enable operation of the ADC12B block.
Parameters
baseAddress is the base address of the ADC12B module.
Modified bits are ADC12ON of ADC12CTL0 register.
Returns
None
References ADC12ENC, ADC12ON, HWREG8, and OFS_ADC12CTL0_L.
void ADC12_B_disable (uint16_t baseAddress)
Disables the ADC12B block.
This will disable operation of the ADC12B block.
Parameters
baseAddress is the base address of the ADC12B module.
Modified bits are ADC12ON of ADC12CTL0 register.
Returns
None
References ADC12ENC, ADC12ON, HWREG8, and OFS_ADC12CTL0_L.
void ADC12_B_setupSamplingTimer (uint16_t baseAddress, uint16_t clockCycleHoldCountLowMem, uint16_t clockCycleHoldCountHighMem, uint16_t multipleSamplesEnabled)
Sets up and enables the Sampling Timer Pulse Mode.
This function sets up the sampling timer pulse mode which allows the sample/hold signal to trigger a sampling timer to sample-and-hold an input signal for a specified number of clock cycles without having to hold the sample/hold signal for the entire period of sampling. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12B module.
clockCycleHoldCountLowMem sets the amount of clock cycles to sample- and-hold for the higher memory buffers 0-7. Valid values are:
ADC12_B_CYCLEHOLD_4_CYCLES [Default]
ADC12_B_CYCLEHOLD_8_CYCLES
ADC12_B_CYCLEHOLD_16_CYCLES
ADC12_B_CYCLEHOLD_32_CYCLES
ADC12_B_CYCLEHOLD_64_CYCLES
ADC12_B_CYCLEHOLD_96_CYCLES
ADC12_B_CYCLEHOLD_128_CYCLES
ADC12_B_CYCLEHOLD_192_CYCLES
ADC12_B_CYCLEHOLD_256_CYCLES
ADC12_B_CYCLEHOLD_384_CYCLES
ADC12_B_CYCLEHOLD_512_CYCLES
ADC12_B_CYCLEHOLD_768_CYCLES
ADC12_B_CYCLEHOLD_1024_CYCLES
Modified bits are ADC12SHT0x of ADC12CTL0 register.
clockCycleHoldCountHighMem sets the amount of clock cycles to sample-and-hold for the higher memory buffers 8-15. Valid values are:
ADC12_B_CYCLEHOLD_4_CYCLES [Default]
ADC12_B_CYCLEHOLD_8_CYCLES
ADC12_B_CYCLEHOLD_16_CYCLES
ADC12_B_CYCLEHOLD_32_CYCLES
ADC12_B_CYCLEHOLD_64_CYCLES
ADC12_B_CYCLEHOLD_96_CYCLES
ADC12_B_CYCLEHOLD_128_CYCLES
ADC12_B_CYCLEHOLD_192_CYCLES
ADC12_B_CYCLEHOLD_256_CYCLES
ADC12_B_CYCLEHOLD_384_CYCLES
ADC12_B_CYCLEHOLD_512_CYCLES
ADC12_B_CYCLEHOLD_768_CYCLES
ADC12_B_CYCLEHOLD_1024_CYCLES
Modified bits are ADC12SHT1x of ADC12CTL0 register.
multipleSamplesEnabled allows multiple conversions to start without a trigger signal from the sample/hold signal Valid values are:
ADC12_B_MULTIPLESAMPLESDISABLE [Default] - a timer trigger will be needed to start every ADC conversion.
ADC12_B_MULTIPLESAMPLESENABLE - during a sequenced and/or repeated conversion mode, after the first conversion, no sample/hold signal is necessary to start subsequent sample/hold and convert processes.
Modified bits are ADC12MSC of ADC12CTL0 register.
Returns
None
References ADC12_B_CYCLEHOLD_1024_CYCLES, ADC12ENC, ADC12MSC, ADC12SHP, ADC12SHT0_15, ADC12SHT1_15, HWREG16, HWREG8, OFS_ADC12CTL0, OFS_ADC12CTL0_L, and OFS_ADC12CTL1.
void ADC12_B_disableSamplingTimer (uint16_t baseAddress)
Disables Sampling Timer Pulse Mode.
Disables the Sampling Timer Pulse Mode. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12B module.
Returns
None
References ADC12ENC, ADC12SHP, HWREG16, HWREG8, OFS_ADC12CTL0_L, and OFS_ADC12CTL1.
void ADC12_B_memoryConfigure (uint16_t baseAddress, uint8_t memoryBufferControlIndex, uint8_t inputSourceSelect, uint16_t refVoltageSourceSelect, uint16_t endOfSequence, uint16_t windowComparatorSelect, uint16_t differentialModeSelect)
DEPRECATED - Configures the controls of the selected memory buffer.
Maps an input signal conversion into the selected memory buffer, as well as the positive and negative reference voltages for each conversion being stored into this memory buffer. If the internal reference is used for the positive reference voltage, the internal REF module must be used to control the voltage level. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12B module.
memoryBufferControlIndex is the selected memory buffer to set the configuration for. Valid values are:
ADC12_B_MEMORY_0
ADC12_B_MEMORY_1
ADC12_B_MEMORY_2
ADC12_B_MEMORY_3
ADC12_B_MEMORY_4
ADC12_B_MEMORY_5
ADC12_B_MEMORY_6
ADC12_B_MEMORY_7
ADC12_B_MEMORY_8
ADC12_B_MEMORY_9
ADC12_B_MEMORY_10
ADC12_B_MEMORY_11
ADC12_B_MEMORY_12
ADC12_B_MEMORY_13
ADC12_B_MEMORY_14
ADC12_B_MEMORY_15
ADC12_B_MEMORY_16
ADC12_B_MEMORY_17
ADC12_B_MEMORY_18
ADC12_B_MEMORY_19
ADC12_B_MEMORY_20
ADC12_B_MEMORY_21
ADC12_B_MEMORY_22
ADC12_B_MEMORY_23
ADC12_B_MEMORY_24
ADC12_B_MEMORY_25
ADC12_B_MEMORY_26
ADC12_B_MEMORY_27
ADC12_B_MEMORY_28
ADC12_B_MEMORY_29
ADC12_B_MEMORY_30
ADC12_B_MEMORY_31
inputSourceSelect is the input that will store the converted data into the specified memory buffer. Valid values are:
ADC12_B_INPUT_A0 [Default]
ADC12_B_INPUT_A1
ADC12_B_INPUT_A2
ADC12_B_INPUT_A3
ADC12_B_INPUT_A4
ADC12_B_INPUT_A5
ADC12_B_INPUT_A6
ADC12_B_INPUT_A7
ADC12_B_INPUT_A8
ADC12_B_INPUT_A9
ADC12_B_INPUT_A10
ADC12_B_INPUT_A11
ADC12_B_INPUT_A12
ADC12_B_INPUT_A13
ADC12_B_INPUT_A14
ADC12_B_INPUT_A15
ADC12_B_INPUT_A16
ADC12_B_INPUT_A17
ADC12_B_INPUT_A18
ADC12_B_INPUT_A19
ADC12_B_INPUT_A20
ADC12_B_INPUT_A21
ADC12_B_INPUT_A22
ADC12_B_INPUT_A23
ADC12_B_INPUT_A24
ADC12_B_INPUT_A25
ADC12_B_INPUT_A26
ADC12_B_INPUT_A27
ADC12_B_INPUT_A28
ADC12_B_INPUT_A29
ADC12_B_INPUT_TCMAP
ADC12_B_INPUT_BATMAP
Modified bits are ADC12INCHx of ADC12MCTLx register.
refVoltageSourceSelect is the reference voltage source to set as the upper/lower limits for the conversion stored in the specified memory. Valid values are:
ADC12_B_VREFPOS_AVCC_VREFNEG_VSS [Default]
ADC12_B_VREFPOS_INTBUF_VREFNEG_VSS
ADC12_B_VREFPOS_EXTNEG_VREFNEG_VSS
ADC12_B_VREFPOS_EXTBUF_VREFNEG_VSS
ADC12_B_VREFPOS_EXTPOS_VREFNEG_VSS
ADC12_B_VREFPOS_AVCC_VREFNEG_EXTBUF
ADC12_B_VREFPOS_AVCC_VREFNEG_EXTPOS
ADC12_B_VREFPOS_INTBUF_VREFNEG_EXTPOS
ADC12_B_VREFPOS_AVCC_VREFNEG_INTBUF
ADC12_B_VREFPOS_EXTPOS_VREFNEG_INTBUF
ADC12_B_VREFPOS_AVCC_VREFNEG_EXTNEG
ADC12_B_VREFPOS_INTBUF_VREFNEG_EXTNEG
ADC12_B_VREFPOS_EXTPOS_VREFNEG_EXTNEG
ADC12_B_VREFPOS_EXTBUF_VREFNEG_EXTNEG
Modified bits are ADC12VRSEL of ADC12MCTLx register.
endOfSequence indicates that the specified memory buffer will be the end of the sequence if a sequenced conversion mode is selected Valid values are:
ADC12_B_NOTENDOFSEQUENCE [Default] - The specified memory buffer will NOT be the end of the sequence OR a sequenced conversion mode is not selected.
ADC12_B_ENDOFSEQUENCE - The specified memory buffer will be the end of the sequence.
Modified bits are ADC12EOS of ADC12MCTLx register.
windowComparatorSelect sets the window comparator mode Valid values are:
ADC12_B_WINDOW_COMPARATOR_DISABLE [Default]
ADC12_B_WINDOW_COMPARATOR_ENABLE
differentialModeSelect sets the differential mode Valid values are:
ADC12_B_DIFFERENTIAL_MODE_DISABLE [Default]
ADC12_B_DIFFERENTIAL_MODE_ENABLE
Returns
None
References ADC12_B_configureMemory(), ADC12_B_configureMemoryParam::differentialModeSelect, ADC12_B_configureMemoryParam::endOfSequence, ADC12_B_configureMemoryParam::inputSourceSelect, ADC12_B_configureMemoryParam::memoryBufferControlIndex, ADC12_B_configureMemoryParam::refVoltageSourceSelect, and ADC12_B_configureMemoryParam::windowComparatorSelect.
void ADC12_B_configureMemory (uint16_t baseAddress, ADC12_B_configureMemoryParam * param)
Configures the controls of the selected memory buffer.
Maps an input signal conversion into the selected memory buffer, as well as the positive and negative reference voltages for each conversion being stored into this memory buffer. If the internal reference is used for the positive reference voltage, the internal REF module must be used to control the voltage level. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12B module.
param is the pointer to struct for ADC12B memory configuration.
Returns
None
References ADC12_B_INPUT_BATMAP, ADC12_B_MEMORY_0, ADC12_B_MEMORY_1, ADC12_B_MEMORY_10, ADC12_B_MEMORY_11, ADC12_B_MEMORY_12, ADC12_B_MEMORY_13, ADC12_B_MEMORY_14, ADC12_B_MEMORY_15, ADC12_B_MEMORY_16, ADC12_B_MEMORY_17, ADC12_B_MEMORY_18, ADC12_B_MEMORY_19, ADC12_B_MEMORY_2, ADC12_B_MEMORY_20, ADC12_B_MEMORY_21, ADC12_B_MEMORY_22, ADC12_B_MEMORY_23, ADC12_B_MEMORY_24, ADC12_B_MEMORY_25, ADC12_B_MEMORY_26, ADC12_B_MEMORY_27, ADC12_B_MEMORY_28, ADC12_B_MEMORY_29, ADC12_B_MEMORY_3, ADC12_B_MEMORY_30, ADC12_B_MEMORY_31, ADC12_B_MEMORY_4, ADC12_B_MEMORY_5, ADC12_B_MEMORY_6, ADC12_B_MEMORY_7, ADC12_B_MEMORY_8, ADC12_B_MEMORY_9, ADC12_B_VREFPOS_EXTBUF_VREFNEG_EXTNEG, ADC12DIF, ADC12ENC, ADC12WINC, ADC12_B_configureMemoryParam::differentialModeSelect, ADC12_B_configureMemoryParam::endOfSequence, HWREG16, HWREG8, ADC12_B_configureMemoryParam::inputSourceSelect, ADC12_B_configureMemoryParam::memoryBufferControlIndex, OFS_ADC12CTL0_L, OFS_ADC12MCTL0, ADC12_B_configureMemoryParam::refVoltageSourceSelect, and ADC12_B_configureMemoryParam::windowComparatorSelect.
Referenced by ADC12_B_memoryConfigure().
void ADC12_B_setWindowCompAdvanced (uint16_t baseAddress, uint16_t highThreshold, uint16_t lowThreshold)
Sets the high and low threshold for the window comparator feature.
Sets the high and low threshold for the window comparator feature. Use the ADC12HIIE, ADC12INIE, ADC12LOIE interrupts to utilize this feature.
Parameters
baseAddress is the base address of the ADC12B module.
highThreshold is the upper bound that could trip an interrupt for the window comparator.
lowThreshold is the lower bound that could trip on interrupt for the window comparator.
Returns
None
References HWREG16, OFS_ADC12HI, and OFS_ADC12LO.
void ADC12_B_enableInterrupt (uint16_t baseAddress, uint16_t interruptMask0, uint16_t interruptMask1, uint16_t interruptMask2)
Enables selected ADC12B interrupt sources.
Enables the indicated ADC12B interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the ADC12B module.
interruptMask0 is the bit mask of the memory buffer and overflow interrupt sources to be enabled. If the desired interrupt is not available in the selection for interruptMask0, then simply pass in a '0' for this value. Valid values are:
ADC12_B_IE0
ADC12_B_IE1
ADC12_B_IE2
ADC12_B_IE3
ADC12_B_IE4
ADC12_B_IE5
ADC12_B_IE6
ADC12_B_IE7
ADC12_B_IE8
ADC12_B_IE9
ADC12_B_IE10
ADC12_B_IE11
ADC12_B_IE12
ADC12_B_IE13
ADC12_B_IE14
ADC12_B_IE15
interruptMask1 is the bit mask of the memory buffer and overflow interrupt sources to be enabled. If the desired interrupt is not available in the selection for interruptMask1, then simply pass in a '0' for this value. Valid values are:
ADC12_B_IE16
ADC12_B_IE17
ADC12_B_IE18
ADC12_B_IE19
ADC12_B_IE20
ADC12_B_IE21
ADC12_B_IE22
ADC12_B_IE23
ADC12_B_IE24
ADC12_B_IE25
ADC12_B_IE26
ADC12_B_IE27
ADC12_B_IE28
ADC12_B_IE29
ADC12_B_IE30
ADC12_B_IE31
interruptMask2 is the bit mask of the memory buffer and overflow interrupt sources to be enabled. If the desired interrupt is not available in the selection for interruptMask2, then simply pass in a '0' for this value. Valid values are:
ADC12_B_INIE - Interrupt enable for a conversion in the result register is either greater than the ADC12LO or lower than the ADC12HI threshold. GIE bit must be set to enable the interrupt.
ADC12_B_LOIE - Interrupt enable for the falling short of the lower limit interrupt of the window comparator for the result register. GIE bit must be set to enable the interrupt.
ADC12_B_HIIE - Interrupt enable for the exceeding the upper limit of the window comparator for the result register. GIE bit must be set to enable the interrupt.
ADC12_B_OVIE - Interrupt enable for a conversion that is about to save to a memory buffer that has not been read out yet. GIE bit must be set to enable the interrupt.
ADC12_B_TOVIE - enable for a conversion that is about to start before the previous conversion has been completed. GIE bit must be set to enable the interrupt.
ADC12_B_RDYIE - enable for the local buffered reference ready signal. GIE bit must be set to enable the interrupt.
Modified bits of ADC12IERx register.
Returns
None
References ADC12_B_HIIE, ADC12_B_INIE, ADC12_B_LOIE, ADC12_B_OVIE, ADC12_B_RDYIE, ADC12_B_TOVIE, HWREG16, OFS_ADC12IER0, OFS_ADC12IER1, and OFS_ADC12IER2.
void ADC12_B_disableInterrupt (uint16_t baseAddress, uint16_t interruptMask0, uint16_t interruptMask1, uint16_t interruptMask2)
Disables selected ADC12B interrupt sources.
Disables the indicated ADC12B interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the ADC12B module.
interruptMask0 is the bit mask of the memory buffer and overflow interrupt sources to be disabled. If the desired interrupt is not available in the selection for interruptMask0, then simply pass in a '0' for this value. Valid values are:
ADC12_B_IE0
ADC12_B_IE1
ADC12_B_IE2
ADC12_B_IE3
ADC12_B_IE4
ADC12_B_IE5
ADC12_B_IE6
ADC12_B_IE7
ADC12_B_IE8
ADC12_B_IE9
ADC12_B_IE10
ADC12_B_IE11
ADC12_B_IE12
ADC12_B_IE13
ADC12_B_IE14
ADC12_B_IE15
interruptMask1 is the bit mask of the memory buffer and overflow interrupt sources to be disabled. If the desired interrupt is not available in the selection for interruptMask1, then simply pass in a '0' for this value. Valid values are:
ADC12_B_IE16
ADC12_B_IE17
ADC12_B_IE18
ADC12_B_IE19
ADC12_B_IE20
ADC12_B_IE21
ADC12_B_IE22
ADC12_B_IE23
ADC12_B_IE24
ADC12_B_IE25
ADC12_B_IE26
ADC12_B_IE27
ADC12_B_IE28
ADC12_B_IE29
ADC12_B_IE30
ADC12_B_IE31
interruptMask2 is the bit mask of the memory buffer and overflow interrupt sources to be disabled. If the desired interrupt is not available in the selection for interruptMask2, then simply pass in a '0' for this value. Valid values are:
ADC12_B_INIE - Interrupt enable for a conversion in the result register is either greater than the ADC12LO or lower than the ADC12HI threshold. GIE bit must be set to enable the interrupt.
ADC12_B_LOIE - Interrupt enable for the falling short of the lower limit interrupt of the window comparator for the result register. GIE bit must be set to enable the interrupt.
ADC12_B_HIIE - Interrupt enable for the exceeding the upper limit of the window comparator for the result register. GIE bit must be set to enable the interrupt.
ADC12_B_OVIE - Interrupt enable for a conversion that is about to save to a memory buffer that has not been read out yet. GIE bit must be set to enable the interrupt.
ADC12_B_TOVIE - enable for a conversion that is about to start before the previous conversion has been completed. GIE bit must be set to enable the interrupt.
ADC12_B_RDYIE - enable for the local buffered reference ready signal. GIE bit must be set to enable the interrupt.
Modified bits of ADC12IERx register.
Returns
None
References ADC12_B_HIIE, ADC12_B_INIE, ADC12_B_LOIE, ADC12_B_OVIE, ADC12_B_RDYIE, ADC12_B_TOVIE, HWREG16, OFS_ADC12IER0, OFS_ADC12IER1, and OFS_ADC12IER2.
void ADC12_B_clearInterrupt (uint16_t baseAddress, uint8_t interruptRegisterChoice, uint16_t memoryInterruptFlagMask)
Clears ADC12B selected interrupt flags.
Modified registers are ADC12IFG .
Parameters
baseAddress is the base address of the ADC12B module.
interruptRegisterChoice is either 0, 1, or 2, to choose the correct interrupt register to update
memoryInterruptFlagMask is the bit mask of the memory buffer and overflow interrupt flags to be cleared. Valid values are:
ADC12_B_IFG0 - interruptRegisterChoice = 0
ADC12_B_IFG1
ADC12_B_IFG2
ADC12_B_IFG3
ADC12_B_IFG4
ADC12_B_IFG5
ADC12_B_IFG6
ADC12_B_IFG7
ADC12_B_IFG8
ADC12_B_IFG9
ADC12_B_IFG10
ADC12_B_IFG11
ADC12_B_IFG12
ADC12_B_IFG13
ADC12_B_IFG14
ADC12_B_IFG15
ADC12_B_IFG16 - interruptRegisterChoice = 1
ADC12_B_IFG17
ADC12_B_IFG18
ADC12_B_IFG19
ADC12_B_IFG20
ADC12_B_IFG21
ADC12_B_IFG22
ADC12_B_IFG23
ADC12_B_IFG24
ADC12_B_IFG25
ADC12_B_IFG26
ADC12_B_IFG27
ADC12_B_IFG28
ADC12_B_IFG29
ADC12_B_IFG30
ADC12_B_IFG31
ADC12_B_INIFG - interruptRegisterChoice = 2
ADC12_B_LOIFG
ADC12_B_HIIFG
ADC12_B_OVIFG
ADC12_B_TOVIFG
ADC12_B_RDYIFG - The selected ADC12B interrupt flags are cleared, so that it no longer asserts. The memory buffer interrupt flags are only cleared when the memory buffer is accessed. Note that the overflow interrupts do not have an interrupt flag to clear; they must be accessed directly from the interrupt vector.
Returns
None
References HWREG16, and OFS_ADC12IFGR0.
uint16_t ADC12_B_getInterruptStatus (uint16_t baseAddress, uint8_t interruptRegisterChoice, uint16_t memoryInterruptFlagMask)
Returns the status of the selected memory interrupt flags.
Returns the status of the selected memory interrupt flags. Note that the overflow interrupts do not have an interrupt flag to clear; they must be accessed directly from the interrupt vector.
Parameters
baseAddress is the base address of the ADC12B module.
interruptRegisterChoice is either 0, 1, or 2, to choose the correct interrupt register to update
memoryInterruptFlagMask is the bit mask of the memory buffer and overflow interrupt flags to be cleared. Valid values are:
ADC12_B_IFG0 - interruptRegisterChoice = 0
ADC12_B_IFG1
ADC12_B_IFG2
ADC12_B_IFG3
ADC12_B_IFG4
ADC12_B_IFG5
ADC12_B_IFG6
ADC12_B_IFG7
ADC12_B_IFG8
ADC12_B_IFG9
ADC12_B_IFG10
ADC12_B_IFG11
ADC12_B_IFG12
ADC12_B_IFG13
ADC12_B_IFG14
ADC12_B_IFG15
ADC12_B_IFG16 - interruptRegisterChoice = 1
ADC12_B_IFG17
ADC12_B_IFG18
ADC12_B_IFG19
ADC12_B_IFG20
ADC12_B_IFG21
ADC12_B_IFG22
ADC12_B_IFG23
ADC12_B_IFG24
ADC12_B_IFG25
ADC12_B_IFG26
ADC12_B_IFG27
ADC12_B_IFG28
ADC12_B_IFG29
ADC12_B_IFG30
ADC12_B_IFG31
ADC12_B_INIFG - interruptRegisterChoice = 2
ADC12_B_LOIFG
ADC12_B_HIIFG
ADC12_B_OVIFG
ADC12_B_TOVIFG
ADC12_B_RDYIFG - The selected ADC12B interrupt flags are cleared, so that it no longer asserts. The memory buffer interrupt flags are only cleared when the memory buffer is accessed. Note that the overflow interrupts do not have an interrupt flag to clear; they must be accessed directly from the interrupt vector.
Returns
The current interrupt flag status for the corresponding mask.
References HWREG16, and OFS_ADC12IFGR0.
void ADC12_B_startConversion (uint16_t baseAddress, uint16_t startingMemoryBufferIndex, uint8_t conversionSequenceModeSelect)
Enables/Starts an Analog-to-Digital Conversion.
Enables/starts the conversion process of the ADC. If the sample/hold signal source chosen during initialization was ADC12OSC, then the conversion is started immediately, otherwise the chosen sample/hold signal source starts the conversion by a rising edge of the signal. Keep in mind when selecting conversion modes, that for sequenced and/or repeated modes, to keep the sample/hold-and-convert process continuing without a trigger from the sample/hold signal source, the multiple samples must be enabled using the ADC12_B_setupSamplingTimer() function. Note that after this function is called, the ADC12_B_stopConversions() has to be called to re-initialize the ADC, reconfigure a memory buffer control, enable/disable the sampling timer, or to change the internal reference voltage.
Parameters
baseAddress is the base address of the ADC12B module.
startingMemoryBufferIndex is the memory buffer that will hold the first or only conversion. Valid values are:
ADC12_B_START_AT_ADC12MEM0 [Default]
ADC12_B_START_AT_ADC12MEM1
ADC12_B_START_AT_ADC12MEM2
ADC12_B_START_AT_ADC12MEM3
ADC12_B_START_AT_ADC12MEM4
ADC12_B_START_AT_ADC12MEM5
ADC12_B_START_AT_ADC12MEM6
ADC12_B_START_AT_ADC12MEM7
ADC12_B_START_AT_ADC12MEM8
ADC12_B_START_AT_ADC12MEM9
ADC12_B_START_AT_ADC12MEM10
ADC12_B_START_AT_ADC12MEM11
ADC12_B_START_AT_ADC12MEM12
ADC12_B_START_AT_ADC12MEM13
ADC12_B_START_AT_ADC12MEM14
ADC12_B_START_AT_ADC12MEM15
ADC12_B_START_AT_ADC12MEM16
ADC12_B_START_AT_ADC12MEM17
ADC12_B_START_AT_ADC12MEM18
ADC12_B_START_AT_ADC12MEM19
ADC12_B_START_AT_ADC12MEM20
ADC12_B_START_AT_ADC12MEM21
ADC12_B_START_AT_ADC12MEM22
ADC12_B_START_AT_ADC12MEM23
ADC12_B_START_AT_ADC12MEM24
ADC12_B_START_AT_ADC12MEM25
ADC12_B_START_AT_ADC12MEM26
ADC12_B_START_AT_ADC12MEM27
ADC12_B_START_AT_ADC12MEM28
ADC12_B_START_AT_ADC12MEM29
ADC12_B_START_AT_ADC12MEM30
ADC12_B_START_AT_ADC12MEM31
Modified bits are ADC12CSTARTADDx of ADC12CTL1 register.
conversionSequenceModeSelect determines the ADC operating mode. Valid values are:
ADC12_B_SINGLECHANNEL [Default] - one-time conversion of a single channel into a single memory buffer.
ADC12_B_SEQOFCHANNELS - one time conversion of multiple channels into the specified starting memory buffer and each subsequent memory buffer up until the conversion is stored in a memory buffer dedicated as the end-of-sequence by the memory's control register.
ADC12_B_REPEATED_SINGLECHANNEL - repeated conversions of one channel into a single memory buffer.
ADC12_B_REPEATED_SEQOFCHANNELS - repeated conversions of multiple channels into the specified starting memory buffer and each subsequent memory buffer up until the conversion is stored in a memory buffer dedicated as the end-of-sequence by the memory's control register.
Modified bits are ADC12CONSEQx of ADC12CTL1 register.
Modified bits of ADC12CTL1 register and bits of ADC12CTL0 register.
Returns
None
References ADC12_B_MEMORY_15, ADC12_B_REPEATED_SEQOFCHANNELS, ADC12CONSEQ_3, ADC12CSTARTADD_31, ADC12ENC, ADC12SC, HWREG16, HWREG8, OFS_ADC12CTL0_L, OFS_ADC12CTL1, and OFS_ADC12CTL3.
void ADC12_B_disableConversions (uint16_t baseAddress, bool preempt)
Disables the ADC from converting any more signals.
Disables the ADC from converting any more signals. If there is a conversion in progress, this function can stop it immediately if the preempt parameter is set as ADC12_B_PREEMPTCONVERSION, by changing the conversion mode to single-channel, single-conversion and disabling conversions. If the conversion mode is set as single-channel, single-conversion and this function is called without preemption, then the ADC core conversion status is polled until the conversion is complete before disabling conversions to prevent unpredictable data. If the ADC12_B_startConversion() has been called, then this function has to be called to re-initialize the ADC, reconfigure a memory buffer control, enable/disable the sampling pulse mode, or change the internal reference voltage.
Parameters
baseAddress is the base address of the ADC12B module.
preempt specifies if the current conversion should be preemptively stopped before the end of the conversion. Valid values are:
ADC12_B_COMPLETECONVERSION - Allows the ADC12B to end the current conversion before disabling conversions.
ADC12_B_PREEMPTCONVERSION - Stops the ADC12B immediately, with unpredictable results of the current conversion.
Modified bits of ADC12CTL1 register and bits of ADC12CTL0 register.
Returns
None
References ADC12_B_isBusy(), ADC12_B_PREEMPTCONVERSION, ADC12CONSEQ_3, ADC12ENC, HWREG8, OFS_ADC12CTL0_L, and OFS_ADC12CTL1_L.
uint16_t ADC12_B_getResults (uint16_t baseAddress, uint8_t memoryBufferIndex)
Returns the raw contents of the specified memory buffer.
Returns the raw contents of the specified memory buffer. The format of the content depends on the read-back format of the data: if the data is in signed 2's complement format then the contents in the memory buffer will be left-justified with the least-significant bits as 0's, whereas if the data is in unsigned format then the contents in the memory buffer will be right- justified with the most-significant bits as 0's.
Parameters
baseAddress is the base address of the ADC12B module.
memoryBufferIndex is the specified memory buffer to read. Valid values are:
ADC12_B_MEMORY_0
ADC12_B_MEMORY_1
ADC12_B_MEMORY_2
ADC12_B_MEMORY_3
ADC12_B_MEMORY_4
ADC12_B_MEMORY_5
ADC12_B_MEMORY_6
ADC12_B_MEMORY_7
ADC12_B_MEMORY_8
ADC12_B_MEMORY_9
ADC12_B_MEMORY_10
ADC12_B_MEMORY_11
ADC12_B_MEMORY_12
ADC12_B_MEMORY_13
ADC12_B_MEMORY_14
ADC12_B_MEMORY_15
ADC12_B_MEMORY_16
ADC12_B_MEMORY_17
ADC12_B_MEMORY_18
ADC12_B_MEMORY_19
ADC12_B_MEMORY_20
ADC12_B_MEMORY_21
ADC12_B_MEMORY_22
ADC12_B_MEMORY_23
ADC12_B_MEMORY_24
ADC12_B_MEMORY_25
ADC12_B_MEMORY_26
ADC12_B_MEMORY_27
ADC12_B_MEMORY_28
ADC12_B_MEMORY_29
ADC12_B_MEMORY_30
ADC12_B_MEMORY_31
Returns
A signed integer of the contents of the specified memory buffer.
References ADC12_B_MEMORY_31, HWREG16, and OFS_ADC12MEM0.
void ADC12_B_setResolution (uint16_t baseAddress, uint8_t resolutionSelect)
Use to change the resolution of the converted data.
This function can be used to change the resolution of the converted data from the default of 12-bits.
Parameters
baseAddress is the base address of the ADC12B module.
resolutionSelect determines the resolution of the converted data. Valid values are:
ADC12_B_RESOLUTION_8BIT
ADC12_B_RESOLUTION_10BIT
ADC12_B_RESOLUTION_12BIT [Default]
Modified bits are ADC12RESx of ADC12CTL2 register.
Returns
None
References ADC12_B_RESOLUTION_12BIT, ADC12RES_3, HWREG8, and OFS_ADC12CTL2_L.
void ADC12_B_setSampleHoldSignalInversion (uint16_t baseAddress, uint16_t invertedSignal)
Use to invert or un-invert the sample/hold signal.
This function can be used to invert or un-invert the sample/hold signal. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12B module.
invertedSignal set if the sample/hold signal should be inverted Valid values are:
ADC12_B_NONINVERTEDSIGNAL [Default] - a sample-and-hold of an input signal for conversion will be started on a rising edge of the sample/hold signal.
ADC12_B_INVERTEDSIGNAL - a sample-and-hold of an input signal for conversion will be started on a falling edge of the sample/hold signal.
Modified bits are ADC12ISSH of ADC12CTL1 register.
Returns
None
References ADC12ENC, ADC12ISSH, HWREG16, HWREG8, OFS_ADC12CTL0_L, and OFS_ADC12CTL1.
void ADC12_B_setDataReadBackFormat (uint16_t baseAddress, uint8_t readBackFormat)
Use to set the read-back format of the converted data.
Sets the format of the converted data: how it will be stored into the memory buffer, and how it should be read back. The format can be set as right-justified (default), which indicates that the number will be unsigned, or left-justified, which indicates that the number will be signed in 2's complement format. This change affects all memory buffers for subsequent conversions.
Parameters
baseAddress is the base address of the ADC12B module.
readBackFormat is the specified format to store the conversions in the memory buffer. Valid values are:
ADC12_B_UNSIGNED_BINARY [Default]
ADC12_B_SIGNED_2SCOMPLEMENT
Modified bits are ADC12DF of ADC12CTL2 register.
Returns
None
References ADC12_B_SIGNED_2SCOMPLEMENT, ADC12DF, HWREG8, and OFS_ADC12CTL2_L.
void ADC12_B_setAdcPowerMode (uint16_t baseAddress, uint8_t powerMode)
Use to set the ADC's power conservation mode if the sampling rate is at 50-ksps or less.
Sets ADC's power mode. If the user has a sampling rate greater than 50-ksps, then he/she can only enable ADC12_B_REGULARPOWERMODE. If the sampling rate is 50-ksps or less, the user can enable ADC12_B_LOWPOWERMODE granting additional power savings.
Parameters
baseAddress is the base address of the ADC12B module.
powerMode is the specified maximum sampling rate. Valid values are:
ADC12_B_REGULARPOWERMODE [Default] - If sampling rate is greater than 50-ksps, there is no power saving feature available.
ADC12_B_LOWPOWERMODE - If sampling rate is less than or equal to 50-ksps, select this value to save power
Modified bits are ADC12SR of ADC12CTL2 register.
Returns
None
References ADC12_B_LOWPOWERMODE, ADC12_B_REGULARPOWERMODE, ADC12PWRMD, HWREG8, and OFS_ADC12CTL2_L.
uint32_t ADC12_B_getMemoryAddressForDMA (uint16_t baseAddress, uint8_t memoryIndex)
Returns the address of the specified memory buffer for the DMA module.
Returns the address of the specified memory buffer. This can be used in conjunction with the DMA to store the converted data directly to memory.
Parameters
baseAddress is the base address of the ADC12B module.
memoryIndex is the memory buffer to return the address of. Valid values are:
ADC12_B_MEMORY_0
ADC12_B_MEMORY_1
ADC12_B_MEMORY_2
ADC12_B_MEMORY_3
ADC12_B_MEMORY_4
ADC12_B_MEMORY_5
ADC12_B_MEMORY_6
ADC12_B_MEMORY_7
ADC12_B_MEMORY_8
ADC12_B_MEMORY_9
ADC12_B_MEMORY_10
ADC12_B_MEMORY_11
ADC12_B_MEMORY_12
ADC12_B_MEMORY_13
ADC12_B_MEMORY_14
ADC12_B_MEMORY_15
ADC12_B_MEMORY_16
ADC12_B_MEMORY_17
ADC12_B_MEMORY_18
ADC12_B_MEMORY_19
ADC12_B_MEMORY_20
ADC12_B_MEMORY_21
ADC12_B_MEMORY_22
ADC12_B_MEMORY_23
ADC12_B_MEMORY_24
ADC12_B_MEMORY_25
ADC12_B_MEMORY_26
ADC12_B_MEMORY_27
ADC12_B_MEMORY_28
ADC12_B_MEMORY_29
ADC12_B_MEMORY_30
ADC12_B_MEMORY_31
Returns
address of the specified memory buffer
References OFS_ADC12MEM0.
uint8_t ADC12_B_isBusy (uint16_t baseAddress)
Returns the busy status of the ADC12B core.
Returns the status of the ADC core if there is a conversion currently taking place.
Parameters
baseAddress is the base address of the ADC12B module.
Returns
ADC12_B_BUSY or ADC12_B_NOTBUSY dependent if there is a conversion currently taking place. Return one of the following:
ADC12_B_NOTBUSY
ADC12_B_BUSY
indicating if a conversion is taking place
References ADC12BUSY, HWREG8, and OFS_ADC12CTL1_L.
Referenced by ADC12_B_disableConversions().
Copyright 2014, Texas Instruments Incorporated