Timer_b_api
Timer_b_api
Functions
void TIMER_B_startCounter (uint16_t baseAddress, uint16_t timerMode)
Starts TIMER_B counter.
void TIMER_B_initContinuousMode (uint16_t baseAddress, TIMER_B_initContinuousModeParam *param)
Configures TIMER_B in continuous mode.
void TIMER_B_configureContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TBIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_B in continuous mode.
void TIMER_B_initUpMode (uint16_t baseAddress, TIMER_B_initUpModeParam *param)
Configures TIMER_B in up mode.
void TIMER_B_configureUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_B in up mode.
void TIMER_B_initUpDownMode (uint16_t baseAddress, TIMER_B_initUpDownModeParam *param)
Configures TIMER_B in up down mode.
void TIMER_B_configureUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_B in up down mode.
void TIMER_B_startContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TBIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_B_configureContinuousMode and TIMER_B_startCounter API. Starts TIMER_B in continuous mode.
void TIMER_B_startContinousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TBIE, uint16_t timerClear)
DEPRECATED - Spelling Error Fixed. Starts TIMER_B in continuous mode.
void TIMER_B_startUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_B_configureUpMode and TIMER_B_startCounter API. Starts TIMER_B in up mode.
void TIMER_B_startUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_B_configureUpDownMode and TIMER_B_startCounter API. Starts TIMER_B in up down mode.
void TIMER_B_initCaptureMode (uint16_t baseAddress, TIMER_B_initCaptureModeParam *param)
Initializes Capture Mode.
void TIMER_B_initCapture (uint16_t baseAddress, uint16_t captureRegister, uint16_t captureMode, uint16_t captureInputSelect, uint16_t synchronizeCaptureSource, uint16_t captureInterruptEnable, uint16_t captureOutputMode)
DEPRECATED - Initializes Capture Mode.
void TIMER_B_initCompareMode (uint16_t baseAddress, TIMER_B_initCompareModeParam *param)
Initializes Compare Mode.
void TIMER_B_initCompare (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareInterruptEnable, uint16_t compareOutputMode, uint16_t compareValue)
DEPRECATED - Initializes Compare Mode.
void TIMER_B_enableInterrupt (uint16_t baseAddress)
Enable TIMER_B interrupt.
void TIMER_B_disableInterrupt (uint16_t baseAddress)
Disable TIMER_B interrupt.
uint32_t TIMER_B_getInterruptStatus (uint16_t baseAddress)
Get TIMER_B interrupt status.
void TIMER_B_enableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Enable capture compare interrupt.
void TIMER_B_disableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Disable capture compare interrupt.
uint32_t TIMER_B_getCaptureCompareInterruptStatus (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t mask)
Return capture compare interrupt status.
void TIMER_B_clear (uint16_t baseAddress)
Reset/Clear the TIMER_B clock divider, count direction, count.
uint8_t TIMER_B_getSynchronizedCaptureCompareInput (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t synchronized)
Get synchronized capturecompare input.
uint8_t TIMER_B_getOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister)
Get output bit for output mode.
uint16_t TIMER_B_getCaptureCompareCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare count.
void TIMER_B_setOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister, uint8_t outputModeOutBitValue)
Set output bit for output mode.
void TIMER_B_outputPWM (uint16_t baseAddress, TIMER_B_outputPWMParam *param)
Generate a PWM with TIMER_B running in up mode.
void TIMER_B_generatePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t compareRegister, uint16_t compareOutputMode, uint16_t dutyCycle)
DEPRECATED - Generate a PWM with TIMER_B running in up mode.
void TIMER_B_stop (uint16_t baseAddress)
Stops the TIMER_B.
void TIMER_B_setCompareValue (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareValue)
Sets the value of the capture-compare register.
void TIMER_B_clearTimerInterruptFlag (uint16_t baseAddress)
Clears the TIMER_B TBIFG interrupt flag.
void TIMER_B_clearCaptureCompareInterruptFlag (uint16_t baseAddress, uint16_t captureCompareRegister)
Clears the capture-compare interrupt flag.
void TIMER_B_selectCounterLength (uint16_t baseAddress, uint16_t counterLength)
Selects TIMER_B counter length.
void TIMER_B_selectLatchingGroup (uint16_t baseAddress, uint16_t groupLatch)
Selects TIMER_B Latching Group.
void TIMER_B_initCompareLatchLoadEvent (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareLatchLoadEvent)
Selects Compare Latch Load Event.
uint16_t TIMER_B_getCounterValue (uint16_t baseAddress)
Reads the current timer count value.
Detailed Description
Function Documentation
void TIMER_B_startCounter (uint16_t baseAddress, uint16_t timerMode)
Starts TIMER_B counter.
This function assumes that the timer has been previously configured using TIMER_B_configureContinuousMode, TIMER_B_configureUpMode or TIMER_B_configureUpDownMode.
Parameters
baseAddress is the base address of the TIMER_B module.
timerMode selects the mode of the timer Valid values are:
TIMER_B_STOP_MODE
TIMER_B_UP_MODE
TIMER_B_CONTINUOUS_MODE [Default]
TIMER_B_UPDOWN_MODE
Modified bits of TBxCTL register.
Returns
None
References HWREG16, OFS_TBxCTL, TIMER_B_CONTINUOUS_MODE, TIMER_B_UP_MODE, and TIMER_B_UPDOWN_MODE.
void TIMER_B_initContinuousMode (uint16_t baseAddress, TIMER_B_initContinuousModeParam * param)
Configures TIMER_B in continuous mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_B_startCounter API.
Parameters
baseAddress is the base address of the TIMER_B module.
param is the pointer to struct for continuous mode initialization.
Modified bits of TBxCTL register.
Returns
None
References TIMER_B_initContinuousModeParam::clockSource, TIMER_B_initContinuousModeParam::clockSourceDivider, CNTL_3, HWREG16, ID__8, OFS_TBxCTL, OFS_TBxEX0, TIMER_B_initContinuousModeParam::startTimer, TBIDEX_7, TIMER_B_CLOCKSOURCE_ACLK, TIMER_B_CLOCKSOURCE_DIVIDER_1, TIMER_B_CLOCKSOURCE_DIVIDER_10, TIMER_B_CLOCKSOURCE_DIVIDER_12, TIMER_B_CLOCKSOURCE_DIVIDER_14, TIMER_B_CLOCKSOURCE_DIVIDER_16, TIMER_B_CLOCKSOURCE_DIVIDER_2, TIMER_B_CLOCKSOURCE_DIVIDER_20, TIMER_B_CLOCKSOURCE_DIVIDER_24, TIMER_B_CLOCKSOURCE_DIVIDER_28, TIMER_B_CLOCKSOURCE_DIVIDER_3, TIMER_B_CLOCKSOURCE_DIVIDER_32, TIMER_B_CLOCKSOURCE_DIVIDER_4, TIMER_B_CLOCKSOURCE_DIVIDER_40, TIMER_B_CLOCKSOURCE_DIVIDER_48, TIMER_B_CLOCKSOURCE_DIVIDER_5, TIMER_B_CLOCKSOURCE_DIVIDER_56, TIMER_B_CLOCKSOURCE_DIVIDER_6, TIMER_B_CLOCKSOURCE_DIVIDER_64, TIMER_B_CLOCKSOURCE_DIVIDER_7, TIMER_B_CLOCKSOURCE_DIVIDER_8, TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_SMCLK, TIMER_B_CONTINUOUS_MODE, TIMER_B_DO_CLEAR, TIMER_B_SKIP_CLEAR, TIMER_B_TBIE_INTERRUPT_DISABLE, TIMER_B_TBIE_INTERRUPT_ENABLE, TIMER_B_UPDOWN_MODE, TIMER_B_initContinuousModeParam::timerClear, and TIMER_B_initContinuousModeParam::timerInterruptEnable_TBIE.
Referenced by TIMER_B_configureContinuousMode(), and TIMER_B_startContinuousMode().
void TIMER_B_configureContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TBIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_B in continuous mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_B_startCounter API.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register.
Returns
None
References TIMER_B_initContinuousModeParam::clockSource, TIMER_B_initContinuousModeParam::clockSourceDivider, TIMER_B_initContinuousModeParam::startTimer, TIMER_B_initContinuousMode(), TIMER_B_initContinuousModeParam::timerClear, and TIMER_B_initContinuousModeParam::timerInterruptEnable_TBIE.
void TIMER_B_initUpMode (uint16_t baseAddress, TIMER_B_initUpModeParam * param)
Configures TIMER_B in up mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_B_startCounter API.
Parameters
baseAddress is the base address of the TIMER_B module.
param is the pointer to struct for up mode initialization.
Modified bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_B_initUpModeParam::clockSource, TIMER_B_initUpModeParam::clockSourceDivider, CNTL_3, HWREG16, OFS_TBxCCR0, OFS_TBxCCTL0, OFS_TBxCTL, OFS_TBxEX0, TIMER_B_initUpModeParam::startTimer, TBIDEX_7, TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_B_CLOCKSOURCE_ACLK, TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_SMCLK, TIMER_B_DO_CLEAR, TIMER_B_SKIP_CLEAR, TIMER_B_TBIE_INTERRUPT_ENABLE, TIMER_B_UP_MODE, TIMER_B_UPDOWN_MODE, TIMER_B_initUpModeParam::timerClear, TIMER_B_initUpModeParam::timerInterruptEnable_TBIE, and TIMER_B_initUpModeParam::timerPeriod.
Referenced by TIMER_B_configureUpMode(), and TIMER_B_startUpMode().
void TIMER_B_configureUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_B in up mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_B_startCounter API.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified TIMER_B period. This is the value that gets written into the CCR0. Limited to 16 bits[uint16_t]
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable TIMER_B CCR0 capture compare interrupt. Valid values are:
TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_B_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_B_initUpModeParam::clockSource, TIMER_B_initUpModeParam::clockSourceDivider, TIMER_B_initUpModeParam::startTimer, TIMER_B_initUpMode(), TIMER_B_initUpModeParam::timerClear, TIMER_B_initUpModeParam::timerInterruptEnable_TBIE, and TIMER_B_initUpModeParam::timerPeriod.
void TIMER_B_initUpDownMode (uint16_t baseAddress, TIMER_B_initUpDownModeParam * param)
Configures TIMER_B in up down mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_B_startCounter API.
Parameters
baseAddress is the base address of the TIMER_B module.
param is the pointer to struct for up-down mode initialization.
Modified bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_B_initUpDownModeParam::clockSource, TIMER_B_initUpDownModeParam::clockSourceDivider, CNTL_3, HWREG16, OFS_TBxCCR0, OFS_TBxCCTL0, OFS_TBxCTL, OFS_TBxEX0, TIMER_B_initUpDownModeParam::startTimer, TBIDEX_7, TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_B_CLOCKSOURCE_ACLK, TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_SMCLK, TIMER_B_DO_CLEAR, TIMER_B_SKIP_CLEAR, TIMER_B_STOP_MODE, TIMER_B_TBIE_INTERRUPT_ENABLE, TIMER_B_UPDOWN_MODE, TIMER_B_initUpDownModeParam::timerClear, TIMER_B_initUpDownModeParam::timerInterruptEnable_TBIE, and TIMER_B_initUpDownModeParam::timerPeriod.
Referenced by TIMER_B_configureUpDownMode(), and TIMER_B_startUpDownMode().
void TIMER_B_configureUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_B in up down mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_B_startCounter API.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified TIMER_B period
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable TIMER_B CCR0 capture compare interrupt. Valid values are:
TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_B_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_B_initUpDownModeParam::clockSource, TIMER_B_initUpDownModeParam::clockSourceDivider, TIMER_B_initUpDownModeParam::startTimer, TIMER_B_initUpDownMode(), TIMER_B_initUpDownModeParam::timerClear, TIMER_B_initUpDownModeParam::timerInterruptEnable_TBIE, and TIMER_B_initUpDownModeParam::timerPeriod.
void TIMER_B_startContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TBIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_B_configureContinuousMode and TIMER_B_startCounter API. Starts TIMER_B in continuous mode.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register.
Returns
None
References TIMER_B_initContinuousModeParam::clockSource, TIMER_B_initContinuousModeParam::clockSourceDivider, TIMER_B_initContinuousModeParam::startTimer, TIMER_B_initContinuousMode(), TIMER_B_initContinuousModeParam::timerClear, and TIMER_B_initContinuousModeParam::timerInterruptEnable_TBIE.
Referenced by TIMER_B_startContinousMode().
void TIMER_B_startContinousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TBIE, uint16_t timerClear)
DEPRECATED - Spelling Error Fixed. Starts TIMER_B in continuous mode.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register.
Returns
None
References TIMER_B_startContinuousMode().
void TIMER_B_startUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_B_configureUpMode and TIMER_B_startCounter API. Starts TIMER_B in up mode.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified TIMER_B period. This is the value that gets written into the CCR0. Limited to 16 bits[uint16_t]
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable TIMER_B CCR0 capture compare interrupt. Valid values are:
TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_B_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_B_initUpModeParam::clockSource, TIMER_B_initUpModeParam::clockSourceDivider, TIMER_B_initUpModeParam::startTimer, TIMER_B_initUpMode(), TIMER_B_initUpModeParam::timerClear, TIMER_B_initUpModeParam::timerInterruptEnable_TBIE, and TIMER_B_initUpModeParam::timerPeriod.
void TIMER_B_startUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TBIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_B_configureUpDownMode and TIMER_B_startCounter API. Starts TIMER_B in up down mode.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified TIMER_B period
timerInterruptEnable_TBIE is to enable or disable TIMER_B interrupt Valid values are:
TIMER_B_TBIE_INTERRUPT_ENABLE
TIMER_B_TBIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable TIMER_B CCR0 capture compare interrupt. Valid values are:
TIMER_B_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_B_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_B clock divider, count direction, count need to be reset. Valid values are:
TIMER_B_DO_CLEAR
TIMER_B_SKIP_CLEAR [Default]
Modified bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_B_initUpDownModeParam::clockSource, TIMER_B_initUpDownModeParam::clockSourceDivider, TIMER_B_initUpDownModeParam::startTimer, TIMER_B_initUpDownMode(), TIMER_B_initUpDownModeParam::timerClear, TIMER_B_initUpDownModeParam::timerInterruptEnable_TBIE, and TIMER_B_initUpDownModeParam::timerPeriod.
void TIMER_B_initCaptureMode (uint16_t baseAddress, TIMER_B_initCaptureModeParam * param)
Initializes Capture Mode.
Parameters
baseAddress is the base address of the TIMER_B module.
param is the pointer to struct for capture mode initialization.
Modified bits of TBxCCTLn register.
Returns
None
References CAP, TIMER_B_initCaptureModeParam::captureInputSelect, TIMER_B_initCaptureModeParam::captureInterruptEnable, TIMER_B_initCaptureModeParam::captureMode, TIMER_B_initCaptureModeParam::captureOutputMode, TIMER_B_initCaptureModeParam::captureRegister, CM_3, HWREG16, TIMER_B_initCaptureModeParam::synchronizeCaptureSource, TIMER_B_CAPTURE_ASYNCHRONOUS, TIMER_B_CAPTURE_INPUTSELECT_CCIxA, TIMER_B_CAPTURE_INPUTSELECT_CCIxB, TIMER_B_CAPTURE_INPUTSELECT_GND, TIMER_B_CAPTURE_INPUTSELECT_Vcc, TIMER_B_CAPTURE_SYNCHRONOUS, TIMER_B_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, TIMER_B_CAPTURECOMPARE_REGISTER_6, TIMER_B_CAPTUREMODE_FALLING_EDGE, TIMER_B_CAPTUREMODE_NO_CAPTURE, TIMER_B_CAPTUREMODE_RISING_AND_FALLING_EDGE, TIMER_B_CAPTUREMODE_RISING_EDGE, TIMER_B_DO_CLEAR, TIMER_B_OUTPUTMODE_OUTBITVALUE, TIMER_B_OUTPUTMODE_RESET, TIMER_B_OUTPUTMODE_RESET_SET, TIMER_B_OUTPUTMODE_SET, TIMER_B_OUTPUTMODE_SET_RESET, TIMER_B_OUTPUTMODE_TOGGLE, TIMER_B_OUTPUTMODE_TOGGLE_RESET, TIMER_B_OUTPUTMODE_TOGGLE_SET, and TIMER_B_TBIE_INTERRUPT_ENABLE.
Referenced by TIMER_B_initCapture().
void TIMER_B_initCapture (uint16_t baseAddress, uint16_t captureRegister, uint16_t captureMode, uint16_t captureInputSelect, uint16_t synchronizeCaptureSource, uint16_t captureInterruptEnable, uint16_t captureOutputMode)
DEPRECATED - Initializes Capture Mode.
Parameters
baseAddress is the base address of the TIMER_B module.
captureRegister selects the capture register being used. Refer to datasheet to ensure the device has the capture register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
captureMode is the capture mode selected. Valid values are:
TIMER_B_CAPTUREMODE_NO_CAPTURE [Default]
TIMER_B_CAPTUREMODE_RISING_EDGE
TIMER_B_CAPTUREMODE_FALLING_EDGE
TIMER_B_CAPTUREMODE_RISING_AND_FALLING_EDGE
captureInputSelect decides the Input Select Valid values are:
TIMER_B_CAPTURE_INPUTSELECT_CCIxA [Default]
TIMER_B_CAPTURE_INPUTSELECT_CCIxB
TIMER_B_CAPTURE_INPUTSELECT_GND
TIMER_B_CAPTURE_INPUTSELECT_Vcc
synchronizeCaptureSource decides if capture source should be synchronized with TIMER_B clock Valid values are:
TIMER_B_CAPTURE_ASYNCHRONOUS [Default]
TIMER_B_CAPTURE_SYNCHRONOUS
captureInterruptEnable is to enable or disable TIMER_B capture compare interrupt. Valid values are:
TIMER_B_CAPTURECOMPARE_INTERRUPT_DISABLE [Default]
TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE
captureOutputMode specifies the output mode. Valid values are:
TIMER_B_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_B_OUTPUTMODE_SET
TIMER_B_OUTPUTMODE_TOGGLE_RESET
TIMER_B_OUTPUTMODE_SET_RESET
TIMER_B_OUTPUTMODE_TOGGLE
TIMER_B_OUTPUTMODE_RESET
TIMER_B_OUTPUTMODE_TOGGLE_SET
TIMER_B_OUTPUTMODE_RESET_SET
Modified bits of TBxCCTLn register.
Returns
None
References TIMER_B_initCaptureModeParam::captureInputSelect, TIMER_B_initCaptureModeParam::captureInterruptEnable, TIMER_B_initCaptureModeParam::captureMode, TIMER_B_initCaptureModeParam::captureOutputMode, TIMER_B_initCaptureModeParam::captureRegister, TIMER_B_initCaptureModeParam::synchronizeCaptureSource, and TIMER_B_initCaptureMode().
void TIMER_B_initCompareMode (uint16_t baseAddress, TIMER_B_initCompareModeParam * param)
Initializes Compare Mode.
Parameters
baseAddress is the base address of the TIMER_B module.
param is the pointer to struct for compare mode initialization.
Modified bits of TBxCCTLn register and bits of TBxCCRn register.
Returns
None
References CAP, TIMER_B_initCompareModeParam::compareInterruptEnable, TIMER_B_initCompareModeParam::compareOutputMode, TIMER_B_initCompareModeParam::compareRegister, TIMER_B_initCompareModeParam::compareValue, HWREG16, OFS_TBxR, TIMER_B_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, TIMER_B_CAPTURECOMPARE_REGISTER_6, TIMER_B_OUTPUTMODE_OUTBITVALUE, TIMER_B_OUTPUTMODE_RESET, TIMER_B_OUTPUTMODE_RESET_SET, TIMER_B_OUTPUTMODE_SET, TIMER_B_OUTPUTMODE_SET_RESET, TIMER_B_OUTPUTMODE_TOGGLE, TIMER_B_OUTPUTMODE_TOGGLE_RESET, and TIMER_B_OUTPUTMODE_TOGGLE_SET.
Referenced by TIMER_B_initCompare().
void TIMER_B_initCompare (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareInterruptEnable, uint16_t compareOutputMode, uint16_t compareValue)
DEPRECATED - Initializes Compare Mode.
Parameters
baseAddress is the base address of the TIMER_B module.
compareRegister selects the compare register being used. Refer to datasheet to ensure the device has the compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
compareInterruptEnable is to enable or disable TIMER_B capture compare interrupt. Valid values are:
TIMER_B_CAPTURECOMPARE_INTERRUPT_DISABLE [Default]
TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE
compareOutputMode specifies the output mode. Valid values are:
TIMER_B_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_B_OUTPUTMODE_SET
TIMER_B_OUTPUTMODE_TOGGLE_RESET
TIMER_B_OUTPUTMODE_SET_RESET
TIMER_B_OUTPUTMODE_TOGGLE
TIMER_B_OUTPUTMODE_RESET
TIMER_B_OUTPUTMODE_TOGGLE_SET
TIMER_B_OUTPUTMODE_RESET_SET
compareValue is the count to be compared with in compare mode
Modified bits of TBxCCTLn register and bits of TBxCCRn register.
Returns
None
References TIMER_B_initCompareModeParam::compareInterruptEnable, TIMER_B_initCompareModeParam::compareOutputMode, TIMER_B_initCompareModeParam::compareRegister, TIMER_B_initCompareModeParam::compareValue, and TIMER_B_initCompareMode().
void TIMER_B_enableInterrupt (uint16_t baseAddress)
Enable TIMER_B interrupt.
Enables TIMER_B interrupt. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the TIMER_B module.
Modified bits of TBxCTL register.
Returns
None
References HWREG16, OFS_TBxCTL, and TBIE.
void TIMER_B_disableInterrupt (uint16_t baseAddress)
Disable TIMER_B interrupt.
Parameters
baseAddress is the base address of the TIMER_B module.
Modified bits of TBxCTL register.
Returns
None
References HWREG16, OFS_TBxCTL, and TBIE.
uint32_t TIMER_B_getInterruptStatus (uint16_t baseAddress)
Get TIMER_B interrupt status.
Parameters
baseAddress is the base address of the TIMER_B module.
Returns
One of the following:
TIMER_B_INTERRUPT_NOT_PENDING
TIMER_B_INTERRUPT_PENDING
indicating the status of the TIMER_B interrupt
References HWREG16, OFS_TBxCTL, and TBIFG.
void TIMER_B_enableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Enable capture compare interrupt.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
Modified bits of TBxCCTLn register.
Returns
None
References CCIE, HWREG16, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, and TIMER_B_CAPTURECOMPARE_REGISTER_6.
void TIMER_B_disableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Disable capture compare interrupt.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
Modified bits of TBxCCTLn register.
Returns
None
References CCIE, HWREG16, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, and TIMER_B_CAPTURECOMPARE_REGISTER_6.
uint32_t TIMER_B_getCaptureCompareInterruptStatus (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t mask)
Return capture compare interrupt status.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
mask is the mask for the interrupt status Mask value is the logical OR of any of the following:
TIMER_B_CAPTURE_OVERFLOW
TIMER_B_CAPTURECOMPARE_INTERRUPT_FLAG
Returns
Logical OR of any of the following:
TIMER_B_CAPTURE_OVERFLOW
TIMER_B_CAPTURECOMPARE_INTERRUPT_FLAG
indicating the status of the masked interrupts
References HWREG16.
void TIMER_B_clear (uint16_t baseAddress)
Reset/Clear the TIMER_B clock divider, count direction, count.
Parameters
baseAddress is the base address of the TIMER_B module.
Modified bits of TBxCTL register.
Returns
None
References HWREG16, OFS_TBxCTL, and TBCLR.
uint8_t TIMER_B_getSynchronizedCaptureCompareInput (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t synchronized)
Get synchronized capturecompare input.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
synchronized selects the type of capture compare input Valid values are:
TIMER_B_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT
TIMER_B_READ_CAPTURE_COMPARE_INPUT
Returns
One of the following:
TIMER_B_CAPTURECOMPARE_INPUT_HIGH
TIMER_B_CAPTURECOMPARE_INPUT_LOW
References HWREG16, TIMER_B_CAPTURECOMPARE_INPUT_HIGH, TIMER_B_CAPTURECOMPARE_INPUT_LOW, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, TIMER_B_CAPTURECOMPARE_REGISTER_6, TIMER_B_READ_CAPTURE_COMPARE_INPUT, and TIMER_B_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT.
uint8_t TIMER_B_getOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister)
Get output bit for output mode.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
Returns
One of the following:
TIMER_B_OUTPUTMODE_OUTBITVALUE_HIGH
TIMER_B_OUTPUTMODE_OUTBITVALUE_LOW
References HWREG16, OUT, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, TIMER_B_CAPTURECOMPARE_REGISTER_6, TIMER_B_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_B_OUTPUTMODE_OUTBITVALUE_LOW.
uint16_t TIMER_B_getCaptureCompareCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare count.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
Returns
Current count as uint16_t
References HWREG16, OFS_TBxR, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, and TIMER_B_CAPTURECOMPARE_REGISTER_6.
void TIMER_B_setOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister, uint8_t outputModeOutBitValue)
Set output bit for output mode.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
outputModeOutBitValue the value to be set for out bit Valid values are:
TIMER_B_OUTPUTMODE_OUTBITVALUE_HIGH
TIMER_B_OUTPUTMODE_OUTBITVALUE_LOW
Modified bits of TBxCCTLn register.
Returns
None
References HWREG16, OUT, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, TIMER_B_CAPTURECOMPARE_REGISTER_6, TIMER_B_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_B_OUTPUTMODE_OUTBITVALUE_LOW.
void TIMER_B_outputPWM (uint16_t baseAddress, TIMER_B_outputPWMParam * param)
Generate a PWM with TIMER_B running in up mode.
Parameters
baseAddress is the base address of the TIMER_B module.
param is the pointer to struct for PWM configuration.
Modified bits of TBxCCTLn register, bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_outputPWMParam::clockSource, TIMER_B_outputPWMParam::clockSourceDivider, TIMER_B_outputPWMParam::compareOutputMode, TIMER_B_outputPWMParam::compareRegister, TIMER_B_outputPWMParam::dutyCycle, HWREG16, OFS_TBxCCR0, OFS_TBxCCTL0, OFS_TBxCTL, OFS_TBxEX0, OFS_TBxR, TBIDEX_7, TIMER_B_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, TIMER_B_CAPTURECOMPARE_REGISTER_6, TIMER_B_CLOCKSOURCE_ACLK, TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_B_CLOCKSOURCE_SMCLK, TIMER_B_DO_CLEAR, TIMER_B_OUTPUTMODE_OUTBITVALUE, TIMER_B_OUTPUTMODE_RESET, TIMER_B_OUTPUTMODE_RESET_SET, TIMER_B_OUTPUTMODE_SET, TIMER_B_OUTPUTMODE_SET_RESET, TIMER_B_OUTPUTMODE_TOGGLE, TIMER_B_OUTPUTMODE_TOGGLE_RESET, TIMER_B_OUTPUTMODE_TOGGLE_SET, TIMER_B_TBIE_INTERRUPT_ENABLE, TIMER_B_UP_MODE, TIMER_B_UPDOWN_MODE, and TIMER_B_outputPWMParam::timerPeriod.
Referenced by TIMER_B_generatePWM().
void TIMER_B_generatePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t compareRegister, uint16_t compareOutputMode, uint16_t dutyCycle)
DEPRECATED - Generate a PWM with TIMER_B running in up mode.
Parameters
baseAddress is the base address of the TIMER_B module.
clockSource selects the clock source Valid values are:
TIMER_B_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_B_CLOCKSOURCE_ACLK
TIMER_B_CLOCKSOURCE_SMCLK
TIMER_B_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the divider for Clock source. Valid values are:
TIMER_B_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_B_CLOCKSOURCE_DIVIDER_2
TIMER_B_CLOCKSOURCE_DIVIDER_3
TIMER_B_CLOCKSOURCE_DIVIDER_4
TIMER_B_CLOCKSOURCE_DIVIDER_5
TIMER_B_CLOCKSOURCE_DIVIDER_6
TIMER_B_CLOCKSOURCE_DIVIDER_7
TIMER_B_CLOCKSOURCE_DIVIDER_8
TIMER_B_CLOCKSOURCE_DIVIDER_10
TIMER_B_CLOCKSOURCE_DIVIDER_12
TIMER_B_CLOCKSOURCE_DIVIDER_14
TIMER_B_CLOCKSOURCE_DIVIDER_16
TIMER_B_CLOCKSOURCE_DIVIDER_20
TIMER_B_CLOCKSOURCE_DIVIDER_24
TIMER_B_CLOCKSOURCE_DIVIDER_28
TIMER_B_CLOCKSOURCE_DIVIDER_32
TIMER_B_CLOCKSOURCE_DIVIDER_40
TIMER_B_CLOCKSOURCE_DIVIDER_48
TIMER_B_CLOCKSOURCE_DIVIDER_56
TIMER_B_CLOCKSOURCE_DIVIDER_64
timerPeriod selects the desired TIMER_B period
compareRegister selects the compare register being used. Refer to datasheet to ensure the device has the compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
compareOutputMode specifies the output mode. Valid values are:
TIMER_B_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_B_OUTPUTMODE_SET
TIMER_B_OUTPUTMODE_TOGGLE_RESET
TIMER_B_OUTPUTMODE_SET_RESET
TIMER_B_OUTPUTMODE_TOGGLE
TIMER_B_OUTPUTMODE_RESET
TIMER_B_OUTPUTMODE_TOGGLE_SET
TIMER_B_OUTPUTMODE_RESET_SET
dutyCycle specifies the dutycycle for the generated waveform
Modified bits of TBxCCTLn register, bits of TBxCTL register, bits of TBxCCTL0 register and bits of TBxCCR0 register.
Returns
None
References TIMER_B_outputPWMParam::clockSource, TIMER_B_outputPWMParam::clockSourceDivider, TIMER_B_outputPWMParam::compareOutputMode, TIMER_B_outputPWMParam::compareRegister, TIMER_B_outputPWMParam::dutyCycle, TIMER_B_outputPWM(), and TIMER_B_outputPWMParam::timerPeriod.
void TIMER_B_stop (uint16_t baseAddress)
Stops the TIMER_B.
Parameters
baseAddress is the base address of the TIMER_B module.
Modified bits of TBxCTL register.
Returns
None
References HWREG16, MC_0, MC_3, and OFS_TBxCTL.
void TIMER_B_setCompareValue (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareValue)
Sets the value of the capture-compare register.
Parameters
baseAddress is the base address of the TIMER_B module.
compareRegister selects the compare register being used. Refer to datasheet to ensure the device has the compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
compareValue is the count to be compared with in compare mode
Modified bits of TBxCCRn register.
Returns
None
References HWREG16, OFS_TBxR, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, and TIMER_B_CAPTURECOMPARE_REGISTER_6.
void TIMER_B_clearTimerInterruptFlag (uint16_t baseAddress)
Clears the TIMER_B TBIFG interrupt flag.
Parameters
baseAddress is the base address of the TIMER_B module.
Modified bits are TBIFG of TBxCTL register.
Returns
None
References HWREG16, OFS_TBxCTL, and TBIFG.
void TIMER_B_clearCaptureCompareInterruptFlag (uint16_t baseAddress, uint16_t captureCompareRegister)
Clears the capture-compare interrupt flag.
Parameters
baseAddress is the base address of the TIMER_B module.
captureCompareRegister selects the capture compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
Modified bits are CCIFG of TBxCCTLn register.
Returns
None
References CCIFG, HWREG16, TIMER_B_CAPTURECOMPARE_REGISTER_0, TIMER_B_CAPTURECOMPARE_REGISTER_1, TIMER_B_CAPTURECOMPARE_REGISTER_2, TIMER_B_CAPTURECOMPARE_REGISTER_3, TIMER_B_CAPTURECOMPARE_REGISTER_4, TIMER_B_CAPTURECOMPARE_REGISTER_5, and TIMER_B_CAPTURECOMPARE_REGISTER_6.
void TIMER_B_selectCounterLength (uint16_t baseAddress, uint16_t counterLength)
Selects TIMER_B counter length.
Parameters
baseAddress is the base address of the TIMER_B module.
counterLength selects the value of counter length. Valid values are:
TIMER_B_COUNTER_16BIT [Default]
TIMER_B_COUNTER_12BIT
TIMER_B_COUNTER_10BIT
TIMER_B_COUNTER_8BIT
Modified bits are CNTL of TBxCTL register.
Returns
None
References CNTL_3, HWREG16, OFS_TBxCTL, TIMER_B_COUNTER_10BIT, TIMER_B_COUNTER_12BIT, TIMER_B_COUNTER_16BIT, and TIMER_B_COUNTER_8BIT.
void TIMER_B_selectLatchingGroup (uint16_t baseAddress, uint16_t groupLatch)
Selects TIMER_B Latching Group.
Parameters
baseAddress is the base address of the TIMER_B module.
groupLatch selects the latching group. Valid values are:
TIMER_B_GROUP_NONE [Default]
TIMER_B_GROUP_CL12_CL23_CL56
TIMER_B_GROUP_CL123_CL456
TIMER_B_GROUP_ALL
Modified bits are TBCLGRP of TBxCTL register.
Returns
None
References HWREG16, OFS_TBxCTL, TBCLGRP_3, TIMER_B_GROUP_ALL, TIMER_B_GROUP_CL123_CL456, TIMER_B_GROUP_CL12_CL23_CL56, and TIMER_B_GROUP_NONE.
void TIMER_B_initCompareLatchLoadEvent (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareLatchLoadEvent)
Selects Compare Latch Load Event.
Parameters
baseAddress is the base address of the TIMER_B module.
compareRegister selects the compare register being used. Refer to datasheet to ensure the device has the compare register being used. Valid values are:
TIMER_B_CAPTURECOMPARE_REGISTER_0
TIMER_B_CAPTURECOMPARE_REGISTER_1
TIMER_B_CAPTURECOMPARE_REGISTER_2
TIMER_B_CAPTURECOMPARE_REGISTER_3
TIMER_B_CAPTURECOMPARE_REGISTER_4
TIMER_B_CAPTURECOMPARE_REGISTER_5
TIMER_B_CAPTURECOMPARE_REGISTER_6
compareLatchLoadEvent selects the latch load event Valid values are:
TIMER_B_LATCH_ON_WRITE_TO_TBxCCRn_COMPARE_REGISTER [Default]
TIMER_B_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UP_OR_CONT_MODE
TIMER_B_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UPDOWN_MODE
TIMER_B_LATCH_WHEN_COUNTER_COUNTS_TO_CURRENT_COMPARE_LATCH_VALUE
Modified bits are CLLD of TBxCCTLn register.
Returns
None
References CLLD_3, HWREG16, TIMER_B_LATCH_ON_WRITE_TO_TBxCCRn_COMPARE_REGISTER, TIMER_B_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UP_OR_CONT_MODE, TIMER_B_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UPDOWN_MODE, and TIMER_B_LATCH_WHEN_COUNTER_COUNTS_TO_CURRENT_COMPARE_LATCH_VALUE.
uint16_t TIMER_B_getCounterValue (uint16_t baseAddress)
Reads the current timer count value.
Reads the current count value of the timer. There is a majority vote system in place to confirm an accurate value is returned. The TIMER_B_THRESHOLD #define in the associated header file can be modified so that the votes must be closer together for a consensus to occur.
Parameters
baseAddress is the base address of the Timer module.
Returns
Majority vote of timer count value
References HWREG16, OFS_TBxR, and TIMER_B_THRESHOLD.
Copyright 2014, Texas Instruments Incorporated