Adc12_a_api
Adc12_a_api
Functions
bool ADC12_A_init (uint16_t baseAddress, uint16_t sampleHoldSignalSourceSelect, uint8_t clockSourceSelect, uint16_t clockSourceDivider)
Initializes the ADC12_A Module.
void ADC12_A_enable (uint16_t baseAddress)
Enables the ADC12_A block.
void ADC12_A_disable (uint16_t baseAddress)
Disables the ADC12_A block.
void ADC12_A_setupSamplingTimer (uint16_t baseAddress, uint16_t clockCycleHoldCountLowMem, uint16_t clockCycleHoldCountHighMem, uint16_t multipleSamplesEnabled)
Sets up and enables the Sampling Timer Pulse Mode.
void ADC12_A_disableSamplingTimer (uint16_t baseAddress)
Disables Sampling Timer Pulse Mode.
void ADC12_A_memoryConfigure (uint16_t baseAddress, uint8_t memoryBufferControlIndex, uint8_t inputSourceSelect, uint8_t positiveRefVoltageSourceSelect, uint8_t negativeRefVoltageSourceSelect, uint8_t endOfSequence)
DEPRECATED - Configures the controls of the selected memory buffer.
void ADC12_A_configureMemory (uint16_t baseAddress, ADC12_A_configureMemoryParam *param)
Configures the controls of the selected memory buffer.
void ADC12_A_enableInterrupt (uint16_t baseAddress, uint32_t interruptMask)
Enables selected ADC12_A interrupt sources.
void ADC12_A_disableInterrupt (uint16_t baseAddress, uint32_t interruptMask)
Disables selected ADC12_A interrupt sources.
void ADC12_A_clearInterrupt (uint16_t baseAddress, uint16_t memoryInterruptFlagMask)
Clears ADC12_A selected interrupt flags.
uint8_t ADC12_A_getInterruptStatus (uint16_t baseAddress, uint16_t memoryInterruptFlagMask)
Returns the status of the selected memory interrupt flags.
void ADC12_A_startConversion (uint16_t baseAddress, uint16_t startingMemoryBufferIndex, uint8_t conversionSequenceModeSelect)
Enables/Starts an Analog-to-Digital Conversion.
void ADC12_A_disableConversions (uint16_t baseAddress, bool preempt)
Disables the ADC from converting any more signals.
uint16_t ADC12_A_getResults (uint16_t baseAddress, uint8_t memoryBufferIndex)
A Signed Integer of the contents of the specified memory buffer.
void ADC12_A_setResolution (uint16_t baseAddress, uint8_t resolutionSelect)
Use to change the resolution of the converted data.
void ADC12_A_setSampleHoldSignalInversion (uint16_t baseAddress, uint16_t invertedSignal)
Use to invert or un-invert the sample/hold signal.
void ADC12_A_setDataReadBackFormat (uint16_t baseAddress, uint8_t readBackFormat)
Use to set the read-back format of the converted data.
void ADC12_A_enableReferenceBurst (uint16_t baseAddress)
Enables the reference buffer's burst ability.
void ADC12_A_disableReferenceBurst (uint16_t baseAddress)
Disables the reference buffer's burst ability.
void ADC12_A_setReferenceBufferSamplingRate (uint16_t baseAddress, uint8_t samplingRateSelect)
Use to set the reference buffer's sampling rate.
uint32_t ADC12_A_getMemoryAddressForDMA (uint16_t baseAddress, uint8_t memoryIndex)
Returns the address of the specified memory buffer for the DMA module.
uint16_t ADC12_A_isBusy (uint16_t baseAddress)
Returns the busy status of the ADC12_A core.
Detailed Description
Function Documentation
bool ADC12_A_init (uint16_t baseAddress, uint16_t sampleHoldSignalSourceSelect, uint8_t clockSourceSelect, uint16_t clockSourceDivider)
Initializes the ADC12_A Module.
This function initializes the ADC module to allow for analog-to-digital conversions. Specifically this function sets up the sample-and-hold signal and clock sources for the ADC core to use for conversions. Upon successful completion of the initialization all of the ADC control registers will be reset, excluding the memory controls and reference module bits, the given parameters will be set, and the ADC core will be turned on (Note, that the ADC core only draws power during conversions and remains off when not converting).Note that sample/hold signal sources are device dependent. Note that if re-initializing the ADC after starting a conversion with the startConversion() function, the disableConversion() must be called BEFORE this function can be called.
Parameters
baseAddress is the base address of the ADC12_A module.
sampleHoldSignalSourceSelect is the signal that will trigger a sample-and-hold for an input signal to be converted. This parameter is device specific and sources should be found in the device's datasheet. Valid values are:
ADC12_A_SAMPLEHOLDSOURCE_SC [Default]
ADC12_A_SAMPLEHOLDSOURCE_1
ADC12_A_SAMPLEHOLDSOURCE_2
ADC12_A_SAMPLEHOLDSOURCE_3 - This parameter is device specific and sources should be found in the device's datasheet.
Modified bits are ADC12SHSx of ADC12CTL1 register.
clockSourceSelect selects the clock that will be used by the ADC12_A core, and the sampling timer if a sampling pulse mode is enabled. Valid values are:
ADC12_A_CLOCKSOURCE_ADC12OSC [Default] - MODOSC 5 MHz oscillator from the UCS
ADC12_A_CLOCKSOURCE_ACLK - The Auxiliary Clock
ADC12_A_CLOCKSOURCE_MCLK - The Master Clock
ADC12_A_CLOCKSOURCE_SMCLK - The Sub-Master Clock
Modified bits are ADC12SSELx of ADC12CTL1 register.
clockSourceDivider selects the amount that the clock will be divided. Valid values are:
ADC12_A_CLOCKDIVIDER_1 [Default]
ADC12_A_CLOCKDIVIDER_2
ADC12_A_CLOCKDIVIDER_3
ADC12_A_CLOCKDIVIDER_4
ADC12_A_CLOCKDIVIDER_5
ADC12_A_CLOCKDIVIDER_6
ADC12_A_CLOCKDIVIDER_7
ADC12_A_CLOCKDIVIDER_8
ADC12_A_CLOCKDIVIDER_12
ADC12_A_CLOCKDIVIDER_16
ADC12_A_CLOCKDIVIDER_20
ADC12_A_CLOCKDIVIDER_24
ADC12_A_CLOCKDIVIDER_28
ADC12_A_CLOCKDIVIDER_32
Modified bits are ADC12PDIV of ADC12CTL2 register; bits ADC12DIVx of ADC12CTL1 register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the initialization process.
References ADC12_A_CLOCKDIVIDER_32, ADC12_A_CLOCKSOURCE_SMCLK, ADC12_A_SAMPLEHOLDSOURCE_3, ADC12DIV_7, ADC12ENC, ADC12ON, ADC12OVIE, ADC12PDIV, ADC12RES_2, ADC12SC, ADC12TOVIE, HWREG16, HWREG8, OFS_ADC12CTL0, OFS_ADC12CTL0_L, OFS_ADC12CTL1, OFS_ADC12CTL2, OFS_ADC12IE, OFS_ADC12IFG, and STATUS_SUCCESS.
void ADC12_A_enable (uint16_t baseAddress)
Enables the ADC12_A block.
This will enable operation of the ADC12_A block.
Parameters
baseAddress is the base address of the ADC12_A module.
Modified bits are ADC12ON of ADC12CTL0 register.
Returns
None
References ADC12ON, HWREG8, and OFS_ADC12CTL0_L.
void ADC12_A_disable (uint16_t baseAddress)
Disables the ADC12_A block.
This will disable operation of the ADC12_A block.
Parameters
baseAddress is the base address of the ADC12_A module.
Modified bits are ADC12ON of ADC12CTL0 register.
Returns
None
References ADC12ON, HWREG8, and OFS_ADC12CTL0_L.
void ADC12_A_setupSamplingTimer (uint16_t baseAddress, uint16_t clockCycleHoldCountLowMem, uint16_t clockCycleHoldCountHighMem, uint16_t multipleSamplesEnabled)
Sets up and enables the Sampling Timer Pulse Mode.
This function sets up the sampling timer pulse mode which allows the sample/hold signal to trigger a sampling timer to sample-and-hold an input signal for a specified number of clock cycles without having to hold the sample/hold signal for the entire period of sampling. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12_A module.
clockCycleHoldCountLowMem sets the amount of clock cycles to sample- and-hold for the higher memory buffers 0-7. Valid values are:
ADC12_A_CYCLEHOLD_4_CYCLES [Default]
ADC12_A_CYCLEHOLD_8_CYCLES
ADC12_A_CYCLEHOLD_16_CYCLES
ADC12_A_CYCLEHOLD_32_CYCLES
ADC12_A_CYCLEHOLD_64_CYCLES
ADC12_A_CYCLEHOLD_96_CYCLES
ADC12_A_CYCLEHOLD_128_CYCLES
ADC12_A_CYCLEHOLD_192_CYCLES
ADC12_A_CYCLEHOLD_256_CYCLES
ADC12_A_CYCLEHOLD_384_CYCLES
ADC12_A_CYCLEHOLD_512_CYCLES
ADC12_A_CYCLEHOLD_768_CYCLES
ADC12_A_CYCLEHOLD_1024_CYCLES
Modified bits are ADC12SHT0x of ADC12CTL0 register.
clockCycleHoldCountHighMem sets the amount of clock cycles to sample-and-hold for the higher memory buffers 8-15. Valid values are:
ADC12_A_CYCLEHOLD_4_CYCLES [Default]
ADC12_A_CYCLEHOLD_8_CYCLES
ADC12_A_CYCLEHOLD_16_CYCLES
ADC12_A_CYCLEHOLD_32_CYCLES
ADC12_A_CYCLEHOLD_64_CYCLES
ADC12_A_CYCLEHOLD_96_CYCLES
ADC12_A_CYCLEHOLD_128_CYCLES
ADC12_A_CYCLEHOLD_192_CYCLES
ADC12_A_CYCLEHOLD_256_CYCLES
ADC12_A_CYCLEHOLD_384_CYCLES
ADC12_A_CYCLEHOLD_512_CYCLES
ADC12_A_CYCLEHOLD_768_CYCLES
ADC12_A_CYCLEHOLD_1024_CYCLES
Modified bits are ADC12SHT1x of ADC12CTL0 register.
multipleSamplesEnabled allows multiple conversions to start without a trigger signal from the sample/hold signal Valid values are:
ADC12_A_MULTIPLESAMPLESDISABLE [Default] - a timer trigger will be needed to start every ADC conversion.
ADC12_A_MULTIPLESAMPLESENABLE - during a sequenced and/or repeated conversion mode, after the first conversion, no sample/hold signal is necessary to start subsequent sample/hold and convert processes.
Modified bits are ADC12MSC of ADC12CTL0 register.
Returns
None
References ADC12_A_CYCLEHOLD_1024_CYCLES, ADC12ENC, ADC12MSC, ADC12SHP, ADC12SHT0_15, ADC12SHT1_15, HWREG16, HWREG8, OFS_ADC12CTL0, OFS_ADC12CTL0_L, and OFS_ADC12CTL1.
void ADC12_A_disableSamplingTimer (uint16_t baseAddress)
Disables Sampling Timer Pulse Mode.
Disables the Sampling Timer Pulse Mode. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12_A module.
Modified bits are ADC12SHP of ADC12CTL0 register.
Returns
None
References ADC12ENC, ADC12SHP, HWREG16, HWREG8, OFS_ADC12CTL0_L, and OFS_ADC12CTL1.
void ADC12_A_memoryConfigure (uint16_t baseAddress, uint8_t memoryBufferControlIndex, uint8_t inputSourceSelect, uint8_t positiveRefVoltageSourceSelect, uint8_t negativeRefVoltageSourceSelect, uint8_t endOfSequence)
DEPRECATED - Configures the controls of the selected memory buffer.
Maps an input signal conversion into the selected memory buffer, as well as the positive and negative reference voltages for each conversion being stored into this memory buffer. If the internal reference is used for the positive reference voltage, the internal REF module must be used to control the voltage level. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12_A module.
memoryBufferControlIndex is the selected memory buffer to set the configuration for. Valid values are:
ADC12_A_MEMORY_0 [Default]
ADC12_A_MEMORY_1
ADC12_A_MEMORY_2
ADC12_A_MEMORY_3
ADC12_A_MEMORY_4
ADC12_A_MEMORY_5
ADC12_A_MEMORY_6
ADC12_A_MEMORY_7
ADC12_A_MEMORY_8
ADC12_A_MEMORY_9
ADC12_A_MEMORY_10
ADC12_A_MEMORY_11
ADC12_A_MEMORY_12
ADC12_A_MEMORY_13
ADC12_A_MEMORY_14
ADC12_A_MEMORY_15
inputSourceSelect is the input that will store the converted data into the specified memory buffer. Valid values are:
ADC12_A_INPUT_A0 [Default]
ADC12_A_INPUT_A1
ADC12_A_INPUT_A2
ADC12_A_INPUT_A3
ADC12_A_INPUT_A4
ADC12_A_INPUT_A5
ADC12_A_INPUT_A6
ADC12_A_INPUT_A7
ADC12_A_INPUT_A8
ADC12_A_INPUT_A9
ADC12_A_INPUT_TEMPSENSOR
ADC12_A_INPUT_BATTERYMONITOR
ADC12_A_INPUT_A12
ADC12_A_INPUT_A13
ADC12_A_INPUT_A14
ADC12_A_INPUT_A15
Modified bits are ADC12INCHx of ADC12MCTLx register.
positiveRefVoltageSourceSelect is the reference voltage source to set as the upper limit for the conversion stored in the specified memory. Valid values are:
ADC12_A_VREFPOS_AVCC [Default]
ADC12_A_VREFPOS_EXT
ADC12_A_VREFPOS_INT
Modified bits are ADC12SREF of ADC12MCTLx register.
negativeRefVoltageSourceSelect is the reference voltage source to set as the lower limit for the conversion stored in the specified memory. Valid values are:
ADC12_A_VREFNEG_AVSS [Default]
ADC12_A_VREFNEG_EXT
Modified bits are ADC12SREF of ADC12MCTLx register.
endOfSequence indicates that the specified memory buffer will be the end of the sequence if a sequenced conversion mode is selected Valid values are:
ADC12_A_NOTENDOFSEQUENCE [Default] - The specified memory buffer will NOT be the end of the sequence OR a sequenced conversion mode is not selected.
ADC12_A_ENDOFSEQUENCE - The specified memory buffer will be the end of the sequence.
Modified bits are ADC12EOS of ADC12MCTLx register.
Returns
None
References ADC12_A_configureMemory(), ADC12_A_configureMemoryParam::endOfSequence, ADC12_A_configureMemoryParam::inputSourceSelect, ADC12_A_configureMemoryParam::memoryBufferControlIndex, ADC12_A_configureMemoryParam::negativeRefVoltageSourceSelect, and ADC12_A_configureMemoryParam::positiveRefVoltageSourceSelect.
void ADC12_A_configureMemory (uint16_t baseAddress, ADC12_A_configureMemoryParam * param)
Configures the controls of the selected memory buffer.
Maps an input signal conversion into the selected memory buffer, as well as the positive and negative reference voltages for each conversion being stored into this memory buffer. If the internal reference is used for the positive reference voltage, the internal REF module must be used to control the voltage level. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12_A module.
param is the pointer to struct for memory configuration.
Returns
None
References ADC12_A_INPUT_A15, ADC12_A_MEMORY_15, ADC12_A_VREFNEG_EXT, ADC12_A_VREFPOS_INT, ADC12ENC, ADC12_A_configureMemoryParam::endOfSequence, HWREG8, ADC12_A_configureMemoryParam::inputSourceSelect, ADC12_A_configureMemoryParam::memoryBufferControlIndex, ADC12_A_configureMemoryParam::negativeRefVoltageSourceSelect, OFS_ADC12CTL0_L, OFS_ADC12MCTL0, and ADC12_A_configureMemoryParam::positiveRefVoltageSourceSelect.
Referenced by ADC12_A_memoryConfigure().
void ADC12_A_enableInterrupt (uint16_t baseAddress, uint32_t interruptMask)
Enables selected ADC12_A interrupt sources.
Enables the indicated ADC12_A interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt, disabled sources have no effect on the processor. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the ADC12_A module.
interruptMask Mask value is the logical OR of any of the following:
ADC12_A_IE0
ADC12_A_IE1
ADC12_A_IE2
ADC12_A_IE3
ADC12_A_IE4
ADC12_A_IE5
ADC12_A_IE6
ADC12_A_IE7
ADC12_A_IE8
ADC12_A_IE9
ADC12_A_IE10
ADC12_A_IE11
ADC12_A_IE12
ADC12_A_IE13
ADC12_A_IE14
ADC12_A_IE15
ADC12_A_OVERFLOW_IE
ADC12_A_CONVERSION_TIME_OVERFLOW_IE
Modified bits of ADC12IE register and bits of ADC12CTL0 register.
Returns
None
References ADC12_A_CONVERSION_TIME_OVERFLOW_IE, ADC12_A_OVERFLOW_IE, ADC12IE0, ADC12IE1, ADC12IE10, ADC12IE11, ADC12IE12, ADC12IE13, ADC12IE14, ADC12IE15, ADC12IE2, ADC12IE3, ADC12IE4, ADC12IE5, ADC12IE6, ADC12IE7, ADC12IE8, ADC12IE9, ADC12OVIE, ADC12OVIE0, ADC12TOVIE, ADC12TOVIE0, HWREG16, OFS_ADC12CTL0, and OFS_ADC12IE.
void ADC12_A_disableInterrupt (uint16_t baseAddress, uint32_t interruptMask)
Disables selected ADC12_A interrupt sources.
Disables the indicated ADC12_A interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt, disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the ADC12_A module.
interruptMask Mask value is the logical OR of any of the following:
ADC12_A_IE0
ADC12_A_IE1
ADC12_A_IE2
ADC12_A_IE3
ADC12_A_IE4
ADC12_A_IE5
ADC12_A_IE6
ADC12_A_IE7
ADC12_A_IE8
ADC12_A_IE9
ADC12_A_IE10
ADC12_A_IE11
ADC12_A_IE12
ADC12_A_IE13
ADC12_A_IE14
ADC12_A_IE15
ADC12_A_OVERFLOW_IE
ADC12_A_CONVERSION_TIME_OVERFLOW_IE
Modified bits of ADC12IE register and bits of ADC12CTL0 register.
Returns
None
References ADC12_A_CONVERSION_TIME_OVERFLOW_IE, ADC12_A_OVERFLOW_IE, ADC12IE0, ADC12IE1, ADC12IE10, ADC12IE11, ADC12IE12, ADC12IE13, ADC12IE14, ADC12IE15, ADC12IE2, ADC12IE3, ADC12IE4, ADC12IE5, ADC12IE6, ADC12IE7, ADC12IE8, ADC12IE9, ADC12OVIE, ADC12OVIE0, ADC12TOVIE, ADC12TOVIE0, HWREG16, OFS_ADC12CTL0, and OFS_ADC12IE.
void ADC12_A_clearInterrupt (uint16_t baseAddress, uint16_t memoryInterruptFlagMask)
Clears ADC12_A selected interrupt flags.
The selected ADC12_A interrupt flags are cleared, so that it no longer asserts. The memory buffer interrupt flags are only cleared when the memory buffer is accessed. Note that the overflow interrupts do not have an interrupt flag to clear; they must be accessed directly from the interrupt vector.
Parameters
baseAddress is the base address of the ADC12_A module.
memoryInterruptFlagMask is a bit mask of the interrupt flags to be cleared. Mask value is the logical OR of any of the following:
ADC12_A_IFG0
ADC12_A_IFG1
ADC12_A_IFG2
ADC12_A_IFG3
ADC12_A_IFG4
ADC12_A_IFG5
ADC12_A_IFG6
ADC12_A_IFG7
ADC12_A_IFG8
ADC12_A_IFG9
ADC12_A_IFG10
ADC12_A_IFG11
ADC12_A_IFG12
ADC12_A_IFG13
ADC12_A_IFG14
ADC12_A_IFG15
Modified bits of ADC12IFG register.
Returns
None
References HWREG16, and OFS_ADC12IFG.
uint8_t ADC12_A_getInterruptStatus (uint16_t baseAddress, uint16_t memoryInterruptFlagMask)
Returns the status of the selected memory interrupt flags.
Returns the status of the selected memory interrupt flags. Note that the overflow interrupts do not have an interrupt flag to clear; they must be accessed directly from the interrupt vector.
Parameters
baseAddress is the base address of the ADC12_A module.
memoryInterruptFlagMask is a bit mask of the interrupt flags status to be returned. Mask value is the logical OR of any of the following:
ADC12_A_IFG0
ADC12_A_IFG1
ADC12_A_IFG2
ADC12_A_IFG3
ADC12_A_IFG4
ADC12_A_IFG5
ADC12_A_IFG6
ADC12_A_IFG7
ADC12_A_IFG8
ADC12_A_IFG9
ADC12_A_IFG10
ADC12_A_IFG11
ADC12_A_IFG12
ADC12_A_IFG13
ADC12_A_IFG14
ADC12_A_IFG15
Returns
The current interrupt flag status for the corresponding mask.
References HWREG16, and OFS_ADC12IFG.
void ADC12_A_startConversion (uint16_t baseAddress, uint16_t startingMemoryBufferIndex, uint8_t conversionSequenceModeSelect)
Enables/Starts an Analog-to-Digital Conversion.
This function enables/starts the conversion process of the ADC. If the sample/hold signal source chosen during initialization was ADC12OSC, then the conversion is started immediately, otherwise the chosen sample/hold signal source starts the conversion by a rising edge of the signal. Keep in mind when selecting conversion modes, that for sequenced and/or repeated modes, to keep the sample/hold-and-convert process continuing without a trigger from the sample/hold signal source, the multiple samples must be enabled using the ADC12_A_setupSamplingTimer() function. Note that after this function is called, the ADC12_A_disableConversions() has to be called to re-initialize the ADC, reconfigure a memory buffer control, enable/disable the sampling timer, or to change the internal reference voltage.
Parameters
baseAddress is the base address of the ADC12_A module.
startingMemoryBufferIndex is the memory buffer that will hold the first or only conversion. Valid values are:
ADC12_A_MEMORY_0 [Default]
ADC12_A_MEMORY_1
ADC12_A_MEMORY_2
ADC12_A_MEMORY_3
ADC12_A_MEMORY_4
ADC12_A_MEMORY_5
ADC12_A_MEMORY_6
ADC12_A_MEMORY_7
ADC12_A_MEMORY_8
ADC12_A_MEMORY_9
ADC12_A_MEMORY_10
ADC12_A_MEMORY_11
ADC12_A_MEMORY_12
ADC12_A_MEMORY_13
ADC12_A_MEMORY_14
ADC12_A_MEMORY_15
Modified bits are ADC12STARTADDx of ADC12CTL1 register.
conversionSequenceModeSelect determines the ADC operating mode. Valid values are:
ADC12_A_SINGLECHANNEL [Default] - one-time conversion of a single channel into a single memory buffer.
ADC12_A_SEQOFCHANNELS - one time conversion of multiple channels into the specified starting memory buffer and each subsequent memory buffer up until the conversion is stored in a memory buffer dedicated as the end-of-sequence by the memory's control register.
ADC12_A_REPEATED_SINGLECHANNEL - repeated conversions of one channel into a single memory buffer.
ADC12_A_REPEATED_SEQOFCHANNELS - repeated conversions of multiple channels into the specified starting memory buffer and each subsequent memory buffer up until the conversion is stored in a memory buffer dedicated as the end-of-sequence by the memory's control register.
Modified bits are ADC12CONSEQx of ADC12CTL1 register.
Modified bits of ADC12CTL1 register and bits of ADC12CTL0 register.
Returns
None
References ADC12_A_MEMORY_15, ADC12_A_REPEATED_SEQOFCHANNELS, ADC12CONSEQ_3, ADC12CSTARTADD_15, ADC12ENC, ADC12SC, HWREG16, HWREG8, OFS_ADC12CTL0_L, OFS_ADC12CTL1, OFS_ADC12CTL1_H, and OFS_ADC12CTL1_L.
void ADC12_A_disableConversions (uint16_t baseAddress, bool preempt)
Disables the ADC from converting any more signals.
Disables the ADC from converting any more signals. If there is a conversion in progress, this function can stop it immediately if the preempt parameter is set as TRUE, by changing the conversion mode to single-channel, single- conversion and disabling conversions. If the conversion mode is set as single-channel, single-conversion and this function is called without preemption, then the ADC core conversion status is polled until the conversion is complete before disabling conversions to prevent unpredictable data. If the ADC12_A_startConversion() has been called, then this function has to be called to re-initialize the ADC, reconfigure a memory buffer control, enable/disable the sampling pulse mode, or change the internal reference voltage.
Parameters
baseAddress is the base address of the ADC12_A module.
preempt specifies if the current conversion should be pre-empted before the end of the conversion. Valid values are:
ADC12_A_COMPLETECONVERSION - Allows the ADC12_A to end the current conversion before disabling conversions.
ADC12_A_PREEMPTCONVERSION - Stops the ADC12_A immediately, with unpredictable results of the current conversion.
Modified bits of ADC12CTL1 register and bits of ADC12CTL0 register.
Returns
None
References ADC12_A_isBusy(), ADC12_A_PREEMPTCONVERSION, ADC12CONSEQ_3, ADC12ENC, HWREG8, OFS_ADC12CTL0_L, and OFS_ADC12CTL1_L.
uint16_t ADC12_A_getResults (uint16_t baseAddress, uint8_t memoryBufferIndex)
A Signed Integer of the contents of the specified memory buffer.
Returns the raw contents of the specified memory buffer. The format of the content depends on the read-back format of the data: if the data is in signed 2's complement format then the contents in the memory buffer will be left-justified with the least-significant bits as 0's, whereas if the data is in unsigned format then the contents in the memory buffer will be right- justified with the most-significant bits as 0's.
Parameters
baseAddress is the base address of the ADC12_A module.
memoryBufferIndex is the specified Memory Buffer to read. Valid values are:
ADC12_A_MEMORY_0 [Default]
ADC12_A_MEMORY_1
ADC12_A_MEMORY_2
ADC12_A_MEMORY_3
ADC12_A_MEMORY_4
ADC12_A_MEMORY_5
ADC12_A_MEMORY_6
ADC12_A_MEMORY_7
ADC12_A_MEMORY_8
ADC12_A_MEMORY_9
ADC12_A_MEMORY_10
ADC12_A_MEMORY_11
ADC12_A_MEMORY_12
ADC12_A_MEMORY_13
ADC12_A_MEMORY_14
ADC12_A_MEMORY_15
Returns
A signed integer of the contents of the specified memory buffer
References ADC12_A_MEMORY_15, and HWREG16.
void ADC12_A_setResolution (uint16_t baseAddress, uint8_t resolutionSelect)
Use to change the resolution of the converted data.
This function can be used to change the resolution of the converted data from the default of 12-bits.
Parameters
baseAddress is the base address of the ADC12_A module.
resolutionSelect determines the resolution of the converted data. Valid values are:
ADC12_A_RESOLUTION_8BIT
ADC12_A_RESOLUTION_10BIT
ADC12_A_RESOLUTION_12BIT [Default]
Modified bits are ADC12RESx of ADC12CTL2 register.
Returns
None
References ADC12_A_RESOLUTION_12BIT, ADC12RES_3, HWREG8, and OFS_ADC12CTL2_L.
void ADC12_A_setSampleHoldSignalInversion (uint16_t baseAddress, uint16_t invertedSignal)
Use to invert or un-invert the sample/hold signal.
This function can be used to invert or un-invert the sample/hold signal. Note that if a conversion has been started with the startConversion() function, then a call to disableConversions() is required before this function may be called.
Parameters
baseAddress is the base address of the ADC12_A module.
invertedSignal set if the sample/hold signal should be inverted Valid values are:
ADC12_A_NONINVERTEDSIGNAL [Default] - a sample-and-hold of an input signal for conversion will be started on a rising edge of the sample/hold signal.
ADC12_A_INVERTEDSIGNAL - a sample-and-hold of an input signal for conversion will be started on a falling edge of the sample/hold signal.
Modified bits are ADC12ISSH of ADC12CTL1 register.
Returns
None
References ADC12ENC, ADC12ISSH, HWREG16, HWREG8, OFS_ADC12CTL0_L, and OFS_ADC12CTL1.
void ADC12_A_setDataReadBackFormat (uint16_t baseAddress, uint8_t readBackFormat)
Use to set the read-back format of the converted data.
Sets the format of the converted data: how it will be stored into the memory buffer, and how it should be read back. The format can be set as right-justified (default), which indicates that the number will be unsigned, or left-justified, which indicates that the number will be signed in 2's complement format. This change affects all memory buffers for subsequent conversions.
Parameters
baseAddress is the base address of the ADC12_A module.
readBackFormat is the specified format to store the conversions in the memory buffer. Valid values are:
ADC12_A_UNSIGNED_BINARY [Default]
ADC12_A_SIGNED_2SCOMPLEMENT
Modified bits are ADC12DF of ADC12CTL2 register.
Returns
None
References ADC12_A_SIGNED_2SCOMPLEMENT, ADC12DF, HWREG8, and OFS_ADC12CTL2_L.
void ADC12_A_enableReferenceBurst (uint16_t baseAddress)
Enables the reference buffer's burst ability.
Enables the reference buffer's burst ability, allowing the reference buffer to turn off while the ADC is not converting, and automatically turning on when the ADC needs the generated reference voltage for a conversion.
Parameters
baseAddress is the base address of the ADC12_A module.
Returns
None
References ADC12REFBURST, HWREG8, and OFS_ADC12CTL2_L.
void ADC12_A_disableReferenceBurst (uint16_t baseAddress)
Disables the reference buffer's burst ability.
Disables the reference buffer's burst ability, forcing the reference buffer to remain on continuously.
Parameters
baseAddress is the base address of the ADC12_A module.
Returns
None
References ADC12REFBURST, HWREG8, and OFS_ADC12CTL2_L.
void ADC12_A_setReferenceBufferSamplingRate (uint16_t baseAddress, uint8_t samplingRateSelect)
Use to set the reference buffer's sampling rate.
Sets the reference buffer's sampling rate to the selected sampling rate. The default sampling rate is maximum of 200-ksps, and can be reduced to a maximum of 50-ksps to conserve power.
Parameters
baseAddress is the base address of the ADC12_A module.
samplingRateSelect is the specified maximum sampling rate. Valid values are:
ADC12_A_MAXSAMPLINGRATE_200KSPS [Default]
ADC12_A_MAXSAMPLINGRATE_50KSPS
Modified bits are ADC12SR of ADC12CTL2 register.
Returns
None
References ADC12_A_MAXSAMPLINGRATE_50KSPS, ADC12SR, HWREG8, and OFS_ADC12CTL2_L.
uint32_t ADC12_A_getMemoryAddressForDMA (uint16_t baseAddress, uint8_t memoryIndex)
Returns the address of the specified memory buffer for the DMA module.
Returns the address of the specified memory buffer. This can be used in conjunction with the DMA to store the converted data directly to memory.
Parameters
baseAddress is the base address of the ADC12_A module.
memoryIndex is the memory buffer to return the address of. Valid values are:
ADC12_A_MEMORY_0 [Default]
ADC12_A_MEMORY_1
ADC12_A_MEMORY_2
ADC12_A_MEMORY_3
ADC12_A_MEMORY_4
ADC12_A_MEMORY_5
ADC12_A_MEMORY_6
ADC12_A_MEMORY_7
ADC12_A_MEMORY_8
ADC12_A_MEMORY_9
ADC12_A_MEMORY_10
ADC12_A_MEMORY_11
ADC12_A_MEMORY_12
ADC12_A_MEMORY_13
ADC12_A_MEMORY_14
ADC12_A_MEMORY_15
Returns
address of the specified memory buffer
uint16_t ADC12_A_isBusy (uint16_t baseAddress)
Returns the busy status of the ADC12_A core.
Returns the status of the ADC core if there is a conversion currently taking place.
Parameters
baseAddress is the base address of the ADC12_A module.
Returns
One of the following:
ADC12_A_NOTBUSY
ADC12_A_BUSY
indicating if a conversion is taking place
References ADC12BUSY, HWREG8, and OFS_ADC12CTL1_L.
Referenced by ADC12_A_disableConversions().
Copyright 2014, Texas Instruments Incorporated