Eusci_b_i2c_api
Eusci_b_i2c_api
Functions
void EUSCI_B_I2C_masterInit (uint16_t baseAddress, uint8_t selectClockSource, uint32_t i2cClk, uint32_t dataRate, uint8_t byteCounterThreshold, uint8_t autoSTOPGeneration)
DEPRECATED - Initializes the I2C Master block.
void EUSCI_B_I2C_initMaster (uint16_t baseAddress, EUSCI_B_I2C_initMasterParam *param)
Initializes the I2C Master block.
void EUSCI_B_I2C_slaveInit (uint16_t baseAddress, uint8_t slaveAddress, uint8_t slaveAddressOffset, uint32_t slaveOwnAddressEnable)
DEPRECATED - Initializes the I2C Slave block.
void EUSCI_B_I2C_initSlave (uint16_t baseAddress, EUSCI_B_I2C_initSlaveParam *param)
Initializes the I2C Slave block.
void EUSCI_B_I2C_enable (uint16_t baseAddress)
Enables the I2C block.
void EUSCI_B_I2C_disable (uint16_t baseAddress)
Disables the I2C block.
void EUSCI_B_I2C_setSlaveAddress (uint16_t baseAddress, uint8_t slaveAddress)
Sets the address that the I2C Master will place on the bus.
void EUSCI_B_I2C_setMode (uint16_t baseAddress, uint8_t mode)
Sets the mode of the I2C device.
uint8_t EUSCI_B_I2C_getMode (uint16_t baseAddress)
Gets the mode of the I2C device.
void EUSCI_B_I2C_slaveDataPut (uint16_t baseAddress, uint8_t transmitData)
Transmits a byte from the I2C Module.
uint8_t EUSCI_B_I2C_slaveDataGet (uint16_t baseAddress)
Receives a byte that has been sent to the I2C Module.
uint16_t EUSCI_B_I2C_isBusBusy (uint16_t baseAddress)
Indicates whether or not the I2C bus is busy.
uint16_t EUSCI_B_I2C_masterIsStopSent (uint16_t baseAddress)
Indicates whether STOP got sent.
uint16_t EUSCI_B_I2C_masterIsStartSent (uint16_t baseAddress)
Indicates whether Start got sent.
void EUSCI_B_I2C_enableInterrupt (uint16_t baseAddress, uint16_t mask)
Enables individual I2C interrupt sources.
void EUSCI_B_I2C_disableInterrupt (uint16_t baseAddress, uint16_t mask)
Disables individual I2C interrupt sources.
void EUSCI_B_I2C_clearInterruptFlag (uint16_t baseAddress, uint16_t mask)
Clears I2C interrupt sources.
uint16_t EUSCI_B_I2C_getInterruptStatus (uint16_t baseAddress, uint16_t mask)
Gets the current I2C interrupt status.
void EUSCI_B_I2C_masterSendSingleByte (uint16_t baseAddress, uint8_t txData)
Does single byte transmission from Master to Slave.
uint8_t EUSCI_B_I2C_masterReceiveSingleByte (uint16_t baseAddress)
Does single byte reception from Slave.
bool EUSCI_B_I2C_masterSendSingleByteWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Does single byte transmission from Master to Slave with timeout.
void EUSCI_B_I2C_masterMultiByteSendStart (uint16_t baseAddress, uint8_t txData)
Starts multi-byte transmission from Master to Slave.
bool EUSCI_B_I2C_masterMultiByteSendStartWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Starts multi-byte transmission from Master to Slave with timeout.
void EUSCI_B_I2C_masterMultiByteSendNext (uint16_t baseAddress, uint8_t txData)
Continues multi-byte transmission from Master to Slave.
bool EUSCI_B_I2C_masterMultiByteSendNextWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Continues multi-byte transmission from Master to Slave with timeout.
void EUSCI_B_I2C_masterMultiByteSendFinish (uint16_t baseAddress, uint8_t txData)
Finishes multi-byte transmission from Master to Slave.
bool EUSCI_B_I2C_masterMultiByteSendFinishWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Finishes multi-byte transmission from Master to Slave with timeout.
void EUSCI_B_I2C_masterSendStart (uint16_t baseAddress)
This function is used by the Master module to initiate START.
void EUSCI_B_I2C_masterMultiByteSendStop (uint16_t baseAddress)
Send STOP byte at the end of a multi-byte transmission from Master to Slave.
bool EUSCI_B_I2C_masterMultiByteSendStopWithTimeout (uint16_t baseAddress, uint32_t timeout)
Send STOP byte at the end of a multi-byte transmission from Master to Slave with timeout.
void EUSCI_B_I2C_masterReceiveStart (uint16_t baseAddress)
Starts reception at the Master end.
uint8_t EUSCI_B_I2C_masterMultiByteReceiveNext (uint16_t baseAddress)
Starts multi-byte reception at the Master end one byte at a time.
uint8_t EUSCI_B_I2C_masterMultiByteReceiveFinish (uint16_t baseAddress)
Finishes multi-byte reception at the Master end.
bool EUSCI_B_I2C_masterMultiByteReceiveFinishWithTimeout (uint16_t baseAddress, uint8_t *txData, uint32_t timeout)
Finishes multi-byte reception at the Master end with timeout.
void EUSCI_B_I2C_masterMultiByteReceiveStop (uint16_t baseAddress)
Sends the STOP at the end of a multi-byte reception at the Master end.
void EUSCI_B_I2C_enableMultiMasterMode (uint16_t baseAddress)
Enables Multi Master Mode.
void EUSCI_B_I2C_disableMultiMasterMode (uint16_t baseAddress)
Disables Multi Master Mode.
uint8_t EUSCI_B_I2C_masterSingleReceive (uint16_t baseAddress)
receives a byte that has been sent to the I2C Master Module.
uint32_t EUSCI_B_I2C_getReceiveBufferAddress (uint16_t baseAddress)
Returns the address of the RX Buffer of the I2C for the DMA module.
uint32_t EUSCI_B_I2C_getTransmitBufferAddress (uint16_t baseAddress)
Returns the address of the TX Buffer of the I2C for the DMA module.
Detailed Description
Function Documentation
void EUSCI_B_I2C_masterInit (uint16_t baseAddress, uint8_t selectClockSource, uint32_t i2cClk, uint32_t dataRate, uint8_t byteCounterThreshold, uint8_t autoSTOPGeneration)
DEPRECATED - Initializes the I2C Master block.
This function initializes operation of the I2C Master block. Upon successful initialization of the I2C block, this function will have set the bus speed for the master; however I2C module is still disabled till EUSCI_B_I2C_enable is invoked.
Parameters
baseAddress is the base address of the I2C Master module.
selectClockSource is the clocksource. Valid values are:
EUSCI_B_I2C_CLOCKSOURCE_ACLK
EUSCI_B_I2C_CLOCKSOURCE_SMCLK
i2cClk is the rate of the clock supplied to the I2C module (the frequency in Hz of the clock source specified in selectClockSource).
dataRate setup for selecting data transfer rate. Valid values are:
EUSCI_B_I2C_SET_DATA_RATE_400KBPS
EUSCI_B_I2C_SET_DATA_RATE_100KBPS
byteCounterThreshold sets threshold for automatic STOP or UCSTPIFG
autoSTOPGeneration sets up the STOP condition generation. Valid values are:
EUSCI_B_I2C_NO_AUTO_STOP
EUSCI_B_I2C_SET_BYTECOUNT_THRESHOLD_FLAG
EUSCI_B_I2C_SEND_STOP_AUTOMATICALLY_ON_BYTECOUNT_THRESHOLD
Returns
None
References EUSCI_B_I2C_initMasterParam::autoSTOPGeneration, EUSCI_B_I2C_initMasterParam::byteCounterThreshold, EUSCI_B_I2C_initMasterParam::dataRate, EUSCI_B_I2C_initMaster(), EUSCI_B_I2C_initMasterParam::i2cClk, and EUSCI_B_I2C_initMasterParam::selectClockSource.
void EUSCI_B_I2C_initMaster (uint16_t baseAddress, EUSCI_B_I2C_initMasterParam * param)
Initializes the I2C Master block.
This function initializes operation of the I2C Master block. Upon successful initialization of the I2C block, this function will have set the bus speed for the master; however I2C module is still disabled till EUSCI_B_I2C_enable is invoked.
Parameters
baseAddress is the base address of the I2C Master module.
param is the pointer to the struct for master initialization.
Returns
None
References EUSCI_B_I2C_initMasterParam::autoSTOPGeneration, EUSCI_B_I2C_initMasterParam::byteCounterThreshold, EUSCI_B_I2C_initMasterParam::dataRate, EUSCI_B_I2C_CLOCKSOURCE_ACLK, EUSCI_B_I2C_CLOCKSOURCE_SMCLK, EUSCI_B_I2C_NO_AUTO_STOP, EUSCI_B_I2C_SEND_STOP_AUTOMATICALLY_ON_BYTECOUNT_THRESHOLD, EUSCI_B_I2C_SET_BYTECOUNT_THRESHOLD_FLAG, EUSCI_B_I2C_SET_DATA_RATE_100KBPS, EUSCI_B_I2C_SET_DATA_RATE_400KBPS, HWREG16, EUSCI_B_I2C_initMasterParam::i2cClk, OFS_UCBxBRW, OFS_UCBxCTLW0, OFS_UCBxCTLW1, OFS_UCBxTBCNT, EUSCI_B_I2C_initMasterParam::selectClockSource, UCASTP_3, UCMODE_3, UCMST, UCSWRST, and UCSYNC.
Referenced by EUSCI_B_I2C_masterInit().
void EUSCI_B_I2C_slaveInit (uint16_t baseAddress, uint8_t slaveAddress, uint8_t slaveAddressOffset, uint32_t slaveOwnAddressEnable)
DEPRECATED - Initializes the I2C Slave block.
This function initializes operation of the I2C as a Slave mode. Upon successful initialization of the I2C blocks, this function will have set the slave address but the I2C module is still disabled till EUSCI_B_I2C_enable is invoked.
Parameters
baseAddress is the base address of the I2C Slave module.
slaveAddress 7-bit slave address
slaveAddressOffset Own address Offset referred to- 'x' value of UCBxI2COAx. Valid values are:
EUSCI_B_I2C_OWN_ADDRESS_OFFSET0
EUSCI_B_I2C_OWN_ADDRESS_OFFSET1
EUSCI_B_I2C_OWN_ADDRESS_OFFSET2
EUSCI_B_I2C_OWN_ADDRESS_OFFSET3
slaveOwnAddressEnable selects if the specified address is enabled or disabled. Valid values are:
EUSCI_B_I2C_OWN_ADDRESS_DISABLE
EUSCI_B_I2C_OWN_ADDRESS_ENABLE
Returns
None
References EUSCI_B_I2C_initSlave(), EUSCI_B_I2C_initSlaveParam::slaveAddress, EUSCI_B_I2C_initSlaveParam::slaveAddressOffset, and EUSCI_B_I2C_initSlaveParam::slaveOwnAddressEnable.
void EUSCI_B_I2C_initSlave (uint16_t baseAddress, EUSCI_B_I2C_initSlaveParam * param)
Initializes the I2C Slave block.
This function initializes operation of the I2C as a Slave mode. Upon successful initialization of the I2C blocks, this function will have set the slave address but the I2C module is still disabled till EUSCI_B_I2C_enable is invoked.
Parameters
baseAddress is the base address of the I2C Slave module.
param is the pointer to the struct for slave initialization.
Returns
None
References EUSCI_B_I2C_OWN_ADDRESS_OFFSET0, EUSCI_B_I2C_OWN_ADDRESS_OFFSET1, EUSCI_B_I2C_OWN_ADDRESS_OFFSET2, EUSCI_B_I2C_OWN_ADDRESS_OFFSET3, HWREG16, OFS_UCBxCTLW0, OFS_UCBxI2COA0, EUSCI_B_I2C_initSlaveParam::slaveAddress, EUSCI_B_I2C_initSlaveParam::slaveAddressOffset, EUSCI_B_I2C_initSlaveParam::slaveOwnAddressEnable, UCMODE_3, UCMST, UCSWRST, and UCSYNC.
Referenced by EUSCI_B_I2C_slaveInit().
void EUSCI_B_I2C_enable (uint16_t baseAddress)
Enables the I2C block.
This will enable operation of the I2C block.
Parameters
baseAddress is the base address of the USCI I2C module.
Modified bits are UCSWRST of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, and UCSWRST.
void EUSCI_B_I2C_disable (uint16_t baseAddress)
Disables the I2C block.
This will disable operation of the I2C block.
Parameters
baseAddress is the base address of the USCI I2C module.
Modified bits are UCSWRST of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, and UCSWRST.
void EUSCI_B_I2C_setSlaveAddress (uint16_t baseAddress, uint8_t slaveAddress)
Sets the address that the I2C Master will place on the bus.
This function will set the address that the I2C Master will place on the bus when initiating a transaction.
Parameters
baseAddress is the base address of the USCI I2C module.
slaveAddress 7-bit slave address
Modified bits of UCBxI2CSA register.
Returns
None
References HWREG16, and OFS_UCBxI2CSA.
void EUSCI_B_I2C_setMode (uint16_t baseAddress, uint8_t mode)
Sets the mode of the I2C device.
When the receive parameter is set to EUSCI_B_I2C_TRANSMIT_MODE, the address will indicate that the I2C module is in receive mode; otherwise, the I2C module is in send mode.
Parameters
baseAddress is the base address of the USCI I2C module.
mode Mode for the EUSCI_B_I2C module Valid values are:
EUSCI_B_I2C_TRANSMIT_MODE [Default]
EUSCI_B_I2C_RECEIVE_MODE
Modified bits are UCTR of UCBxCTLW0 register.
Returns
None
References EUSCI_B_I2C_RECEIVE_MODE, EUSCI_B_I2C_TRANSMIT_MODE, HWREG16, and OFS_UCBxCTLW0.
uint8_t EUSCI_B_I2C_getMode (uint16_t baseAddress)
Gets the mode of the I2C device.
Current I2C transmit/receive mode.
Parameters
baseAddress is the base address of the I2C module.
Modified bits are UCTR of UCBxCTLW0 register.
Returns
None Return one of the following:
EUSCI_B_I2C_TRANSMIT_MODE
EUSCI_B_I2C_RECEIVE_MODE
indicating the current mode
References HWREG16, OFS_UCBxCTLW0, and UCTR.
void EUSCI_B_I2C_slaveDataPut (uint16_t baseAddress, uint8_t transmitData)
Transmits a byte from the I2C Module.
This function will place the supplied data into I2C transmit data register to start transmission.
Parameters
baseAddress is the base address of the I2C Slave module.
transmitData data to be transmitted from the I2C module
Modified bits of UCBxTXBUF register.
Returns
None
References HWREG16, and OFS_UCBxTXBUF.
uint8_t EUSCI_B_I2C_slaveDataGet (uint16_t baseAddress)
Receives a byte that has been sent to the I2C Module.
This function reads a byte of data from the I2C receive data Register.
Parameters
baseAddress is the base address of the I2C Slave module.
Returns
Returns the byte received from by the I2C module, cast as an uint8_t.
References HWREG16, and OFS_UCBxRXBUF.
uint16_t EUSCI_B_I2C_isBusBusy (uint16_t baseAddress)
Indicates whether or not the I2C bus is busy.
This function returns an indication of whether or not the I2C bus is busy. This function checks the status of the bus via UCBBUSY bit in UCBxSTAT register.
Parameters
baseAddress is the base address of the I2C module.
Returns
One of the following:
EUSCI_B_I2C_BUS_BUSY
EUSCI_B_I2C_BUS_NOT_BUSY
indicating whether the bus is busy
References HWREG16, OFS_UCBxSTATW, and UCBBUSY.
uint16_t EUSCI_B_I2C_masterIsStopSent (uint16_t baseAddress)
Indicates whether STOP got sent.
This function returns an indication of whether or not STOP got sent This function checks the status of the bus via UCTXSTP bit in UCBxCTL1 register.
Parameters
baseAddress is the base address of the I2C Master module.
Returns
One of the following:
EUSCI_B_I2C_STOP_SEND_COMPLETE
EUSCI_B_I2C_SENDING_STOP
indicating whether the stop was sent
References HWREG16, OFS_UCBxCTLW0, and UCTXSTP.
uint16_t EUSCI_B_I2C_masterIsStartSent (uint16_t baseAddress)
Indicates whether Start got sent.
This function returns an indication of whether or not Start got sent This function checks the status of the bus via UCTXSTT bit in UCBxCTL1 register.
Parameters
baseAddress is the base address of the I2C Master module.
Returns
One of the following:
EUSCI_B_I2C_START_SEND_COMPLETE
EUSCI_B_I2C_SENDING_START
indicating whether the start was sent
References HWREG16, OFS_UCBxCTLW0, and UCTXSTT.
void EUSCI_B_I2C_enableInterrupt (uint16_t baseAddress, uint16_t mask)
Enables individual I2C interrupt sources.
Enables the indicated I2C interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the I2C module.
mask is the bit mask of the interrupt sources to be enabled. Mask value is the logical OR of any of the following:
EUSCI_B_I2C_NAK_INTERRUPT - Not-acknowledge interrupt
EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT - Arbitration lost interrupt
EUSCI_B_I2C_STOP_INTERRUPT - STOP condition interrupt
EUSCI_B_I2C_START_INTERRUPT - START condition interrupt
EUSCI_B_I2C_TRANSMIT_INTERRUPT0 - Transmit interrupt0
EUSCI_B_I2C_TRANSMIT_INTERRUPT1 - Transmit interrupt1
EUSCI_B_I2C_TRANSMIT_INTERRUPT2 - Transmit interrupt2
EUSCI_B_I2C_TRANSMIT_INTERRUPT3 - Transmit interrupt3
EUSCI_B_I2C_RECEIVE_INTERRUPT0 - Receive interrupt0
EUSCI_B_I2C_RECEIVE_INTERRUPT1 - Receive interrupt1
EUSCI_B_I2C_RECEIVE_INTERRUPT2 - Receive interrupt2
EUSCI_B_I2C_RECEIVE_INTERRUPT3 - Receive interrupt3
EUSCI_B_I2C_BIT9_POSITION_INTERRUPT - Bit position 9 interrupt
EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT - Clock low timeout interrupt enable
EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT - Byte counter interrupt enable
Modified bits of UCBxIE register.
Returns
None
References EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT, EUSCI_B_I2C_BIT9_POSITION_INTERRUPT, EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT, EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT, EUSCI_B_I2C_NAK_INTERRUPT, EUSCI_B_I2C_RECEIVE_INTERRUPT0, EUSCI_B_I2C_RECEIVE_INTERRUPT1, EUSCI_B_I2C_RECEIVE_INTERRUPT2, EUSCI_B_I2C_RECEIVE_INTERRUPT3, EUSCI_B_I2C_START_INTERRUPT, EUSCI_B_I2C_STOP_INTERRUPT, EUSCI_B_I2C_TRANSMIT_INTERRUPT0, EUSCI_B_I2C_TRANSMIT_INTERRUPT1, EUSCI_B_I2C_TRANSMIT_INTERRUPT2, EUSCI_B_I2C_TRANSMIT_INTERRUPT3, HWREG16, and OFS_UCBxIE.
void EUSCI_B_I2C_disableInterrupt (uint16_t baseAddress, uint16_t mask)
Disables individual I2C interrupt sources.
Disables the indicated I2C interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the I2C module.
mask is the bit mask of the interrupt sources to be disabled. Mask value is the logical OR of any of the following:
EUSCI_B_I2C_NAK_INTERRUPT - Not-acknowledge interrupt
EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT - Arbitration lost interrupt
EUSCI_B_I2C_STOP_INTERRUPT - STOP condition interrupt
EUSCI_B_I2C_START_INTERRUPT - START condition interrupt
EUSCI_B_I2C_TRANSMIT_INTERRUPT0 - Transmit interrupt0
EUSCI_B_I2C_TRANSMIT_INTERRUPT1 - Transmit interrupt1
EUSCI_B_I2C_TRANSMIT_INTERRUPT2 - Transmit interrupt2
EUSCI_B_I2C_TRANSMIT_INTERRUPT3 - Transmit interrupt3
EUSCI_B_I2C_RECEIVE_INTERRUPT0 - Receive interrupt0
EUSCI_B_I2C_RECEIVE_INTERRUPT1 - Receive interrupt1
EUSCI_B_I2C_RECEIVE_INTERRUPT2 - Receive interrupt2
EUSCI_B_I2C_RECEIVE_INTERRUPT3 - Receive interrupt3
EUSCI_B_I2C_BIT9_POSITION_INTERRUPT - Bit position 9 interrupt
EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT - Clock low timeout interrupt enable
EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT - Byte counter interrupt enable
Modified bits of UCBxIE register.
Returns
None
References EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT, EUSCI_B_I2C_BIT9_POSITION_INTERRUPT, EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT, EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT, EUSCI_B_I2C_NAK_INTERRUPT, EUSCI_B_I2C_RECEIVE_INTERRUPT0, EUSCI_B_I2C_RECEIVE_INTERRUPT1, EUSCI_B_I2C_RECEIVE_INTERRUPT2, EUSCI_B_I2C_RECEIVE_INTERRUPT3, EUSCI_B_I2C_START_INTERRUPT, EUSCI_B_I2C_STOP_INTERRUPT, EUSCI_B_I2C_TRANSMIT_INTERRUPT0, EUSCI_B_I2C_TRANSMIT_INTERRUPT1, EUSCI_B_I2C_TRANSMIT_INTERRUPT2, EUSCI_B_I2C_TRANSMIT_INTERRUPT3, HWREG16, and OFS_UCBxIE.
void EUSCI_B_I2C_clearInterruptFlag (uint16_t baseAddress, uint16_t mask)
Clears I2C interrupt sources.
The I2C interrupt source is cleared, so that it no longer asserts. The highest interrupt flag is automatically cleared when an interrupt vector generator is used.
Parameters
baseAddress is the base address of the I2C module.
mask is a bit mask of the interrupt sources to be cleared. Mask value is the logical OR of any of the following:
EUSCI_B_I2C_NAK_INTERRUPT - Not-acknowledge interrupt
EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT - Arbitration lost interrupt
EUSCI_B_I2C_STOP_INTERRUPT - STOP condition interrupt
EUSCI_B_I2C_START_INTERRUPT - START condition interrupt
EUSCI_B_I2C_TRANSMIT_INTERRUPT0 - Transmit interrupt0
EUSCI_B_I2C_TRANSMIT_INTERRUPT1 - Transmit interrupt1
EUSCI_B_I2C_TRANSMIT_INTERRUPT2 - Transmit interrupt2
EUSCI_B_I2C_TRANSMIT_INTERRUPT3 - Transmit interrupt3
EUSCI_B_I2C_RECEIVE_INTERRUPT0 - Receive interrupt0
EUSCI_B_I2C_RECEIVE_INTERRUPT1 - Receive interrupt1
EUSCI_B_I2C_RECEIVE_INTERRUPT2 - Receive interrupt2
EUSCI_B_I2C_RECEIVE_INTERRUPT3 - Receive interrupt3
EUSCI_B_I2C_BIT9_POSITION_INTERRUPT - Bit position 9 interrupt
EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT - Clock low timeout interrupt enable
EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT - Byte counter interrupt enable
Modified bits of UCBxIFG register.
Returns
None
References EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT, EUSCI_B_I2C_BIT9_POSITION_INTERRUPT, EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT, EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT, EUSCI_B_I2C_NAK_INTERRUPT, EUSCI_B_I2C_RECEIVE_INTERRUPT0, EUSCI_B_I2C_RECEIVE_INTERRUPT1, EUSCI_B_I2C_RECEIVE_INTERRUPT2, EUSCI_B_I2C_RECEIVE_INTERRUPT3, EUSCI_B_I2C_START_INTERRUPT, EUSCI_B_I2C_STOP_INTERRUPT, EUSCI_B_I2C_TRANSMIT_INTERRUPT0, EUSCI_B_I2C_TRANSMIT_INTERRUPT1, EUSCI_B_I2C_TRANSMIT_INTERRUPT2, EUSCI_B_I2C_TRANSMIT_INTERRUPT3, HWREG16, and OFS_UCBxIFG.
uint16_t EUSCI_B_I2C_getInterruptStatus (uint16_t baseAddress, uint16_t mask)
Gets the current I2C interrupt status.
This returns the interrupt status for the I2C module based on which flag is passed.
Parameters
baseAddress is the base address of the I2C module.
mask is the masked interrupt flag status to be returned. Mask value is the logical OR of any of the following:
EUSCI_B_I2C_NAK_INTERRUPT - Not-acknowledge interrupt
EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT - Arbitration lost interrupt
EUSCI_B_I2C_STOP_INTERRUPT - STOP condition interrupt
EUSCI_B_I2C_START_INTERRUPT - START condition interrupt
EUSCI_B_I2C_TRANSMIT_INTERRUPT0 - Transmit interrupt0
EUSCI_B_I2C_TRANSMIT_INTERRUPT1 - Transmit interrupt1
EUSCI_B_I2C_TRANSMIT_INTERRUPT2 - Transmit interrupt2
EUSCI_B_I2C_TRANSMIT_INTERRUPT3 - Transmit interrupt3
EUSCI_B_I2C_RECEIVE_INTERRUPT0 - Receive interrupt0
EUSCI_B_I2C_RECEIVE_INTERRUPT1 - Receive interrupt1
EUSCI_B_I2C_RECEIVE_INTERRUPT2 - Receive interrupt2
EUSCI_B_I2C_RECEIVE_INTERRUPT3 - Receive interrupt3
EUSCI_B_I2C_BIT9_POSITION_INTERRUPT - Bit position 9 interrupt
EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT - Clock low timeout interrupt enable
EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT - Byte counter interrupt enable
Returns
Logical OR of any of the following:
EUSCI_B_I2C_NAK_INTERRUPT Not-acknowledge interrupt
EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT Arbitration lost interrupt
EUSCI_B_I2C_STOP_INTERRUPT STOP condition interrupt
EUSCI_B_I2C_START_INTERRUPT START condition interrupt
EUSCI_B_I2C_TRANSMIT_INTERRUPT0 Transmit interrupt0
EUSCI_B_I2C_TRANSMIT_INTERRUPT1 Transmit interrupt1
EUSCI_B_I2C_TRANSMIT_INTERRUPT2 Transmit interrupt2
EUSCI_B_I2C_TRANSMIT_INTERRUPT3 Transmit interrupt3
EUSCI_B_I2C_RECEIVE_INTERRUPT0 Receive interrupt0
EUSCI_B_I2C_RECEIVE_INTERRUPT1 Receive interrupt1
EUSCI_B_I2C_RECEIVE_INTERRUPT2 Receive interrupt2
EUSCI_B_I2C_RECEIVE_INTERRUPT3 Receive interrupt3
EUSCI_B_I2C_BIT9_POSITION_INTERRUPT Bit position 9 interrupt
EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT Clock low timeout interrupt enable
EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT Byte counter interrupt enable
indicating the status of the masked interrupts
References EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT, EUSCI_B_I2C_BIT9_POSITION_INTERRUPT, EUSCI_B_I2C_BYTE_COUNTER_INTERRUPT, EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT, EUSCI_B_I2C_NAK_INTERRUPT, EUSCI_B_I2C_RECEIVE_INTERRUPT0, EUSCI_B_I2C_RECEIVE_INTERRUPT1, EUSCI_B_I2C_RECEIVE_INTERRUPT2, EUSCI_B_I2C_RECEIVE_INTERRUPT3, EUSCI_B_I2C_START_INTERRUPT, EUSCI_B_I2C_STOP_INTERRUPT, EUSCI_B_I2C_TRANSMIT_INTERRUPT0, EUSCI_B_I2C_TRANSMIT_INTERRUPT1, EUSCI_B_I2C_TRANSMIT_INTERRUPT2, EUSCI_B_I2C_TRANSMIT_INTERRUPT3, HWREG16, and OFS_UCBxIFG.
void EUSCI_B_I2C_masterSendSingleByte (uint16_t baseAddress, uint8_t txData)
Does single byte transmission from Master to Slave.
This function is used by the Master module to send a single byte. This function sends a start, then transmits the byte to the slave and then sends a stop.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the data byte to be transmitted
Modified bits of UCBxTXBUF register, bits of UCBxCTLW0 register, bits of UCBxIE register and bits of UCBxIFG register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, UCTR, UCTXIE, UCTXIFG, UCTXSTP, and UCTXSTT.
uint8_t EUSCI_B_I2C_masterReceiveSingleByte (uint16_t baseAddress)
Does single byte reception from Slave.
This function is used by the Master module to receive a single byte. This function sends start and stop, waits for data reception and then receives the data from the slave
Parameters
baseAddress is the base address of the I2C Master module.
Modified bits of UCBxTXBUF register, bits of UCBxCTLW0 register, bits of UCBxIE register and bits of UCBxIFG register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the transmission process.
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIFG, OFS_UCBxRXBUF, UCRXIFG, UCTR, UCTXSTP, and UCTXSTT.
bool EUSCI_B_I2C_masterSendSingleByteWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Does single byte transmission from Master to Slave with timeout.
This function is used by the Master module to send a single byte. This function sends a start, then transmits the byte to the slave and then sends a stop.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the data byte to be transmitted
timeout is the amount of time to wait until giving up
Modified bits of UCBxTXBUF register, bits of UCBxCTLW0 register, bits of UCBxIE register and bits of UCBxIFG register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the transmission process.
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, STATUS_FAIL, STATUS_SUCCESS, UCTR, UCTXIE, UCTXIFG, UCTXSTP, and UCTXSTT.
void EUSCI_B_I2C_masterMultiByteSendStart (uint16_t baseAddress, uint8_t txData)
Starts multi-byte transmission from Master to Slave.
This function is used by the master module to start a multi byte transaction.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the first data byte to be transmitted
Modified bits of UCBxTXBUF register, bits of UCBxCTLW0 register, bits of UCBxIE register and bits of UCBxIFG register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, UCTR, UCTXIE, UCTXIFG, and UCTXSTT.
bool EUSCI_B_I2C_masterMultiByteSendStartWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Starts multi-byte transmission from Master to Slave with timeout.
This function is used by the master module to start a multi byte transaction.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the first data byte to be transmitted
timeout is the amount of time to wait until giving up
Modified bits of UCBxTXBUF register, bits of UCBxCTLW0 register, bits of UCBxIE register and bits of UCBxIFG register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the transmission process.
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, STATUS_FAIL, STATUS_SUCCESS, UCTR, UCTXIE, UCTXIFG, and UCTXSTT.
void EUSCI_B_I2C_masterMultiByteSendNext (uint16_t baseAddress, uint8_t txData)
Continues multi-byte transmission from Master to Slave.
This function is used by the Master module continue each byte of a multi- byte transmission. This function transmits each data byte of a multi-byte transmission to the slave.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the next data byte to be transmitted
Modified bits of UCBxTXBUF register.
Returns
None
References HWREG16, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, UCTXIE, and UCTXIFG.
bool EUSCI_B_I2C_masterMultiByteSendNextWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Continues multi-byte transmission from Master to Slave with timeout.
This function is used by the Master module continue each byte of a multi- byte transmission. This function transmits each data byte of a multi-byte transmission to the slave.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the next data byte to be transmitted
timeout is the amount of time to wait until giving up
Modified bits of UCBxTXBUF register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the transmission process.
References HWREG16, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, STATUS_FAIL, STATUS_SUCCESS, UCTXIE, and UCTXIFG.
void EUSCI_B_I2C_masterMultiByteSendFinish (uint16_t baseAddress, uint8_t txData)
Finishes multi-byte transmission from Master to Slave.
This function is used by the Master module to send the last byte and STOP. This function transmits the last data byte of a multi-byte transmission to the slave and then sends a stop.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the last data byte to be transmitted in a multi-byte transmission
Modified bits of UCBxTXBUF register and bits of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, UCTXIE, UCTXIFG, and UCTXSTP.
bool EUSCI_B_I2C_masterMultiByteSendFinishWithTimeout (uint16_t baseAddress, uint8_t txData, uint32_t timeout)
Finishes multi-byte transmission from Master to Slave with timeout.
This function is used by the Master module to send the last byte and STOP. This function transmits the last data byte of a multi-byte transmission to the slave and then sends a stop.
Parameters
baseAddress is the base address of the I2C Master module.
txData is the last data byte to be transmitted in a multi-byte transmission
timeout is the amount of time to wait until giving up
Modified bits of UCBxTXBUF register and bits of UCBxCTLW0 register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the transmission process.
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxTXBUF, STATUS_FAIL, STATUS_SUCCESS, UCTXIE, UCTXIFG, and UCTXSTP.
void EUSCI_B_I2C_masterSendStart (uint16_t baseAddress)
This function is used by the Master module to initiate START.
This function is used by the Master module to initiate START
Parameters
baseAddress is the base address of the I2C Master module.
Modified bits are UCTXSTT of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, and UCTXSTT.
void EUSCI_B_I2C_masterMultiByteSendStop (uint16_t baseAddress)
Send STOP byte at the end of a multi-byte transmission from Master to Slave.
This function is used by the Master module send STOP at the end of a multi- byte transmission. This function sends a stop after current transmission is complete.
Parameters
baseAddress is the base address of the I2C Master module.
Modified bits are UCTXSTP of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, UCTXIE, UCTXIFG, and UCTXSTP.
bool EUSCI_B_I2C_masterMultiByteSendStopWithTimeout (uint16_t baseAddress, uint32_t timeout)
Send STOP byte at the end of a multi-byte transmission from Master to Slave with timeout.
This function is used by the Master module send STOP at the end of a multi- byte transmission. This function sends a stop after current transmission is complete.
Parameters
baseAddress is the base address of the I2C Master module.
timeout is the amount of time to wait until giving up
Modified bits are UCTXSTP of UCBxCTLW0 register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the transmission process.
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIE, OFS_UCBxIFG, STATUS_FAIL, STATUS_SUCCESS, UCTXIE, UCTXIFG, and UCTXSTP.
void EUSCI_B_I2C_masterReceiveStart (uint16_t baseAddress)
Starts reception at the Master end.
This function is used by the Master module initiate reception of a single byte. This function sends a start.
Parameters
baseAddress is the base address of the I2C Master module.
Modified bits are UCTXSTT of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, UCTR, and UCTXSTT.
uint8_t EUSCI_B_I2C_masterMultiByteReceiveNext (uint16_t baseAddress)
Starts multi-byte reception at the Master end one byte at a time.
This function is used by the Master module to receive each byte of a multi- byte reception. This function reads currently received byte.
Parameters
baseAddress is the base address of the I2C Master module.
Returns
Received byte at Master end.
References HWREG16, and OFS_UCBxRXBUF.
uint8_t EUSCI_B_I2C_masterMultiByteReceiveFinish (uint16_t baseAddress)
Finishes multi-byte reception at the Master end.
This function is used by the Master module to initiate completion of a multi-byte reception. This function receives the current byte and initiates the STOP from master to slave.
Parameters
baseAddress is the base address of the I2C Master module.
Modified bits are UCTXSTP of UCBxCTLW0 register.
Returns
Received byte at Master end.
References HWREG16, OFS_UCBxCTLW0, OFS_UCBxIFG, OFS_UCBxRXBUF, UCRXIFG, and UCTXSTP.
bool EUSCI_B_I2C_masterMultiByteReceiveFinishWithTimeout (uint16_t baseAddress, uint8_t * txData, uint32_t timeout)
Finishes multi-byte reception at the Master end with timeout.
This function is used by the Master module to initiate completion of a multi-byte reception. This function receives the current byte and initiates the STOP from master to slave.
Parameters
baseAddress is the base address of the I2C Master module.
txData is a pointer to the location to store the received byte at master end
timeout is the amount of time to wait until giving up
Modified bits are UCTXSTP of UCBxCTLW0 register.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the reception process
References HWREG16, HWREG8, OFS_UCBxCTLW0, OFS_UCBxIFG, OFS_UCBxRXBUF, STATUS_FAIL, STATUS_SUCCESS, UCRXIFG, and UCTXSTP.
void EUSCI_B_I2C_masterMultiByteReceiveStop (uint16_t baseAddress)
Sends the STOP at the end of a multi-byte reception at the Master end.
This function is used by the Master module to initiate STOP
Parameters
baseAddress is the base address of the I2C Master module.
Modified bits are UCTXSTP of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, and UCTXSTP.
void EUSCI_B_I2C_enableMultiMasterMode (uint16_t baseAddress)
Enables Multi Master Mode.
At the end of this function, the I2C module is still disabled till EUSCI_B_I2C_enable is invoked
Parameters
baseAddress is the base address of the I2C module.
Modified bits are UCSWRST and UCMM of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, UCMM, and UCSWRST.
void EUSCI_B_I2C_disableMultiMasterMode (uint16_t baseAddress)
Disables Multi Master Mode.
At the end of this function, the I2C module is still disabled till EUSCI_B_I2C_enable is invoked
Parameters
baseAddress is the base address of the I2C module.
Modified bits are UCSWRST and UCMM of UCBxCTLW0 register.
Returns
None
References HWREG16, OFS_UCBxCTLW0, UCMM, and UCSWRST.
uint8_t EUSCI_B_I2C_masterSingleReceive (uint16_t baseAddress)
receives a byte that has been sent to the I2C Master Module.
This function reads a byte of data from the I2C receive data Register.
Parameters
baseAddress is the base address of the I2C Master module.
Returns
Returns the byte received from by the I2C module, cast as an uint8_t.
References HWREG16, OFS_UCBxIE, OFS_UCBxIFG, OFS_UCBxRXBUF, UCRXIE0, and UCRXIFG0.
uint32_t EUSCI_B_I2C_getReceiveBufferAddress (uint16_t baseAddress)
Returns the address of the RX Buffer of the I2C for the DMA module.
Returns the address of the I2C RX Buffer. This can be used in conjunction with the DMA to store the received data directly to memory.
Parameters
baseAddress is the base address of the I2C module.
Returns
The address of the I2C RX Buffer
References OFS_UCBxRXBUF.
uint32_t EUSCI_B_I2C_getTransmitBufferAddress (uint16_t baseAddress)
Returns the address of the TX Buffer of the I2C for the DMA module.
Returns the address of the I2C TX Buffer. This can be used in conjunction with the DMA to obtain transmitted data directly from memory.
Parameters
baseAddress is the base address of the I2C module.
Returns
The address of the I2C TX Buffer
References OFS_UCBxTXBUF.
Copyright 2014, Texas Instruments Incorporated