Eusci_a_spi_api
Eusci_a_spi_api
Functions
void EUSCI_A_SPI_masterInit (uint16_t baseAddress, uint8_t selectClockSource, uint32_t clockSourceFrequency, uint32_t desiredSpiClock, uint16_t msbFirst, uint16_t clockPhase, uint16_t clockPolarity, uint16_t spiMode)
DEPRECATED - Initializes the SPI Master block.
void EUSCI_A_SPI_initMaster (uint16_t baseAddress, EUSCI_A_SPI_initMasterParam *param)
Initializes the SPI Master block.
void EUSCI_A_SPI_select4PinFunctionality (uint16_t baseAddress, uint8_t select4PinFunctionality)
Selects 4Pin Functionality.
void EUSCI_A_SPI_masterChangeClock (uint16_t baseAddress, uint32_t clockSourceFrequency, uint32_t desiredSpiClock)
DEPRECATED - Initializes the SPI Master clock. At the end of this function call, SPI module is left enabled.
void EUSCI_A_SPI_changeMasterClock (uint16_t baseAddress, EUSCI_A_SPI_changeMasterClockParam *param)
Initializes the SPI Master clock. At the end of this function call, SPI module is left enabled.
void EUSCI_A_SPI_slaveInit (uint16_t baseAddress, uint16_t msbFirst, uint16_t clockPhase, uint16_t clockPolarity, uint16_t spiMode)
DEPRECATED - Initializes the SPI Slave block.
void EUSCI_A_SPI_initSlave (uint16_t baseAddress, EUSCI_A_SPI_initSlaveParam *param)
Initializes the SPI Slave block.
void EUSCI_A_SPI_changeClockPhasePolarity (uint16_t baseAddress, uint16_t clockPhase, uint16_t clockPolarity)
Changes the SPI clock phase and polarity. At the end of this function call, SPI module is left enabled.
void EUSCI_A_SPI_transmitData (uint16_t baseAddress, uint8_t transmitData)
Transmits a byte from the SPI Module.
uint8_t EUSCI_A_SPI_receiveData (uint16_t baseAddress)
Receives a byte that has been sent to the SPI Module.
void EUSCI_A_SPI_enableInterrupt (uint16_t baseAddress, uint8_t mask)
Enables individual SPI interrupt sources.
void EUSCI_A_SPI_disableInterrupt (uint16_t baseAddress, uint8_t mask)
Disables individual SPI interrupt sources.
uint8_t EUSCI_A_SPI_getInterruptStatus (uint16_t baseAddress, uint8_t mask)
Gets the current SPI interrupt status.
void EUSCI_A_SPI_clearInterruptFlag (uint16_t baseAddress, uint8_t mask)
Clears the selected SPI interrupt status flag.
void EUSCI_A_SPI_enable (uint16_t baseAddress)
Enables the SPI block.
void EUSCI_A_SPI_disable (uint16_t baseAddress)
Disables the SPI block.
uint32_t EUSCI_A_SPI_getReceiveBufferAddress (uint16_t baseAddress)
Returns the address of the RX Buffer of the SPI for the DMA module.
uint32_t EUSCI_A_SPI_getTransmitBufferAddress (uint16_t baseAddress)
Returns the address of the TX Buffer of the SPI for the DMA module.
uint16_t EUSCI_A_SPI_isBusy (uint16_t baseAddress)
Indicates whether or not the SPI bus is busy.
Detailed Description
Function Documentation
void EUSCI_A_SPI_masterInit (uint16_t baseAddress, uint8_t selectClockSource, uint32_t clockSourceFrequency, uint32_t desiredSpiClock, uint16_t msbFirst, uint16_t clockPhase, uint16_t clockPolarity, uint16_t spiMode)
DEPRECATED - Initializes the SPI Master block.
Upon successful initialization of the SPI master block, this function will have set the bus speed for the master, but the SPI Master block still remains disabled and must be enabled with EUSCI_A_SPI_enable()
Parameters
baseAddress is the base address of the EUSCI_A_SPI Master module.
selectClockSource selects Clock source. Valid values are:
EUSCI_A_SPI_CLOCKSOURCE_ACLK
EUSCI_A_SPI_CLOCKSOURCE_SMCLK
clockSourceFrequency is the frequency of the selected clock source
desiredSpiClock is the desired clock rate for SPI communication
msbFirst controls the direction of the receive and transmit shift register. Valid values are:
EUSCI_A_SPI_MSB_FIRST
EUSCI_A_SPI_LSB_FIRST [Default]
clockPhase is clock phase select. Valid values are:
EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT [Default]
EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT
clockPolarity is clock polarity select Valid values are:
EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH
EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW [Default]
spiMode is SPI mode select Valid values are:
EUSCI_A_SPI_3PIN
EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_HIGH
EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_LOW
Modified bits are UCCKPH, UCCKPL, UC7BIT, UCMSB, UCSSELx and UCSWRST of UCAxCTLW0 register.
Returns
STATUS_SUCCESS
References EUSCI_A_SPI_initMasterParam::clockPhase, EUSCI_A_SPI_initMasterParam::clockPolarity, EUSCI_A_SPI_initMasterParam::clockSourceFrequency, EUSCI_A_SPI_initMasterParam::desiredSpiClock, EUSCI_A_SPI_initMaster(), EUSCI_A_SPI_initMasterParam::msbFirst, EUSCI_A_SPI_initMasterParam::selectClockSource, and EUSCI_A_SPI_initMasterParam::spiMode.
void EUSCI_A_SPI_initMaster (uint16_t baseAddress, EUSCI_A_SPI_initMasterParam * param)
Initializes the SPI Master block.
Upon successful initialization of the SPI master block, this function will have set the bus speed for the master, but the SPI Master block still remains disabled and must be enabled with EUSCI_A_SPI_enable()
Parameters
baseAddress is the base address of the EUSCI_A_SPI Master module.
param is the pointer to struct for master initialization.
Modified bits are UCCKPH, UCCKPL, UC7BIT, UCMSB, UCSSELx and UCSWRST of UCAxCTLW0 register.
Returns
STATUS_SUCCESS
References EUSCI_A_SPI_initMasterParam::clockPhase, EUSCI_A_SPI_initMasterParam::clockPolarity, EUSCI_A_SPI_initMasterParam::clockSourceFrequency, EUSCI_A_SPI_initMasterParam::desiredSpiClock, EUSCI_A_SPI_3PIN, EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_HIGH, EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_LOW, EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH, EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW, EUSCI_A_SPI_CLOCKSOURCE_ACLK, EUSCI_A_SPI_CLOCKSOURCE_SMCLK, EUSCI_A_SPI_LSB_FIRST, EUSCI_A_SPI_MSB_FIRST, EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT, EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT, HWREG16, EUSCI_A_SPI_initMasterParam::msbFirst, OFS_UCAxBRW, OFS_UCAxCTLW0, OFS_UCAxMCTLW, EUSCI_A_SPI_initMasterParam::selectClockSource, EUSCI_A_SPI_initMasterParam::spiMode, UC7BIT, UCCKPH, UCCKPL, UCMODE_3, UCMSB, UCMST, UCSSEL_3, UCSWRST, and UCSYNC.
Referenced by EUSCI_A_SPI_masterInit().
void EUSCI_A_SPI_select4PinFunctionality (uint16_t baseAddress, uint8_t select4PinFunctionality)
Selects 4Pin Functionality.
This function should be invoked only in 4-wire mode. Invoking this function has no effect in 3-wire mode.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
select4PinFunctionality selects 4 pin functionality Valid values are:
EUSCI_A_SPI_PREVENT_CONFLICTS_WITH_OTHER_MASTERS
EUSCI_A_SPI_ENABLE_SIGNAL_FOR_4WIRE_SLAVE
Modified bits are UCSTEM of UCAxCTLW0 register.
Returns
None
References EUSCI_A_SPI_ENABLE_SIGNAL_FOR_4WIRE_SLAVE, EUSCI_A_SPI_PREVENT_CONFLICTS_WITH_OTHER_MASTERS, HWREG16, OFS_UCAxCTLW0, and UCSTEM.
void EUSCI_A_SPI_masterChangeClock (uint16_t baseAddress, uint32_t clockSourceFrequency, uint32_t desiredSpiClock)
DEPRECATED - Initializes the SPI Master clock. At the end of this function call, SPI module is left enabled.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
clockSourceFrequency is the frequency of the selected clock source
desiredSpiClock is the desired clock rate for SPI communication
Modified bits are UCSWRST of UCAxCTLW0 register.
Returns
None
References EUSCI_A_SPI_changeMasterClockParam::clockSourceFrequency, EUSCI_A_SPI_changeMasterClockParam::desiredSpiClock, and EUSCI_A_SPI_changeMasterClock().
void EUSCI_A_SPI_changeMasterClock (uint16_t baseAddress, EUSCI_A_SPI_changeMasterClockParam * param)
Initializes the SPI Master clock. At the end of this function call, SPI module is left enabled.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
param is the pointer to struct for master clock setting.
Modified bits are UCSWRST of UCAxCTLW0 register.
Returns
None
References EUSCI_A_SPI_changeMasterClockParam::clockSourceFrequency, EUSCI_A_SPI_changeMasterClockParam::desiredSpiClock, HWREG16, OFS_UCAxBRW, OFS_UCAxCTLW0, and UCSWRST.
Referenced by EUSCI_A_SPI_masterChangeClock().
void EUSCI_A_SPI_slaveInit (uint16_t baseAddress, uint16_t msbFirst, uint16_t clockPhase, uint16_t clockPolarity, uint16_t spiMode)
DEPRECATED - Initializes the SPI Slave block.
Upon successful initialization of the SPI slave block, this function will have initialized the slave block, but the SPI Slave block still remains disabled and must be enabled with EUSCI_A_SPI_enable()
Parameters
baseAddress is the base address of the EUSCI_A_SPI Slave module.
msbFirst controls the direction of the receive and transmit shift register. Valid values are:
EUSCI_A_SPI_MSB_FIRST
EUSCI_A_SPI_LSB_FIRST [Default]
clockPhase is clock phase select. Valid values are:
EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT [Default]
EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT
clockPolarity is clock polarity select Valid values are:
EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH
EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW [Default]
spiMode is SPI mode select Valid values are:
EUSCI_A_SPI_3PIN
EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_HIGH
EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_LOW
Modified bits are UCMSB, UCMST, UC7BIT, UCCKPL, UCCKPH, UCMODE and UCSWRST of UCAxCTLW0 register.
Returns
STATUS_SUCCESS
References EUSCI_A_SPI_initSlaveParam::clockPhase, EUSCI_A_SPI_initSlaveParam::clockPolarity, EUSCI_A_SPI_initSlave(), EUSCI_A_SPI_initSlaveParam::msbFirst, and EUSCI_A_SPI_initSlaveParam::spiMode.
void EUSCI_A_SPI_initSlave (uint16_t baseAddress, EUSCI_A_SPI_initSlaveParam * param)
Initializes the SPI Slave block.
Upon successful initialization of the SPI slave block, this function will have initialized the slave block, but the SPI Slave block still remains disabled and must be enabled with EUSCI_A_SPI_enable()
Parameters
baseAddress is the base address of the EUSCI_A_SPI Slave module.
param is the pointer to struct for slave initialization.
Modified bits are UCMSB, UCMST, UC7BIT, UCCKPL, UCCKPH, UCMODE and UCSWRST of UCAxCTLW0 register.
Returns
STATUS_SUCCESS
References EUSCI_A_SPI_initSlaveParam::clockPhase, EUSCI_A_SPI_initSlaveParam::clockPolarity, EUSCI_A_SPI_3PIN, EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_HIGH, EUSCI_A_SPI_4PIN_UCxSTE_ACTIVE_LOW, EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH, EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW, EUSCI_A_SPI_LSB_FIRST, EUSCI_A_SPI_MSB_FIRST, EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT, EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT, HWREG16, EUSCI_A_SPI_initSlaveParam::msbFirst, OFS_UCAxCTLW0, EUSCI_A_SPI_initSlaveParam::spiMode, UC7BIT, UCCKPH, UCCKPL, UCMODE_3, UCMSB, UCMST, UCSWRST, and UCSYNC.
Referenced by EUSCI_A_SPI_slaveInit().
void EUSCI_A_SPI_changeClockPhasePolarity (uint16_t baseAddress, uint16_t clockPhase, uint16_t clockPolarity)
Changes the SPI clock phase and polarity. At the end of this function call, SPI module is left enabled.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
clockPhase is clock phase select. Valid values are:
EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT [Default]
EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT
clockPolarity is clock polarity select Valid values are:
EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH
EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW [Default]
Modified bits are UCCKPL, UCCKPH and UCSWRST of UCAxCTLW0 register.
Returns
None
References EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH, EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW, EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT, EUSCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT, HWREG16, OFS_UCAxCTLW0, UCCKPH, UCCKPL, and UCSWRST.
void EUSCI_A_SPI_transmitData (uint16_t baseAddress, uint8_t transmitData)
Transmits a byte from the SPI Module.
This function will place the supplied data into SPI transmit data register to start transmission.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
transmitData data to be transmitted from the SPI module
Returns
None
References HWREG16, and OFS_UCAxTXBUF.
uint8_t EUSCI_A_SPI_receiveData (uint16_t baseAddress)
Receives a byte that has been sent to the SPI Module.
This function reads a byte of data from the SPI receive data Register.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
Returns
Returns the byte received from by the SPI module, cast as an uint8_t.
References HWREG16, and OFS_UCAxRXBUF.
void EUSCI_A_SPI_enableInterrupt (uint16_t baseAddress, uint8_t mask)
Enables individual SPI interrupt sources.
Enables the indicated SPI interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
mask is the bit mask of the interrupt sources to be enabled. Mask value is the logical OR of any of the following:
EUSCI_A_SPI_TRANSMIT_INTERRUPT
EUSCI_A_SPI_RECEIVE_INTERRUPT
Modified bits of UCAxIFG register and bits of UCAxIE register.
Returns
None
References EUSCI_A_SPI_RECEIVE_INTERRUPT, EUSCI_A_SPI_TRANSMIT_INTERRUPT, HWREG16, and OFS_UCAxIE.
void EUSCI_A_SPI_disableInterrupt (uint16_t baseAddress, uint8_t mask)
Disables individual SPI interrupt sources.
Disables the indicated SPI interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
mask is the bit mask of the interrupt sources to be disabled. Mask value is the logical OR of any of the following:
EUSCI_A_SPI_TRANSMIT_INTERRUPT
EUSCI_A_SPI_RECEIVE_INTERRUPT
Modified bits of UCAxIE register.
Returns
None
References EUSCI_A_SPI_RECEIVE_INTERRUPT, EUSCI_A_SPI_TRANSMIT_INTERRUPT, HWREG16, and OFS_UCAxIE.
uint8_t EUSCI_A_SPI_getInterruptStatus (uint16_t baseAddress, uint8_t mask)
Gets the current SPI interrupt status.
This returns the interrupt status for the SPI module based on which flag is passed.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
mask is the masked interrupt flag status to be returned. Mask value is the logical OR of any of the following:
EUSCI_A_SPI_TRANSMIT_INTERRUPT
EUSCI_A_SPI_RECEIVE_INTERRUPT
Returns
Logical OR of any of the following:
EUSCI_A_SPI_TRANSMIT_INTERRUPT
EUSCI_A_SPI_RECEIVE_INTERRUPT
indicating the status of the masked interrupts
References EUSCI_A_SPI_RECEIVE_INTERRUPT, EUSCI_A_SPI_TRANSMIT_INTERRUPT, HWREG16, and OFS_UCAxIFG.
void EUSCI_A_SPI_clearInterruptFlag (uint16_t baseAddress, uint8_t mask)
Clears the selected SPI interrupt status flag.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
mask is the masked interrupt flag to be cleared. Mask value is the logical OR of any of the following:
EUSCI_A_SPI_TRANSMIT_INTERRUPT
EUSCI_A_SPI_RECEIVE_INTERRUPT
Modified bits of UCAxIFG register.
Returns
None
References EUSCI_A_SPI_RECEIVE_INTERRUPT, EUSCI_A_SPI_TRANSMIT_INTERRUPT, HWREG16, and OFS_UCAxIFG.
void EUSCI_A_SPI_enable (uint16_t baseAddress)
Enables the SPI block.
This will enable operation of the SPI block.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
Modified bits are UCSWRST of UCAxCTLW0 register.
Returns
None
References HWREG16, OFS_UCAxCTLW0, and UCSWRST.
void EUSCI_A_SPI_disable (uint16_t baseAddress)
Disables the SPI block.
This will disable operation of the SPI block.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
Modified bits are UCSWRST of UCAxCTLW0 register.
Returns
None
References HWREG16, OFS_UCAxCTLW0, and UCSWRST.
uint32_t EUSCI_A_SPI_getReceiveBufferAddress (uint16_t baseAddress)
Returns the address of the RX Buffer of the SPI for the DMA module.
Returns the address of the SPI RX Buffer. This can be used in conjunction with the DMA to store the received data directly to memory.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
Returns
the address of the RX Buffer
References OFS_UCAxRXBUF.
uint32_t EUSCI_A_SPI_getTransmitBufferAddress (uint16_t baseAddress)
Returns the address of the TX Buffer of the SPI for the DMA module.
Returns the address of the SPI TX Buffer. This can be used in conjunction with the DMA to obtain transmitted data directly from memory.
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
Returns
the address of the TX Buffer
References OFS_UCAxTXBUF.
uint16_t EUSCI_A_SPI_isBusy (uint16_t baseAddress)
Indicates whether or not the SPI bus is busy.
This function returns an indication of whether or not the SPI bus is busy.This function checks the status of the bus via UCBBUSY bit
Parameters
baseAddress is the base address of the EUSCI_A_SPI module.
Returns
One of the following:
EUSCI_A_SPI_BUSY
EUSCI_A_SPI_NOT_BUSY
indicating if the EUSCI_A_SPI is busy
References HWREG16, OFS_UCAxSTATW, and UCBUSY.
Copyright 2014, Texas Instruments Incorporated