Sd24_b_api
Sd24_b_api
Functions
void SD24_B_init (uint16_t baseAddress, uint16_t clockSourceSelect, uint16_t clockPreDivider, uint16_t clockDivider, uint16_t referenceSelect)
DEPRECATED - Initializes the SD24_B Module.
void SD24_B_initialize (uint16_t baseAddress, SD24_B_initializeParam *param)
Initializes the SD24_B Module.
void SD24_B_configureConverter (uint16_t baseAddress, uint8_t converter, uint8_t alignment, uint8_t startSelect, uint8_t conversionMode)
DEPRECATED - Configure SD24_B converter.
void SD24_B_initConverter (uint16_t baseAddress, SD24_B_initConverterParam *param)
Configure SD24_B converter.
void SD24_B_configureConverterAdvanced (uint16_t baseAddress, uint8_t converter, uint8_t alignment, uint8_t startSelect, uint8_t conversionMode, uint8_t dataFormat, uint8_t sampleDelay, uint16_t oversampleRatio, uint8_t gain)
DEPRECATED - Configure SD24_B converter - Advanced Configure.
void SD24_B_initConverterAdvanced (uint16_t baseAddress, SD24_B_initConverterAdvancedParam *param)
Configure SD24_B converter - Advanced Configure.
void SD24_B_setConverterDataFormat (uint16_t baseAddress, uint8_t converter, uint8_t dataFormat)
Set SD24_B converter data format.
void SD24_B_startGroupConversion (uint16_t baseAddress, uint8_t group)
Start Conversion Group.
void SD24_B_stopGroupConversion (uint16_t baseAddress, uint8_t group)
Stop Conversion Group.
void SD24_B_startConverterConversion (uint16_t baseAddress, uint8_t converter)
Start Conversion for Converter.
void SD24_B_stopConverterConversion (uint16_t baseAddress, uint8_t converter)
Stop Conversion for Converter.
void SD24_B_configureDMATrigger (uint16_t baseAddress, uint16_t interruptFlag)
Configures the converter that triggers a DMA transfer.
void SD24_B_setInterruptDelay (uint16_t baseAddress, uint8_t converter, uint8_t sampleDelay)
Configures the delay for an interrupt to trigger.
void SD24_B_setOversampling (uint16_t baseAddress, uint8_t converter, uint16_t oversampleRatio)
Configures the oversampling ratio for a converter.
void SD24_B_setGain (uint16_t baseAddress, uint8_t converter, uint8_t gain)
Configures the gain for the converter.
uint32_t SD24_B_getResults (uint16_t baseAddress, uint8_t converter)
Returns the results for a converter.
uint16_t SD24_B_getHighWordResults (uint16_t baseAddress, uint8_t converter)
Returns the high word results for a converter.
void SD24_B_enableInterrupt (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Enables interrupts for the SD24_B Module.
void SD24_B_disableInterrupt (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Disables interrupts for the SD24_B Module.
void SD24_B_clearInterrupt (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Clears interrupts for the SD24_B Module.
uint16_t SD24_B_getInterruptStatus (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Returns the interrupt status for the SD24_B Module.
Detailed Description
Function Documentation
void SD24_B_init (uint16_t baseAddress, uint16_t clockSourceSelect, uint16_t clockPreDivider, uint16_t clockDivider, uint16_t referenceSelect)
DEPRECATED - Initializes the SD24_B Module.
This function initializes the SD24_B module sigma-delta analog-to-digital conversions. Specifically the function sets up the clock source for the SD24_B core to use for conversions. Upon completion of the initialization the SD24_B interrupt registers will be reset and the given parameters will be set. The converter configuration settings are independent of this function. The values you choose for the clock divider and predivider are used to determine the effective clock frequency. The formula used is: f_sd24 = f_clk /(divider * predivider)
Parameters
baseAddress is the base address of the SD24_B module.
clockSourceSelect selects the clock that will be used as the SD24_B core Valid values are:
SD24_B_CLOCKSOURCE_MCLK [Default]
SD24_B_CLOCKSOURCE_SMCLK
SD24_B_CLOCKSOURCE_ACLK
SD24_B_CLOCKSOURCE_SD24CLK
Modified bits are SD24SSEL of SD24BCTL0 register.
clockPreDivider selects the amount that the clock will be predivided Valid values are:
SD24_B_PRECLOCKDIVIDER_1 [Default]
SD24_B_PRECLOCKDIVIDER_2
SD24_B_PRECLOCKDIVIDER_4
SD24_B_PRECLOCKDIVIDER_8
SD24_B_PRECLOCKDIVIDER_16
SD24_B_PRECLOCKDIVIDER_32
SD24_B_PRECLOCKDIVIDER_64
SD24_B_PRECLOCKDIVIDER_128
Modified bits are SD24PDIVx of SD24BCTL0 register.
clockDivider selects the amount that the clock will be divided. Valid values are:
SD24_B_CLOCKDIVIDER_1 [Default]
SD24_B_CLOCKDIVIDER_2
SD24_B_CLOCKDIVIDER_3
SD24_B_CLOCKDIVIDER_4
SD24_B_CLOCKDIVIDER_5
SD24_B_CLOCKDIVIDER_6
SD24_B_CLOCKDIVIDER_7
SD24_B_CLOCKDIVIDER_8
SD24_B_CLOCKDIVIDER_9
SD24_B_CLOCKDIVIDER_10
SD24_B_CLOCKDIVIDER_11
SD24_B_CLOCKDIVIDER_12
SD24_B_CLOCKDIVIDER_13
SD24_B_CLOCKDIVIDER_14
SD24_B_CLOCKDIVIDER_15
SD24_B_CLOCKDIVIDER_16
SD24_B_CLOCKDIVIDER_17
SD24_B_CLOCKDIVIDER_18
SD24_B_CLOCKDIVIDER_19
SD24_B_CLOCKDIVIDER_20
SD24_B_CLOCKDIVIDER_21
SD24_B_CLOCKDIVIDER_22
SD24_B_CLOCKDIVIDER_23
SD24_B_CLOCKDIVIDER_24
SD24_B_CLOCKDIVIDER_25
SD24_B_CLOCKDIVIDER_26
SD24_B_CLOCKDIVIDER_27
SD24_B_CLOCKDIVIDER_28
SD24_B_CLOCKDIVIDER_29
SD24_B_CLOCKDIVIDER_30
SD24_B_CLOCKDIVIDER_31
SD24_B_CLOCKDIVIDER_32
Modified bits are SD24DIVx of SD24BCTL0 register.
referenceSelect selects the reference source for the SD24_B core Valid values are:
SD24_B_REF_EXTERNAL [Default]
SD24_B_REF_INTERNAL
Modified bits are SD24REFS of SD24BCTL0 register.
Returns
None
References SD24_B_initializeParam::clockDivider, SD24_B_initializeParam::clockPreDivider, SD24_B_initializeParam::clockSourceSelect, SD24_B_initializeParam::referenceSelect, and SD24_B_initialize().
void SD24_B_initialize (uint16_t baseAddress, SD24_B_initializeParam * param)
Initializes the SD24_B Module.
This function initializes the SD24_B module sigma-delta analog-to-digital conversions. Specifically the function sets up the clock source for the SD24_B core to use for conversions. Upon completion of the initialization the SD24_B interrupt registers will be reset and the given parameters will be set. The converter configuration settings are independent of this function. The values you choose for the clock divider and predivider are used to determine the effective clock frequency. The formula used is: f_sd24 = f_clk /(divider * predivider)
Parameters
baseAddress is the base address of the SD24_B module.
param is the pointer to struct for initialization.
Returns
None
References SD24_B_initializeParam::clockDivider, SD24_B_initializeParam::clockPreDivider, SD24_B_initializeParam::clockSourceSelect, HWREG16, OFS_SD24BCTL0, OFS_SD24BCTL1, OFS_SD24BIE, OFS_SD24BIFG, OFS_SD24BTRGCTL, SD24_B_initializeParam::referenceSelect, SD24_B_CLOCKSOURCE_ACLK, SD24_B_CLOCKSOURCE_MCLK, SD24_B_CLOCKSOURCE_SD24CLK, SD24_B_CLOCKSOURCE_SMCLK, SD24_B_REF_EXTERNAL, SD24_B_REF_INTERNAL, SD24DIV0, SD24DIV1, SD24DIV2, SD24DIV3, SD24DIV4, SD24GRP0SC, SD24GRP1SC, SD24GRP2SC, SD24GRP3SC, SD24PDIV_7, SD24REFS, SD24SSEL_3, SD24TRGIE, and SD24TRGIFG.
Referenced by SD24_B_init().
void SD24_B_configureConverter (uint16_t baseAddress, uint8_t converter, uint8_t alignment, uint8_t startSelect, uint8_t conversionMode)
DEPRECATED - Configure SD24_B converter.
This function initializes a converter of the SD24_B module. Upon completion the converter will be ready for a conversion and can be started with the SD24_B_startGroupConversion() or SD24_B_startConverterConversion() depending on the startSelect parameter. Additional configuration such as data format can be configured in SD24_B_setConverterDataFormat().
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be configured. Check check datasheet for available converters on device. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
alignment selects how the data will be aligned in result Valid values are:
SD24_B_ALIGN_RIGHT [Default]
SD24_B_ALIGN_LEFT
Modified bits are SD24ALGN of SD24BCCTLx register.
startSelect selects what will trigger the start of the converter Valid values are:
SD24_B_CONVERSION_SELECT_SD24SC [Default]
SD24_B_CONVERSION_SELECT_EXT1
SD24_B_CONVERSION_SELECT_EXT2
SD24_B_CONVERSION_SELECT_EXT3
SD24_B_CONVERSION_SELECT_GROUP0
SD24_B_CONVERSION_SELECT_GROUP1
SD24_B_CONVERSION_SELECT_GROUP2
SD24_B_CONVERSION_SELECT_GROUP3
Modified bits are SD24SCSx of SD24BCCTLx register.
conversionMode determines whether the converter will do continuous samples or a single sample Valid values are:
SD24_B_CONTINUOUS_MODE [Default]
SD24_B_SINGLE_MODE
Modified bits are SD24SNGL of SD24BCCTLx register.
Returns
None
References SD24_B_initConverterParam::alignment, SD24_B_initConverterParam::conversionMode, SD24_B_initConverterParam::converter, SD24_B_initConverter(), and SD24_B_initConverterParam::startSelect.
void SD24_B_initConverter (uint16_t baseAddress, SD24_B_initConverterParam * param)
Configure SD24_B converter.
This function initializes a converter of the SD24_B module. Upon completion the converter will be ready for a conversion and can be started with the SD24_B_startGroupConversion() or SD24_B_startConverterConversion() depending on the startSelect parameter. Additional configuration such as data format can be configured in SD24_B_setConverterDataFormat().
Parameters
baseAddress is the base address of the SD24_B module.
param is the pointer to struct for converter configuration.
Returns
None
References SD24_B_initConverterParam::alignment, SD24_B_initConverterParam::conversionMode, SD24_B_initConverterParam::converter, HWREG16, OFS_SD24BCCTL0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, SD24ALGN, SD24SCS__GROUP3, SD24SNGL, and SD24_B_initConverterParam::startSelect.
Referenced by SD24_B_configureConverter().
void SD24_B_configureConverterAdvanced (uint16_t baseAddress, uint8_t converter, uint8_t alignment, uint8_t startSelect, uint8_t conversionMode, uint8_t dataFormat, uint8_t sampleDelay, uint16_t oversampleRatio, uint8_t gain)
DEPRECATED - Configure SD24_B converter - Advanced Configure.
This function initializes a converter of the SD24_B module. Upon completion the converter will be ready for a conversion and can be started with the SD24_B_startGroupConversion() or SD24_B_startConverterConversion() depending on the startSelect parameter.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be configured. Check check datasheet for available converters on device. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
alignment selects how the data will be aligned in result Valid values are:
SD24_B_ALIGN_RIGHT [Default]
SD24_B_ALIGN_LEFT
Modified bits are SD24ALGN of SD24BCCTLx register.
startSelect selects what will trigger the start of the converter Valid values are:
SD24_B_CONVERSION_SELECT_SD24SC [Default]
SD24_B_CONVERSION_SELECT_EXT1
SD24_B_CONVERSION_SELECT_EXT2
SD24_B_CONVERSION_SELECT_EXT3
SD24_B_CONVERSION_SELECT_GROUP0
SD24_B_CONVERSION_SELECT_GROUP1
SD24_B_CONVERSION_SELECT_GROUP2
SD24_B_CONVERSION_SELECT_GROUP3
Modified bits are SD24SCSx of SD24BCCTLx register.
conversionMode determines whether the converter will do continuous samples or a single sample Valid values are:
SD24_B_CONTINUOUS_MODE [Default]
SD24_B_SINGLE_MODE
Modified bits are SD24SNGL of SD24BCCTLx register.
dataFormat selects how the data format of the results Valid values are:
SD24_B_DATA_FORMAT_BINARY [Default]
SD24_B_DATA_FORMAT_2COMPLEMENT
Modified bits are SD24DFx of SD24BCCTLx register.
sampleDelay selects the delay for the interrupt Valid values are:
SD24_B_FOURTH_SAMPLE_INTERRUPT [Default]
SD24_B_THIRD_SAMPLE_INTERRUPT
SD24_B_SECOND_SAMPLE_INTERRUPT
SD24_B_FIRST_SAMPLE_INTERRUPT
Modified bits are SD24INTDLYx of SD24INCTLx register.
oversampleRatio selects oversampling ratio for the converter Valid values are:
SD24_B_OVERSAMPLE_32
SD24_B_OVERSAMPLE_64
SD24_B_OVERSAMPLE_128
SD24_B_OVERSAMPLE_256
SD24_B_OVERSAMPLE_512
SD24_B_OVERSAMPLE_1024
Modified bits are SD24OSRx of SD24BOSRx register.
gain selects the gain for the converter Valid values are:
SD24_B_GAIN_1 [Default]
SD24_B_GAIN_2
SD24_B_GAIN_4
SD24_B_GAIN_8
SD24_B_GAIN_16
SD24_B_GAIN_32
SD24_B_GAIN_64
SD24_B_GAIN_128
Modified bits are SD24GAINx of SD24BINCTLx register.
Returns
None
References SD24_B_initConverterAdvancedParam::alignment, SD24_B_initConverterAdvancedParam::conversionMode, SD24_B_initConverterAdvancedParam::converter, SD24_B_initConverterAdvancedParam::dataFormat, SD24_B_initConverterAdvancedParam::gain, SD24_B_initConverterAdvancedParam::oversampleRatio, SD24_B_initConverterAdvancedParam::sampleDelay, SD24_B_initConverterAdvanced(), and SD24_B_initConverterAdvancedParam::startSelect.
void SD24_B_initConverterAdvanced (uint16_t baseAddress, SD24_B_initConverterAdvancedParam * param)
Configure SD24_B converter - Advanced Configure.
This function initializes a converter of the SD24_B module. Upon completion the converter will be ready for a conversion and can be started with the SD24_B_startGroupConversion() or SD24_B_startConverterConversion() depending on the startSelect parameter.
Parameters
baseAddress is the base address of the SD24_B module.
param is the pointer to struct for converter advanced configuration.
Returns
None
References SD24_B_initConverterAdvancedParam::alignment, SD24_B_initConverterAdvancedParam::conversionMode, SD24_B_initConverterAdvancedParam::converter, SD24_B_initConverterAdvancedParam::dataFormat, SD24_B_initConverterAdvancedParam::gain, HWREG16, OFS_SD24BCCTL0, OFS_SD24BINCTL0, OFS_SD24BOSR0, OSR0, OSR1, OSR10, OSR2, OSR3, OSR4, OSR5, OSR6, OSR7, OSR8, OSR9, SD24_B_initConverterAdvancedParam::oversampleRatio, SD24_B_initConverterAdvancedParam::sampleDelay, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, SD24ALGN, SD24DF_0, SD24DF_1, SD24GAIN_128, SD24INTDLY_3, SD24SCS__GROUP3, SD24SNGL, and SD24_B_initConverterAdvancedParam::startSelect.
Referenced by SD24_B_configureConverterAdvanced().
void SD24_B_setConverterDataFormat (uint16_t baseAddress, uint8_t converter, uint8_t dataFormat)
Set SD24_B converter data format.
This function sets the converter format so that the resulting data can be viewed in either binary or 2's complement.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be configured. Check check datasheet for available converters on device. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
dataFormat selects how the data format of the results Valid values are:
SD24_B_DATA_FORMAT_BINARY [Default]
SD24_B_DATA_FORMAT_2COMPLEMENT
Modified bits are SD24DFx of SD24BCCTLx register.
Returns
None
References HWREG8, OFS_SD24BCCTL0_L, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, SD24DF0, and SD24DF1.
void SD24_B_startGroupConversion (uint16_t baseAddress, uint8_t group)
Start Conversion Group.
This function starts all the converters that are associated with a group. To set a converter to a group use the SD24_B_configureConverter() function.
Parameters
baseAddress is the base address of the SD24_B module.
group selects the group that will be started Valid values are:
SD24_B_GROUP0
SD24_B_GROUP1
SD24_B_GROUP2
SD24_B_GROUP3
Modified bits are SD24DGRPxSC of SD24BCTL1 register.
Returns
None
References HWREG16, OFS_SD24BCTL1, SD24_B_GROUP0, SD24_B_GROUP1, SD24_B_GROUP2, SD24_B_GROUP3, SD24GRP0SC, SD24GRP1SC, SD24GRP2SC, and SD24GRP3SC.
void SD24_B_stopGroupConversion (uint16_t baseAddress, uint8_t group)
Stop Conversion Group.
This function stops all the converters that are associated with a group. To set a converter to a group use the SD24_B_configureConverter() function.
Parameters
baseAddress is the base address of the SD24_B module.
group selects the group that will be stopped Valid values are:
SD24_B_GROUP0
SD24_B_GROUP1
SD24_B_GROUP2
SD24_B_GROUP3
Modified bits are SD24DGRPxSC of SD24BCTL1 register.
Returns
None
References HWREG16, OFS_SD24BCTL1, SD24_B_GROUP0, SD24_B_GROUP1, SD24_B_GROUP2, SD24_B_GROUP3, SD24GRP0SC, SD24GRP1SC, SD24GRP2SC, and SD24GRP3SC.
void SD24_B_startConverterConversion (uint16_t baseAddress, uint8_t converter)
Start Conversion for Converter.
This function starts a single converter.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be started Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
Modified bits are SD24SC of SD24BCCTLx register.
Returns
None
References HWREG16, OFS_SD24BCCTL0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, SD24SC, and SD24SCS_7.
void SD24_B_stopConverterConversion (uint16_t baseAddress, uint8_t converter)
Stop Conversion for Converter.
This function stops a single converter.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be stopped Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
Modified bits are SD24SC of SD24BCCTLx register.
Returns
None
References HWREG16, OFS_SD24BCCTL0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, SD24SC, and SD24SCS_7.
void SD24_B_configureDMATrigger (uint16_t baseAddress, uint16_t interruptFlag)
Configures the converter that triggers a DMA transfer.
This function chooses which interrupt will trigger a DMA transfer.
Parameters
baseAddress is the base address of the SD24_B module.
interruptFlag selects the converter interrupt that triggers a DMA transfer. Valid values are:
SD24_B_DMA_TRIGGER_IFG0
SD24_B_DMA_TRIGGER_IFG1
SD24_B_DMA_TRIGGER_IFG2
SD24_B_DMA_TRIGGER_IFG3
SD24_B_DMA_TRIGGER_IFG4
SD24_B_DMA_TRIGGER_IFG5
SD24_B_DMA_TRIGGER_IFG6
SD24_B_DMA_TRIGGER_IFG7
SD24_B_DMA_TRIGGER_TRGIFG
Modified bits are SD24DMAx of SD24BCTL1 register.
Returns
None
References HWREG16, OFS_SD24BCTL1, SD24DMA_0, SD24DMA_1, SD24DMA_2, and SD24DMA_3.
void SD24_B_setInterruptDelay (uint16_t baseAddress, uint8_t converter, uint8_t sampleDelay)
Configures the delay for an interrupt to trigger.
This function configures the delay for the first interrupt service request for the corresponding converter. This feature delays the interrupt request for a completed conversion by up to four conversion cycles allowing the digital filter to settle prior to generating an interrupt request.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be stopped Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
sampleDelay selects the delay for the interrupt Valid values are:
SD24_B_FOURTH_SAMPLE_INTERRUPT [Default]
SD24_B_THIRD_SAMPLE_INTERRUPT
SD24_B_SECOND_SAMPLE_INTERRUPT
SD24_B_FIRST_SAMPLE_INTERRUPT
Modified bits are SD24INTDLYx of SD24INCTLx register.
Returns
None
References HWREG16, OFS_SD24BINCTL0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, and SD24INTDLY_3.
void SD24_B_setOversampling (uint16_t baseAddress, uint8_t converter, uint16_t oversampleRatio)
Configures the oversampling ratio for a converter.
This function configures the oversampling ratio for a given converter.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be configured Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
oversampleRatio selects oversampling ratio for the converter Valid values are:
SD24_B_OVERSAMPLE_32
SD24_B_OVERSAMPLE_64
SD24_B_OVERSAMPLE_128
SD24_B_OVERSAMPLE_256
SD24_B_OVERSAMPLE_512
SD24_B_OVERSAMPLE_1024
Modified bits are SD24OSRx of SD24BOSRx register.
Returns
None
References HWREG16, OFS_SD24BOSR0, OSR0, OSR1, OSR10, OSR2, OSR3, OSR4, OSR5, OSR6, OSR7, OSR8, OSR9, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
void SD24_B_setGain (uint16_t baseAddress, uint8_t converter, uint8_t gain)
Configures the gain for the converter.
This function configures the gain for a single converter.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter that will be configured Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
gain selects the gain for the converter Valid values are:
SD24_B_GAIN_1 [Default]
SD24_B_GAIN_2
SD24_B_GAIN_4
SD24_B_GAIN_8
SD24_B_GAIN_16
SD24_B_GAIN_32
SD24_B_GAIN_64
SD24_B_GAIN_128
Modified bits are SD24GAINx of SD24BINCTLx register.
Returns
None
References HWREG16, OFS_SD24BINCTL0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, SD24_B_CONVERTER_7, and SD24GAIN_128.
uint32_t SD24_B_getResults (uint16_t baseAddress, uint8_t converter)
Returns the results for a converter.
This function gets the results from the SD24BMEMLx and SD24MEMHx registers and concatenates them to form a long. The actual result is a maximum 24 bits.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter who's results will be returned Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
Returns
Result of conversion
References HWREG16, OFS_SD24BMEML0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
uint16_t SD24_B_getHighWordResults (uint16_t baseAddress, uint8_t converter)
Returns the high word results for a converter.
This function gets the results from the SD24MEMHx register and returns it.
Parameters
baseAddress is the base address of the SD24_B module.
converter selects the converter who's results will be returned Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
Returns
Result of conversion
References HWREG16, OFS_SD24BMEMH0, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
void SD24_B_enableInterrupt (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Enables interrupts for the SD24_B Module.
This function enables interrupts for the SD24_B module. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the SD24_B module.
converter is the selected converter. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
mask is the bit mask of the converter interrupt sources to be enabled. Mask value is the logical OR of any of the following:
SD24_B_CONVERTER_INTERRUPT
SD24_B_CONVERTER_OVERFLOW_INTERRUPT
Modified bits are SD24OVIEx of SD24BIE register.
Returns
None
References HWREG16, OFS_SD24BIE, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
void SD24_B_disableInterrupt (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Disables interrupts for the SD24_B Module.
This function disables interrupts for the SD24_B module.
Parameters
baseAddress is the base address of the SD24_B module.
converter is the selected converter. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
mask is the bit mask of the converter interrupt sources to be disabled. Mask value is the logical OR of any of the following:
SD24_B_CONVERTER_INTERRUPT
SD24_B_CONVERTER_OVERFLOW_INTERRUPT
Modified bits are SD24OVIEx of SD24BIE register.
Modified bits of SD24BIE register.
Returns
None
References HWREG16, OFS_SD24BIE, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
void SD24_B_clearInterrupt (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Clears interrupts for the SD24_B Module.
This function clears interrupt flags for the SD24_B module.
Parameters
baseAddress is the base address of the SD24_B module.
converter is the selected converter. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
mask is the bit mask of the converter interrupt sources to clear. Mask value is the logical OR of any of the following:
SD24_B_CONVERTER_INTERRUPT
SD24_B_CONVERTER_OVERFLOW_INTERRUPT
Modified bits are SD24OVIFGx of SD24BIFG register.
Returns
None
References HWREG16, OFS_SD24BIFG, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
uint16_t SD24_B_getInterruptStatus (uint16_t baseAddress, uint8_t converter, uint16_t mask)
Returns the interrupt status for the SD24_B Module.
This function returns interrupt flag statuses for the SD24_B module.
Parameters
baseAddress is the base address of the SD24_B module.
converter is the selected converter. Valid values are:
SD24_B_CONVERTER_0
SD24_B_CONVERTER_1
SD24_B_CONVERTER_2
SD24_B_CONVERTER_3
SD24_B_CONVERTER_4
SD24_B_CONVERTER_5
SD24_B_CONVERTER_6
SD24_B_CONVERTER_7
mask is the bit mask of the converter interrupt sources to return. Mask value is the logical OR of any of the following:
SD24_B_CONVERTER_INTERRUPT
SD24_B_CONVERTER_OVERFLOW_INTERRUPT
Returns
Logical OR of any of the following:
SD24_B_CONVERTER_INTERRUPT
SD24_B_CONVERTER_OVERFLOW_INTERRUPT
indicating the status of the masked interrupts
References HWREG16, OFS_SD24BIFG, SD24_B_CONVERTER_0, SD24_B_CONVERTER_1, SD24_B_CONVERTER_2, SD24_B_CONVERTER_3, SD24_B_CONVERTER_4, SD24_B_CONVERTER_5, SD24_B_CONVERTER_6, and SD24_B_CONVERTER_7.
Copyright 2014, Texas Instruments Incorporated