Comp_b_api
Comp_b_api
Functions
bool COMP_B_init (uint16_t baseAddress, uint8_t positiveTerminalInput, uint8_t negativeTerminalInput, uint16_t powerModeSelect, uint8_t outputFilterEnableAndDelayLevel, uint16_t invertedOutputPolarity)
DEPRECATED - Initializes the COMP_B Module.
bool COMP_B_initialize (uint16_t baseAddress, COMP_B_initializeParam *param)
Initializes the COMP_B Module.
void COMP_B_setReferenceVoltage (uint16_t baseAddress, uint16_t supplyVoltageReferenceBase, uint16_t lowerLimitSupplyVoltageFractionOf32, uint16_t upperLimitSupplyVoltageFractionOf32, uint16_t referenceAccuracy)
DEPRECATED - Generates a Reference Voltage to the terminal selected during initialization.
void COMP_B_configureReferenceVoltage (uint16_t baseAddress, COMP_B_configureReferenceVoltageParam *param)
Generates a Reference Voltage to the terminal selected during initialization.
void COMP_B_enableInterrupt (uint16_t baseAddress, uint16_t interruptMask)
Enables selected COMP_B interrupt sources.
void COMP_B_disableInterrupt (uint16_t baseAddress, uint16_t interruptMask)
Disables selected COMP_B interrupt sources.
void COMP_B_clearInterrupt (uint16_t baseAddress, uint16_t interruptFlagMask)
Clears COMP_B interrupt flags.
uint8_t COMP_B_getInterruptStatus (uint16_t baseAddress, uint16_t interruptFlagMask)
Gets the current COMP_B interrupt status.
void COMP_B_interruptSetEdgeDirection (uint16_t baseAddress, uint16_t edgeDirection)
Explicitly sets the edge direction that would trigger an interrupt.
void COMP_B_interruptToggleEdgeDirection (uint16_t baseAddress)
Toggles the edge direction that would trigger an interrupt.
void COMP_B_enable (uint16_t baseAddress)
Turns on the COMP_B module.
void COMP_B_disable (uint16_t baseAddress)
Turns off the COMP_B module.
void COMP_B_shortInputs (uint16_t baseAddress)
Shorts the two input pins chosen during initialization.
void COMP_B_unshortInputs (uint16_t baseAddress)
Disables the short of the two input pins chosen during initialization.
void COMP_B_disableInputBuffer (uint16_t baseAddress, uint8_t inputPort)
Disables the input buffer of the selected input port to effectively allow for analog signals.
void COMP_B_enableInputBuffer (uint16_t baseAddress, uint8_t inputPort)
Enables the input buffer of the selected input port to allow for digital signals.
void COMP_B_IOSwap (uint16_t baseAddress)
Toggles the bit that swaps which terminals the inputs go to, while also inverting the output of the COMP_B.
uint16_t COMP_B_outputValue (uint16_t baseAddress)
Returns the output value of the COMP_B module.
Detailed Description
Function Documentation
bool COMP_B_init (uint16_t baseAddress, uint8_t positiveTerminalInput, uint8_t negativeTerminalInput, uint16_t powerModeSelect, uint8_t outputFilterEnableAndDelayLevel, uint16_t invertedOutputPolarity)
DEPRECATED - Initializes the COMP_B Module.
Upon successful initialization of the COMP_B module, this function will have reset all necessary register bits and set the given options in the registers. To actually use the COMP_B module, the COMP_B_enable() function must be explicitly called before use. If a Reference Voltage is set to a terminal, the Voltage should be set using the COMP_B_setReferenceVoltage() function.
Parameters
baseAddress is the base address of the COMP_B module.
positiveTerminalInput selects the input to the positive terminal. Valid values are:
COMP_B_INPUT0 [Default]
COMP_B_INPUT1
COMP_B_INPUT2
COMP_B_INPUT3
COMP_B_INPUT4
COMP_B_INPUT5
COMP_B_INPUT6
COMP_B_INPUT7
COMP_B_INPUT8
COMP_B_INPUT9
COMP_B_INPUT10
COMP_B_INPUT11
COMP_B_INPUT12
COMP_B_INPUT13
COMP_B_INPUT14
COMP_B_INPUT15
COMP_B_VREF
Modified bits are CBIPEN and CBIPSEL of CBCTL0 register; bits CBRSEL of CBCTL2 register; bits CBPDx of CBCTL3 register.
negativeTerminalInput selects the input to the negative terminal. Valid values are:
COMP_B_INPUT0 [Default]
COMP_B_INPUT1
COMP_B_INPUT2
COMP_B_INPUT3
COMP_B_INPUT4
COMP_B_INPUT5
COMP_B_INPUT6
COMP_B_INPUT7
COMP_B_INPUT8
COMP_B_INPUT9
COMP_B_INPUT10
COMP_B_INPUT11
COMP_B_INPUT12
COMP_B_INPUT13
COMP_B_INPUT14
COMP_B_INPUT15
COMP_B_VREF
Modified bits are CBIMEN and CBIMSEL of CBCTL0 register; bits CBRSEL of CBCTL2 register; bits CBPDx of CBCTL3 register.
powerModeSelect selects the power mode at which the COMP_B module will operate at. Valid values are:
COMP_B_POWERMODE_HIGHSPEED [Default]
COMP_B_POWERMODE_NORMALMODE
COMP_B_POWERMODE_ULTRALOWPOWER
Modified bits are CBWRMD of CBCTL1 register.
outputFilterEnableAndDelayLevel controls the output filter delay state, which is either off or enabled with a specified delay level. This parameter is device specific and delay levels should be found in the device's datasheet. Valid values are:
COMP_B_FILTEROUTPUT_OFF [Default]
COMP_B_FILTEROUTPUT_DLYLVL1
COMP_B_FILTEROUTPUT_DLYLVL2
COMP_B_FILTEROUTPUT_DLYLVL3
COMP_B_FILTEROUTPUT_DLYLVL4
Modified bits are CBFDLY and CBF of CBCTL1 register.
invertedOutputPolarity controls if the output will be inverted or not Valid values are:
COMP_B_NORMALOUTPUTPOLARITY [Default]
COMP_B_INVERTEDOUTPUTPOLARITY
Returns
STATUS_SUCCESS or STATUS_FAILURE of the initialization process.
References COMP_B_initialize(), COMP_B_initializeParam::invertedOutputPolarity, COMP_B_initializeParam::negativeTerminalInput, COMP_B_initializeParam::outputFilterEnableAndDelayLevel, COMP_B_initializeParam::positiveTerminalInput, and COMP_B_initializeParam::powerModeSelect.
bool COMP_B_initialize (uint16_t baseAddress, COMP_B_initializeParam * param)
Initializes the COMP_B Module.
Upon successful initialization of the COMP_B module, this function will have reset all necessary register bits and set the given options in the registers. To actually use the COMP_B module, the COMP_B_enable() function must be explicitly called before use. If a Reference Voltage is set to a terminal, the Voltage should be set using the COMP_B_setReferenceVoltage() function.
Parameters
baseAddress is the base address of the COMP_B module.
param is the pointer to struct for initialization.
Returns
STATUS_SUCCESS or STATUS_FAILURE of the initialization process.
References CBIMEN, CBIPEN, CBRSEL, COMP_B_FILTEROUTPUT_DLYLVL4, COMP_B_POWERMODE_ULTRALOWPOWER, COMP_B_VREF, HWREG16, COMP_B_initializeParam::invertedOutputPolarity, COMP_B_initializeParam::negativeTerminalInput, OFS_CBCTL0, OFS_CBCTL1, OFS_CBCTL2, OFS_CBCTL3, OFS_CBINT, COMP_B_initializeParam::outputFilterEnableAndDelayLevel, COMP_B_initializeParam::positiveTerminalInput, COMP_B_initializeParam::powerModeSelect, and STATUS_SUCCESS.
Referenced by COMP_B_init().
void COMP_B_setReferenceVoltage (uint16_t baseAddress, uint16_t supplyVoltageReferenceBase, uint16_t lowerLimitSupplyVoltageFractionOf32, uint16_t upperLimitSupplyVoltageFractionOf32, uint16_t referenceAccuracy)
DEPRECATED - Generates a Reference Voltage to the terminal selected during initialization.
Use this function to generate a voltage to serve as a reference to the terminal selected at initialization. The voltage is determined by the equation: Vbase * (Numerator / 32). If the upper and lower limit voltage numerators are equal, then a static reference is defined, whereas they are different then a hysteresis effect is generated.
Parameters
baseAddress is the base address of the COMP_B module.
supplyVoltageReferenceBase decides the source and max amount of Voltage that can be used as a reference. Valid values are:
COMP_B_VREFBASE_VCC
COMP_B_VREFBASE1_5V
COMP_B_VREFBASE2_0V
COMP_B_VREFBASE2_5V
Modified bits are CBREFL of CBCTL2 register.
lowerLimitSupplyVoltageFractionOf32 is the numerator of the equation to generate the reference voltage for the lower limit reference voltage.
Modified bits are CBREF0 of CBCTL2 register.
upperLimitSupplyVoltageFractionOf32 is the numerator of the equation to generate the reference voltage for the upper limit reference voltage.
Modified bits are CBREF1 of CBCTL2 register.
referenceAccuracy is the reference accuracy setting of the COMP_B. Clocked is for low power/low accuracy. Valid values are:
COMP_B_ACCURACY_STATIC
COMP_B_ACCURACY_CLOCKED
Modified bits are CDREFACC of CDCTL2 register.
Returns
None
References COMP_B_configureReferenceVoltage(), COMP_B_configureReferenceVoltageParam::lowerLimitSupplyVoltageFractionOf32, COMP_B_configureReferenceVoltageParam::referenceAccuracy, COMP_B_configureReferenceVoltageParam::supplyVoltageReferenceBase, and COMP_B_configureReferenceVoltageParam::upperLimitSupplyVoltageFractionOf32.
void COMP_B_configureReferenceVoltage (uint16_t baseAddress, COMP_B_configureReferenceVoltageParam * param)
Generates a Reference Voltage to the terminal selected during initialization.
Use this function to generate a voltage to serve as a reference to the terminal selected at initialization. The voltage is determined by the equation: Vbase * (Numerator / 32). If the upper and lower limit voltage numerators are equal, then a static reference is defined, whereas they are different then a hysteresis effect is generated.
Parameters
baseAddress is the base address of the COMP_B module.
param is the pointer to struct for reference voltage configuration.
Returns
None
References CBMRVS, CBREFACC, CBRS_1, CBRS_2, CBRS_3, CBRSEL, COMP_B_VREFBASE2_5V, COMP_B_VREFBASE_VCC, HWREG16, COMP_B_configureReferenceVoltageParam::lowerLimitSupplyVoltageFractionOf32, OFS_CBCTL1, OFS_CBCTL2, COMP_B_configureReferenceVoltageParam::referenceAccuracy, COMP_B_configureReferenceVoltageParam::supplyVoltageReferenceBase, and COMP_B_configureReferenceVoltageParam::upperLimitSupplyVoltageFractionOf32.
Referenced by COMP_B_setReferenceVoltage().
void COMP_B_enableInterrupt (uint16_t baseAddress, uint16_t interruptMask)
Enables selected COMP_B interrupt sources.
Enables the indicated COMP_B interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the COMP_B module.
interruptMask is the bit mask of the interrupt sources to be enabled. Mask value is the logical OR of any of the following:
COMP_B_OUTPUT_INT - Output interrupt
COMP_B_OUTPUTINVERTED_INT - Output interrupt inverted polarity
Modified bits of CBINT register.
Returns
None
References HWREG16, and OFS_CBINT.
void COMP_B_disableInterrupt (uint16_t baseAddress, uint16_t interruptMask)
Disables selected COMP_B interrupt sources.
Disables the indicated COMP_B interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the COMP_B module.
interruptMask is the bit mask of the interrupt sources to be disabled. Mask value is the logical OR of any of the following:
COMP_B_OUTPUT_INT - Output interrupt
COMP_B_OUTPUTINVERTED_INT - Output interrupt inverted polarity
Modified bits of CBINT register.
Returns
None
References HWREG16, and OFS_CBINT.
void COMP_B_clearInterrupt (uint16_t baseAddress, uint16_t interruptFlagMask)
Clears COMP_B interrupt flags.
The COMP_B interrupt source is cleared, so that it no longer asserts. The highest interrupt flag is automatically cleared when an interrupt vector generator is used.
Parameters
baseAddress is the base address of the COMP_B module.
interruptFlagMask is a bit mask of the interrupt sources to be cleared. Mask value is the logical OR of any of the following:
COMP_B_OUTPUT_FLAG - Output interrupt
COMP_B_OUTPUTINVERTED_FLAG - Output interrupt inverted polarity
Modified bits of CBINT register.
Returns
None
References HWREG16, and OFS_CBINT.
uint8_t COMP_B_getInterruptStatus (uint16_t baseAddress, uint16_t interruptFlagMask)
Gets the current COMP_B interrupt status.
This returns the interrupt status for the COMP_B module based on which flag is passed.
Parameters
baseAddress is the base address of the COMP_B module.
interruptFlagMask is the masked interrupt flag status to be returned. Mask value is the logical OR of any of the following:
COMP_B_OUTPUT_FLAG - Output interrupt
COMP_B_OUTPUTINVERTED_FLAG - Output interrupt inverted polarity
Returns
Logical OR of any of the following:
COMP_B_OUTPUT_FLAG Output interrupt
COMP_B_OUTPUTINVERTED_FLAG Output interrupt inverted polarity
indicating the status of the masked interrupts
References HWREG16, and OFS_CBINT.
void COMP_B_interruptSetEdgeDirection (uint16_t baseAddress, uint16_t edgeDirection)
Explicitly sets the edge direction that would trigger an interrupt.
This function will set which direction the output will have to go, whether rising or falling, to generate an interrupt based on a non-inverted interrupt.
Parameters
baseAddress is the base address of the COMP_B module.
edgeDirection determines which direction the edge would have to go to generate an interrupt based on the non-inverted interrupt flag. Valid values are:
COMP_B_FALLINGEDGE [Default] - sets the bit to generate an interrupt when the output of the COMP_B falls from HIGH to LOW if the normal interrupt bit is set(and LOW to HIGH if the inverted interrupt enable bit is set).
COMP_B_RISINGEDGE - sets the bit to generate an interrupt when the output of the COMP_B rises from LOW to HIGH if the normal interrupt bit is set(and HIGH to LOW if the inverted interrupt enable bit is set).
Modified bits are CBIES of CBCTL1 register.
Returns
None
References CBIES, COMP_B_FALLINGEDGE, COMP_B_RISINGEDGE, HWREG16, and OFS_CBCTL1.
void COMP_B_interruptToggleEdgeDirection (uint16_t baseAddress)
Toggles the edge direction that would trigger an interrupt.
This function will toggle which direction the output will have to go, whether rising or falling, to generate an interrupt based on a non-inverted interrupt. If the direction was rising, it is now falling, if it was falling, it is now rising.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
None
References CBIES, HWREG16, and OFS_CBCTL1.
void COMP_B_enable (uint16_t baseAddress)
Turns on the COMP_B module.
This function sets the bit that enables the operation of the COMP_B module.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
None
References CBON, HWREG16, and OFS_CBCTL1.
void COMP_B_disable (uint16_t baseAddress)
Turns off the COMP_B module.
This function clears the CBON bit disabling the operation of the COMP_B module, saving from excess power consumption.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
None
References CBON, HWREG16, and OFS_CBCTL1.
void COMP_B_shortInputs (uint16_t baseAddress)
Shorts the two input pins chosen during initialization.
This function sets the bit that shorts the devices attached to the input pins chosen from the initialization of the COMP_B.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
None
References CBSHORT, HWREG16, and OFS_CBCTL1.
void COMP_B_unshortInputs (uint16_t baseAddress)
Disables the short of the two input pins chosen during initialization.
This function clears the bit that shorts the devices attached to the input pins chosen from the initialization of the COMP_B.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
None
References CBSHORT, HWREG16, and OFS_CBCTL1.
void COMP_B_disableInputBuffer (uint16_t baseAddress, uint8_t inputPort)
Disables the input buffer of the selected input port to effectively allow for analog signals.
This function sets the bit to disable the buffer for the specified input port to allow for analog signals from any of the COMP_B input pins. This bit is automatically set when the input is initialized to be used with the COMP_B module. This function should be used whenever an analog input is connected to one of these pins to prevent parasitic voltage from causing unexpected results.
Parameters
baseAddress is the base address of the COMP_B module.
inputPort is the port in which the input buffer will be disabled. Valid values are:
COMP_B_INPUT0 [Default]
COMP_B_INPUT1
COMP_B_INPUT2
COMP_B_INPUT3
COMP_B_INPUT4
COMP_B_INPUT5
COMP_B_INPUT6
COMP_B_INPUT7
COMP_B_INPUT8
COMP_B_INPUT9
COMP_B_INPUT10
COMP_B_INPUT11
COMP_B_INPUT12
COMP_B_INPUT13
COMP_B_INPUT14
COMP_B_INPUT15
COMP_B_VREF
Modified bits are CBPDx of CBCTL3 register.
Returns
None
References COMP_B_INPUT15, HWREG16, and OFS_CBCTL3.
void COMP_B_enableInputBuffer (uint16_t baseAddress, uint8_t inputPort)
Enables the input buffer of the selected input port to allow for digital signals.
This function clears the bit to enable the buffer for the specified input port to allow for digital signals from any of the COMP_B input pins. This should not be reset if there is an analog signal connected to the specified input pin to prevent from unexpected results.
Parameters
baseAddress is the base address of the COMP_B module.
inputPort is the port in which the input buffer will be enabled. Valid values are:
COMP_B_INPUT0 [Default]
COMP_B_INPUT1
COMP_B_INPUT2
COMP_B_INPUT3
COMP_B_INPUT4
COMP_B_INPUT5
COMP_B_INPUT6
COMP_B_INPUT7
COMP_B_INPUT8
COMP_B_INPUT9
COMP_B_INPUT10
COMP_B_INPUT11
COMP_B_INPUT12
COMP_B_INPUT13
COMP_B_INPUT14
COMP_B_INPUT15
COMP_B_VREF
Modified bits are CBPDx of CBCTL3 register.
Returns
None
References COMP_B_INPUT15, HWREG16, and OFS_CBCTL3.
void COMP_B_IOSwap (uint16_t baseAddress)
Toggles the bit that swaps which terminals the inputs go to, while also inverting the output of the COMP_B.
This function toggles the bit that controls which input goes to which terminal. After initialization, this bit is set to 0, after toggling it once the inputs are routed to the opposite terminal and the output is inverted.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
None
References CBEX, HWREG16, and OFS_CBCTL1.
uint16_t COMP_B_outputValue (uint16_t baseAddress)
Returns the output value of the COMP_B module.
Returns the output value of the COMP_B module.
Parameters
baseAddress is the base address of the COMP_B module.
Returns
One of the following:
COMP_B_LOW
COMP_B_HIGH
indicating the output value of the COMP_B module
References CBOUT, HWREG16, and OFS_CBCTL1.
Copyright 2014, Texas Instruments Incorporated