Usci_a_spi_api
Usci_a_spi_api
Functions
bool USCI_A_SPI_masterInit (uint16_t baseAddress, uint8_t selectClockSource, uint32_t clockSourceFrequency, uint32_t desiredSpiClock, uint8_t msbFirst, uint8_t clockPhase, uint8_t clockPolarity)
DEPRECATED - Initializes the SPI Master block.
bool USCI_A_SPI_initMaster (uint16_t baseAddress, USCI_A_SPI_initMasterParam *param)
Initializes the SPI Master block.
void USCI_A_SPI_masterChangeClock (uint16_t baseAddress, uint32_t clockSourceFrequency, uint32_t desiredSpiClock)
DEPRECATED - Initializes the SPI Master clock.At the end of this function call, SPI module is left enabled.
void USCI_A_SPI_changeMasterClock (uint16_t baseAddress, USCI_A_SPI_changeMasterClockParam *param)
Initializes the SPI Master clock.At the end of this function call, SPI module is left enabled.
bool USCI_A_SPI_slaveInit (uint16_t baseAddress, uint8_t msbFirst, uint8_t clockPhase, uint8_t clockPolarity)
Initializes the SPI Slave block.
void USCI_A_SPI_changeClockPhasePolarity (uint16_t baseAddress, uint8_t clockPhase, uint8_t clockPolarity)
Changes the SPI clock phase and polarity.At the end of this function call, SPI module is left enabled.
void USCI_A_SPI_transmitData (uint16_t baseAddress, uint8_t transmitData)
Transmits a byte from the SPI Module.
uint8_t USCI_A_SPI_receiveData (uint16_t baseAddress)
Receives a byte that has been sent to the SPI Module.
void USCI_A_SPI_enableInterrupt (uint16_t baseAddress, uint8_t mask)
Enables individual SPI interrupt sources.
void USCI_A_SPI_disableInterrupt (uint16_t baseAddress, uint8_t mask)
Disables individual SPI interrupt sources.
uint8_t USCI_A_SPI_getInterruptStatus (uint16_t baseAddress, uint8_t mask)
Gets the current SPI interrupt status.
void USCI_A_SPI_clearInterruptFlag (uint16_t baseAddress, uint8_t mask)
Clears the selected SPI interrupt status flag.
void USCI_A_SPI_enable (uint16_t baseAddress)
Enables the SPI block.
void USCI_A_SPI_disable (uint16_t baseAddress)
Disables the SPI block.
uint32_t USCI_A_SPI_getReceiveBufferAddressForDMA (uint16_t baseAddress)
Returns the address of the RX Buffer of the SPI for the DMA module.
uint32_t USCI_A_SPI_getTransmitBufferAddressForDMA (uint16_t baseAddress)
Returns the address of the TX Buffer of the SPI for the DMA module.
uint8_t USCI_A_SPI_isBusy (uint16_t baseAddress)
Indicates whether or not the SPI bus is busy.
Detailed Description
Function Documentation
bool USCI_A_SPI_masterInit (uint16_t baseAddress, uint8_t selectClockSource, uint32_t clockSourceFrequency, uint32_t desiredSpiClock, uint8_t msbFirst, uint8_t clockPhase, uint8_t clockPolarity)
DEPRECATED - Initializes the SPI Master block.
Upon successful initialization of the SPI master block, this function will have set the bus speed for the master, but the SPI Master block still remains disabled and must be enabled with USCI_A_SPI_enable()
Parameters
baseAddress is the base address of the I2C Master module.
selectClockSource selects Clock source. Valid values are:
USCI_A_SPI_CLOCKSOURCE_ACLK
USCI_A_SPI_CLOCKSOURCE_SMCLK
clockSourceFrequency is the frequency of the selected clock source
desiredSpiClock is the desired clock rate for SPI communication
msbFirst controls the direction of the receive and transmit shift register. Valid values are:
USCI_A_SPI_MSB_FIRST
USCI_A_SPI_LSB_FIRST [Default]
clockPhase is clock phase select. Valid values are:
USCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT [Default]
USCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT
clockPolarity Valid values are:
USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH
USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW [Default]
Modified bits are UCCKPH, UCCKPL, UC7BIT and UCMSB of UCAxCTL0 register; bits UCSSELx and UCSWRST of UCAxCTL1 register.
Returns
STATUS_SUCCESS
References USCI_A_SPI_initMasterParam::clockPhase, USCI_A_SPI_initMasterParam::clockPolarity, USCI_A_SPI_initMasterParam::clockSourceFrequency, USCI_A_SPI_initMasterParam::desiredSpiClock, USCI_A_SPI_initMasterParam::msbFirst, USCI_A_SPI_initMasterParam::selectClockSource, and USCI_A_SPI_initMaster().
bool USCI_A_SPI_initMaster (uint16_t baseAddress, USCI_A_SPI_initMasterParam * param)
Initializes the SPI Master block.
Upon successful initialization of the SPI master block, this function will have set the bus speed for the master, but the SPI Master block still remains disabled and must be enabled with USCI_A_SPI_enable()
Parameters
baseAddress is the base address of the I2C Master module.
param is the pointer to struct for master initialization.
Modified bits are UCCKPH, UCCKPL, UC7BIT and UCMSB of UCAxCTL0 register; bits UCSSELx and UCSWRST of UCAxCTL1 register.
Returns
STATUS_SUCCESS
References USCI_A_SPI_initMasterParam::clockPhase, USCI_A_SPI_initMasterParam::clockPolarity, USCI_A_SPI_initMasterParam::clockSourceFrequency, USCI_A_SPI_initMasterParam::desiredSpiClock, HWREG16, HWREG8, USCI_A_SPI_initMasterParam::msbFirst, OFS_UCAxBRW, OFS_UCAxCTL0, OFS_UCAxCTL1, OFS_UCAxMCTL, USCI_A_SPI_initMasterParam::selectClockSource, STATUS_SUCCESS, UC7BIT, UCCKPH, UCCKPL, UCMODE_0, UCMODE_3, UCMSB, UCMST, UCSSEL_3, UCSWRST, UCSYNC, USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH, USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW, USCI_A_SPI_CLOCKSOURCE_ACLK, USCI_A_SPI_CLOCKSOURCE_SMCLK, USCI_A_SPI_LSB_FIRST, USCI_A_SPI_MSB_FIRST, USCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT, and USCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT.
Referenced by USCI_A_SPI_masterInit().
void USCI_A_SPI_masterChangeClock (uint16_t baseAddress, uint32_t clockSourceFrequency, uint32_t desiredSpiClock)
DEPRECATED - Initializes the SPI Master clock.At the end of this function call, SPI module is left enabled.
Parameters
baseAddress is the base address of the I2C Master module.
clockSourceFrequency is the frequency of the selected clock source
desiredSpiClock is the desired clock rate for SPI communication
Modified bits of UCAxBRW register.
Returns
None
References USCI_A_SPI_ChangeMasterClockParam::clockSourceFrequency, USCI_A_SPI_ChangeMasterClockParam::desiredSpiClock, and USCI_A_SPI_changeMasterClock().
void USCI_A_SPI_changeMasterClock (uint16_t baseAddress, USCI_A_SPI_changeMasterClockParam * param)
Initializes the SPI Master clock.At the end of this function call, SPI module is left enabled.
Parameters
baseAddress is the base address of the I2C Master module.
param is the pointer to struct for master clock setting.
Modified bits of UCAxBRW register.
Returns
None
References USCI_A_SPI_ChangeMasterClockParam::clockSourceFrequency, USCI_A_SPI_ChangeMasterClockParam::desiredSpiClock, HWREG8, OFS_UCAxBRW, OFS_UCAxCTL1, and UCSWRST.
Referenced by USCI_A_SPI_masterChangeClock().
bool USCI_A_SPI_slaveInit (uint16_t baseAddress, uint8_t msbFirst, uint8_t clockPhase, uint8_t clockPolarity)
Initializes the SPI Slave block.
Upon successful initialization of the SPI slave block, this function will have initialized the slave block, but the SPI Slave block still remains disabled and must be enabled with USCI_A_SPI_enable()
Parameters
baseAddress is the base address of the SPI Slave module.
msbFirst controls the direction of the receive and transmit shift register. Valid values are:
USCI_A_SPI_MSB_FIRST
USCI_A_SPI_LSB_FIRST [Default]
clockPhase is clock phase select. Valid values are:
USCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT [Default]
USCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT
clockPolarity Valid values are:
USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH
USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW [Default]
Modified bits are UCMSB, UCMST, UC7BIT, UCCKPL, UCCKPH and UCMODE of UCAxCTL0 register; bits UCSWRST of UCAxCTL1 register.
Returns
STATUS_SUCCESS
References HWREG8, OFS_UCAxCTL0, OFS_UCAxCTL1, STATUS_SUCCESS, UC7BIT, UCCKPH, UCCKPL, UCMODE_0, UCMODE_3, UCMSB, UCMST, UCSWRST, UCSYNC, USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH, USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW, USCI_A_SPI_LSB_FIRST, USCI_A_SPI_MSB_FIRST, USCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT, and USCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT.
void USCI_A_SPI_changeClockPhasePolarity (uint16_t baseAddress, uint8_t clockPhase, uint8_t clockPolarity)
Changes the SPI clock phase and polarity.At the end of this function call, SPI module is left enabled.
Parameters
baseAddress is the base address of the I2C Master module.
clockPhase is clock phase select. Valid values are:
USCI_A_SPI_PHASE_DATA_CHANGED_ONFIRST_CAPTURED_ON_NEXT [Default]
USCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT
clockPolarity Valid values are:
USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH
USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW [Default]
Modified bits are UCCKPL and UCCKPH of UCAxCTL0 register.
Returns
None
References HWREG8, OFS_UCAxCTL0, OFS_UCAxCTL1, UCCKPH, UCCKPL, UCSWRST, USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_HIGH, and USCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW.
void USCI_A_SPI_transmitData (uint16_t baseAddress, uint8_t transmitData)
Transmits a byte from the SPI Module.
This function will place the supplied data into SPI transmit data register to start transmission
Parameters
baseAddress is the base address of the SPI module.
transmitData data to be transmitted from the SPI module
Returns
None
References HWREG8, and OFS_UCAxTXBUF.
uint8_t USCI_A_SPI_receiveData (uint16_t baseAddress)
Receives a byte that has been sent to the SPI Module.
This function reads a byte of data from the SPI receive data Register.
Parameters
baseAddress is the base address of the SPI module.
Returns
Returns the byte received from by the SPI module, cast as an uint8_t.
References HWREG8, and OFS_UCAxRXBUF.
void USCI_A_SPI_enableInterrupt (uint16_t baseAddress, uint8_t mask)
Enables individual SPI interrupt sources.
Enables the indicated SPI interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor. Does not clear interrupt flags.
Parameters
baseAddress is the base address of the SPI module.
mask is the bit mask of the interrupt sources to be enabled. Mask value is the logical OR of any of the following:
USCI_A_SPI_TRANSMIT_INTERRUPT
USCI_A_SPI_RECEIVE_INTERRUPT
Modified bits of UCAxIE register.
Returns
None
References HWREG8, OFS_UCAxIE, USCI_A_SPI_RECEIVE_INTERRUPT, and USCI_A_SPI_TRANSMIT_INTERRUPT.
void USCI_A_SPI_disableInterrupt (uint16_t baseAddress, uint8_t mask)
Disables individual SPI interrupt sources.
Disables the indicated SPI interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
Parameters
baseAddress is the base address of the SPI module.
mask is the bit mask of the interrupt sources to be disabled. Mask value is the logical OR of any of the following:
USCI_A_SPI_TRANSMIT_INTERRUPT
USCI_A_SPI_RECEIVE_INTERRUPT
Modified bits of UCAxIE register.
Returns
None
References HWREG8, OFS_UCAxIE, USCI_A_SPI_RECEIVE_INTERRUPT, and USCI_A_SPI_TRANSMIT_INTERRUPT.
uint8_t USCI_A_SPI_getInterruptStatus (uint16_t baseAddress, uint8_t mask)
Gets the current SPI interrupt status.
This returns the interrupt status for the SPI module based on which flag is passed.
Parameters
baseAddress is the base address of the SPI module.
mask is the masked interrupt flag status to be returned. Mask value is the logical OR of any of the following:
USCI_A_SPI_TRANSMIT_INTERRUPT
USCI_A_SPI_RECEIVE_INTERRUPT
Returns
The current interrupt status as the mask of the set flags Return Logical OR of any of the following:
USCI_A_SPI_TRANSMIT_INTERRUPT
USCI_A_SPI_RECEIVE_INTERRUPT
indicating the status of the masked interrupts
References HWREG8, OFS_UCAxIFG, USCI_A_SPI_RECEIVE_INTERRUPT, and USCI_A_SPI_TRANSMIT_INTERRUPT.
void USCI_A_SPI_clearInterruptFlag (uint16_t baseAddress, uint8_t mask)
Clears the selected SPI interrupt status flag.
Parameters
baseAddress is the base address of the SPI module.
mask is the masked interrupt flag to be cleared. Mask value is the logical OR of any of the following:
USCI_A_SPI_TRANSMIT_INTERRUPT
USCI_A_SPI_RECEIVE_INTERRUPT
Modified bits of UCAxIFG register.
Returns
None
References HWREG8, OFS_UCAxIFG, USCI_A_SPI_RECEIVE_INTERRUPT, and USCI_A_SPI_TRANSMIT_INTERRUPT.
void USCI_A_SPI_enable (uint16_t baseAddress)
Enables the SPI block.
This will enable operation of the SPI block.
Parameters
baseAddress is the base address of the USCI SPI module.
Modified bits are UCSWRST of UCAxCTL1 register.
Returns
None
References HWREG8, OFS_UCAxCTL1, and UCSWRST.
void USCI_A_SPI_disable (uint16_t baseAddress)
Disables the SPI block.
This will disable operation of the SPI block.
Parameters
baseAddress is the base address of the USCI SPI module.
Modified bits are UCSWRST of UCAxCTL1 register.
Returns
None
References HWREG8, OFS_UCAxCTL1, and UCSWRST.
uint32_t USCI_A_SPI_getReceiveBufferAddressForDMA (uint16_t baseAddress)
Returns the address of the RX Buffer of the SPI for the DMA module.
Returns the address of the SPI RX Buffer. This can be used in conjunction with the DMA to store the received data directly to memory.
Parameters
baseAddress is the base address of the SPI module.
Returns
the address of the RX Buffer
References OFS_UCAxRXBUF.
uint32_t USCI_A_SPI_getTransmitBufferAddressForDMA (uint16_t baseAddress)
Returns the address of the TX Buffer of the SPI for the DMA module.
Returns the address of the SPI TX Buffer. This can be used in conjunction with the DMA to obtain transmitted data directly from memory.
Parameters
baseAddress is the base address of the SPI module.
Returns
the address of the TX Buffer
References OFS_UCAxTXBUF.
uint8_t USCI_A_SPI_isBusy (uint16_t baseAddress)
Indicates whether or not the SPI bus is busy.
This function returns an indication of whether or not the SPI bus is busy.This function checks the status of the bus via UCBBUSY bit
Parameters
baseAddress is the base address of the SPI module.
Returns
USCI_A_SPI_BUSY if the SPI module transmitting or receiving is busy; otherwise, returns USCI_A_SPI_NOT_BUSY. Return one of the following:
USCI_A_SPI_BUSY
USCI_A_SPI_NOT_BUSY
indicating if the USCI_A_SPI is busy
References HWREG8, OFS_UCAxSTAT, and UCBUSY.
Copyright 2014, Texas Instruments Incorporated