Timer_d_api
Timer_d_api
Functions
void TIMER_D_startCounter (uint16_t baseAddress, uint16_t timerMode)
Starts TIMER_D counter.
void TIMER_D_initContinuousMode (uint16_t baseAddress, TIMER_D_initContinuousModeParam *param)
Configures timer in continuous mode.
void TIMER_D_configureContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerInterruptEnable_TDIE, uint16_t timerClear)
DEPRECATED - Configures timer in continuous mode.
void TIMER_D_initUpMode (uint16_t baseAddress, TIMER_D_initUpModeParam *param)
Configures timer in up mode.
void TIMER_D_configureUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t timerInterruptEnable_TDIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures timer in up mode.
void TIMER_D_initUpDownMode (uint16_t baseAddress, TIMER_D_initUpDownModeParam *param)
Configures timer in up down mode.
void TIMER_D_configureUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t timerInterruptEnable_TDIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures timer in up down mode.
void TIMER_D_initCaptureMode (uint16_t baseAddress, TIMER_D_initCaptureModeParam *param)
Initializes Capture Mode.
void TIMER_D_initCapture (uint16_t baseAddress, uint16_t captureRegister, uint16_t captureMode, uint16_t captureInputSelect, uint16_t synchronizeCaptureSource, uint16_t captureInterruptEnable, uint16_t captureOutputMode, uint8_t channelCaptureMode)
DEPRECATED - Initializes Capture Mode.
void TIMER_D_initCompareMode (uint16_t baseAddress, TIMER_D_initCompareModeParam *param)
Initializes Compare Mode.
void TIMER_D_initCompare (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareInterruptEnable, uint16_t compareOutputMode, uint16_t compareValue)
DEPRECATED - Initializes Compare Mode.
void TIMER_D_enableTimerInterrupt (uint16_t baseAddress)
Enable timer interrupt.
void TIMER_D_enableHighResInterrupt (uint16_t baseAddress, uint16_t mask)
Enable High Resolution interrupt.
void TIMER_D_disableTimerInterrupt (uint16_t baseAddress)
Disable timer interrupt.
void TIMER_D_disableHighResInterrupt (uint16_t baseAddress, uint16_t mask)
Disable High Resolution interrupt.
uint32_t TIMER_D_getTimerInterruptStatus (uint16_t baseAddress)
Get timer interrupt status.
void TIMER_D_enableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Enable capture compare interrupt.
void TIMER_D_disableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Disable capture compare interrupt.
uint32_t TIMER_D_getCaptureCompareInterruptStatus (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t mask)
Return capture compare interrupt status.
uint16_t TIMER_D_getHighResInterruptStatus (uint16_t baseAddress, uint16_t mask)
Returns High Resolution interrupt status.
void TIMER_D_clear (uint16_t baseAddress)
Reset/Clear the timer clock divider, count direction, count.
void TIMER_D_clearHighResInterruptStatus (uint16_t baseAddress, uint16_t mask)
Clears High Resolution interrupt status.
uint8_t TIMER_D_getSynchronizedCaptureCompareInput (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t synchronized)
Get synchronized capturecompare input.
uint8_t TIMER_D_getOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister)
Get output bit for output mode.
uint16_t TIMER_D_getCaptureCompareCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare count.
uint16_t TIMER_D_getCaptureCompareLatchCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capture compare latch register count.
uint8_t TIMER_D_getCaptureCompareInputSignal (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare input signal.
void TIMER_D_setOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister, uint8_t outputModeOutBitValue)
Set output bit for output mode.
void TIMER_D_outputPWM (uint16_t baseAddress, TIMER_D_outputPWMParam *param)
Generate a PWM with timer running in up mode.
void TIMER_D_generatePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t compareRegister, uint16_t compareOutputMode, uint16_t dutyCycle)
DEPRECATED - Generate a PWM with timer running in up mode.
void TIMER_D_stop (uint16_t baseAddress)
Stops the timer.
void TIMER_D_setCompareValue (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareValue)
Sets the value of the capture-compare register.
void TIMER_D_clearTimerInterruptFlag (uint16_t baseAddress)
Clears the Timer TDIFG interrupt flag.
void TIMER_D_clearCaptureCompareInterruptFlag (uint16_t baseAddress, uint16_t captureCompareRegister)
Clears the capture-compare interrupt flag.
uint8_t TIMER_D_initHighResGeneratorInFreeRunningMode (uint16_t baseAddress, uint8_t desiredHighResFrequency)
Configures TIMER_D in free running mode.
void TIMER_D_initHighResGeneratorInRegulatedMode (uint16_t baseAddress, TIMER_D_initHighResGeneratorInRegulatedModeParam *param)
Configures TIMER_D in Regulated mode.
void TIMER_D_configureHighResGeneratorInRegulatedMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint8_t highResClockMultiplyFactor, uint8_t highResClockDivider)
DEPRECATED - Configures TIMER_D in Regulated mode.
void TIMER_D_combineTDCCRToOutputPWM (uint16_t baseAddress, TIMER_D_combineTDCCRToOutputPWMParam *param)
Combine TDCCR to get PWM.
void TIMER_D_combineTDCCRToGeneratePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t combineCCRRegistersCombination, uint16_t compareOutputMode, uint16_t dutyCycle1, uint16_t dutyCycle2)
DEPRECATED - Combine TDCCR to get PWM.
void TIMER_D_selectLatchingGroup (uint16_t baseAddress, uint16_t groupLatch)
Selects TIMER_D Latching Group.
void TIMER_D_selectCounterLength (uint16_t baseAddress, uint16_t counterLength)
Selects TIMER_D counter length.
void TIMER_D_initCompareLatchLoadEvent (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareLatchLoadEvent)
Selects Compare Latch Load Event.
void TIMER_D_disableHighResFastWakeup (uint16_t baseAddress)
Disable High Resolution fast wakeup.
void TIMER_D_enableHighResFastWakeup (uint16_t baseAddress)
Enable High Resolution fast wakeup.
void TIMER_D_disableHighResClockEnhancedAccuracy (uint16_t baseAddress)
Disable High Resolution Clock Enhanced Accuracy.
void TIMER_D_enableHighResClockEnhancedAccuracy (uint16_t baseAddress)
Enable High Resolution Clock Enhanced Accuracy.
void TIMER_D_DisableHighResGeneratorForceON (uint16_t baseAddress)
Disable High Resolution Clock Enhanced Accuracy.
void TIMER_D_EnableHighResGeneratorForceON (uint16_t baseAddress)
Enable High Resolution Clock Enhanced Accuracy.
void TIMER_D_selectHighResCoarseClockRange (uint16_t baseAddress, uint16_t highResCoarseClockRange)
Select High Resolution Coarse Clock Range.
void TIMER_D_selectHighResClockRange (uint16_t baseAddress, uint16_t highResClockRange)
Select High Resolution Clock Range Selection.
uint16_t TIMER_D_getCounterValue (uint16_t baseAddress)
Reads the current timer count value.
Detailed Description
Function Documentation
void TIMER_D_startCounter (uint16_t baseAddress, uint16_t timerMode)
Starts TIMER_D counter.
NOTE: This function assumes that the timer has been previously configured using TIMER_D_configureContinuousMode, TIMER_D_configureUpMode or TIMER_D_configureUpDownMode.
Parameters
baseAddress is the base address of the TIMER_DA module.
timerMode selects the mode of the timer Valid values are:
TIMER_D_STOP_MODE
TIMER_D_UP_MODE
TIMER_D_CONTINUOUS_MODE [Default]
TIMER_D_UPDOWN_MODE
Modified bits of TDxCTL0 register.
Returns
None
References HWREG16, OFS_TDxCTL0, TIMER_D_CONTINUOUS_MODE, TIMER_D_UP_MODE, and TIMER_D_UPDOWN_MODE.
void TIMER_D_initContinuousMode (uint16_t baseAddress, TIMER_D_initContinuousModeParam * param)
Configures timer in continuous mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_D_start API.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for continuous mode initialization.
Modified bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initContinuousModeParam::clockingMode, TIMER_D_initContinuousModeParam::clockSource, TIMER_D_initContinuousModeParam::clockSourceDivider, HWREG16, ID__8, OFS_TDxCTL0, OFS_TDxCTL1, TDCLKM0, TDCLKM1, TDIDEX_7, TIMER_D_CLOCKINGMODE_AUXILIARY_CLK, TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK, TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK, TIMER_D_CLOCKSOURCE_ACLK, TIMER_D_CLOCKSOURCE_DIVIDER_1, TIMER_D_CLOCKSOURCE_DIVIDER_10, TIMER_D_CLOCKSOURCE_DIVIDER_12, TIMER_D_CLOCKSOURCE_DIVIDER_14, TIMER_D_CLOCKSOURCE_DIVIDER_16, TIMER_D_CLOCKSOURCE_DIVIDER_2, TIMER_D_CLOCKSOURCE_DIVIDER_20, TIMER_D_CLOCKSOURCE_DIVIDER_24, TIMER_D_CLOCKSOURCE_DIVIDER_28, TIMER_D_CLOCKSOURCE_DIVIDER_3, TIMER_D_CLOCKSOURCE_DIVIDER_32, TIMER_D_CLOCKSOURCE_DIVIDER_4, TIMER_D_CLOCKSOURCE_DIVIDER_40, TIMER_D_CLOCKSOURCE_DIVIDER_48, TIMER_D_CLOCKSOURCE_DIVIDER_5, TIMER_D_CLOCKSOURCE_DIVIDER_56, TIMER_D_CLOCKSOURCE_DIVIDER_6, TIMER_D_CLOCKSOURCE_DIVIDER_64, TIMER_D_CLOCKSOURCE_DIVIDER_7, TIMER_D_CLOCKSOURCE_DIVIDER_8, TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_SMCLK, TIMER_D_DO_CLEAR, TIMER_D_SKIP_CLEAR, TIMER_D_TDIE_INTERRUPT_DISABLE, TIMER_D_TDIE_INTERRUPT_ENABLE, TIMER_D_UPDOWN_MODE, TIMER_D_initContinuousModeParam::timerClear, and TIMER_D_initContinuousModeParam::timerInterruptEnable_TDIE.
Referenced by TIMER_D_configureContinuousMode().
void TIMER_D_configureContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerInterruptEnable_TDIE, uint16_t timerClear)
DEPRECATED - Configures timer in continuous mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_D_start API.
Parameters
baseAddress is the base address of the TIMER_D module.
clockSource selects Clock source. Valid values are:
TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK [Default]
TIMER_D_CLOCKSOURCE_ACLK
TIMER_D_CLOCKSOURCE_SMCLK
TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK
clockSourceDivider is the divider for clock source. Valid values are:
TIMER_D_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_D_CLOCKSOURCE_DIVIDER_2
TIMER_D_CLOCKSOURCE_DIVIDER_3
TIMER_D_CLOCKSOURCE_DIVIDER_4
TIMER_D_CLOCKSOURCE_DIVIDER_5
TIMER_D_CLOCKSOURCE_DIVIDER_6
TIMER_D_CLOCKSOURCE_DIVIDER_7
TIMER_D_CLOCKSOURCE_DIVIDER_8
TIMER_D_CLOCKSOURCE_DIVIDER_10
TIMER_D_CLOCKSOURCE_DIVIDER_12
TIMER_D_CLOCKSOURCE_DIVIDER_14
TIMER_D_CLOCKSOURCE_DIVIDER_16
TIMER_D_CLOCKSOURCE_DIVIDER_20
TIMER_D_CLOCKSOURCE_DIVIDER_24
TIMER_D_CLOCKSOURCE_DIVIDER_28
TIMER_D_CLOCKSOURCE_DIVIDER_32
TIMER_D_CLOCKSOURCE_DIVIDER_40
TIMER_D_CLOCKSOURCE_DIVIDER_48
TIMER_D_CLOCKSOURCE_DIVIDER_56
TIMER_D_CLOCKSOURCE_DIVIDER_64
clockingMode is the selected clock mode register values. Valid values are:
TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK [Default]
TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK
TIMER_D_CLOCKINGMODE_AUXILIARY_CLK
timerInterruptEnable_TDIE is to enable or disable timer interrupt Valid values are:
TIMER_D_TDIE_INTERRUPT_ENABLE
TIMER_D_TDIE_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_D_DO_CLEAR
TIMER_D_SKIP_CLEAR [Default]
Modified bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initContinuousModeParam::clockingMode, TIMER_D_initContinuousModeParam::clockSource, TIMER_D_initContinuousModeParam::clockSourceDivider, TIMER_D_initContinuousMode(), TIMER_D_initContinuousModeParam::timerClear, and TIMER_D_initContinuousModeParam::timerInterruptEnable_TDIE.
void TIMER_D_initUpMode (uint16_t baseAddress, TIMER_D_initUpModeParam * param)
Configures timer in up mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_D_start API.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for up mode initialization.
Modified bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_D_initUpModeParam::clockingMode, TIMER_D_initUpModeParam::clockSource, TIMER_D_initUpModeParam::clockSourceDivider, HWREG16, ID__8, OFS_TDxCCR0, OFS_TDxCCTL0, OFS_TDxCTL0, OFS_TDxCTL1, TDCLKM0, TDCLKM1, TDIDEX_7, TIMER_D_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_D_CLOCKINGMODE_AUXILIARY_CLK, TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK, TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK, TIMER_D_CLOCKSOURCE_ACLK, TIMER_D_CLOCKSOURCE_DIVIDER_1, TIMER_D_CLOCKSOURCE_DIVIDER_10, TIMER_D_CLOCKSOURCE_DIVIDER_12, TIMER_D_CLOCKSOURCE_DIVIDER_14, TIMER_D_CLOCKSOURCE_DIVIDER_16, TIMER_D_CLOCKSOURCE_DIVIDER_2, TIMER_D_CLOCKSOURCE_DIVIDER_20, TIMER_D_CLOCKSOURCE_DIVIDER_24, TIMER_D_CLOCKSOURCE_DIVIDER_28, TIMER_D_CLOCKSOURCE_DIVIDER_3, TIMER_D_CLOCKSOURCE_DIVIDER_32, TIMER_D_CLOCKSOURCE_DIVIDER_4, TIMER_D_CLOCKSOURCE_DIVIDER_40, TIMER_D_CLOCKSOURCE_DIVIDER_48, TIMER_D_CLOCKSOURCE_DIVIDER_5, TIMER_D_CLOCKSOURCE_DIVIDER_56, TIMER_D_CLOCKSOURCE_DIVIDER_6, TIMER_D_CLOCKSOURCE_DIVIDER_64, TIMER_D_CLOCKSOURCE_DIVIDER_7, TIMER_D_CLOCKSOURCE_DIVIDER_8, TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_SMCLK, TIMER_D_DO_CLEAR, TIMER_D_SKIP_CLEAR, TIMER_D_STOP_MODE, TIMER_D_TDIE_INTERRUPT_ENABLE, TIMER_D_UPDOWN_MODE, TIMER_D_initUpModeParam::timerClear, TIMER_D_initUpModeParam::timerInterruptEnable_TDIE, and TIMER_D_initUpModeParam::timerPeriod.
Referenced by TIMER_D_configureUpMode().
void TIMER_D_configureUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t timerInterruptEnable_TDIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures timer in up mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_D_start API.
Parameters
baseAddress is the base address of the TIMER_D module.
clockSource selects Clock source. Valid values are:
TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK [Default]
TIMER_D_CLOCKSOURCE_ACLK
TIMER_D_CLOCKSOURCE_SMCLK
TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK
clockSourceDivider is the divider for clock source. Valid values are:
TIMER_D_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_D_CLOCKSOURCE_DIVIDER_2
TIMER_D_CLOCKSOURCE_DIVIDER_3
TIMER_D_CLOCKSOURCE_DIVIDER_4
TIMER_D_CLOCKSOURCE_DIVIDER_5
TIMER_D_CLOCKSOURCE_DIVIDER_6
TIMER_D_CLOCKSOURCE_DIVIDER_7
TIMER_D_CLOCKSOURCE_DIVIDER_8
TIMER_D_CLOCKSOURCE_DIVIDER_10
TIMER_D_CLOCKSOURCE_DIVIDER_12
TIMER_D_CLOCKSOURCE_DIVIDER_14
TIMER_D_CLOCKSOURCE_DIVIDER_16
TIMER_D_CLOCKSOURCE_DIVIDER_20
TIMER_D_CLOCKSOURCE_DIVIDER_24
TIMER_D_CLOCKSOURCE_DIVIDER_28
TIMER_D_CLOCKSOURCE_DIVIDER_32
TIMER_D_CLOCKSOURCE_DIVIDER_40
TIMER_D_CLOCKSOURCE_DIVIDER_48
TIMER_D_CLOCKSOURCE_DIVIDER_56
TIMER_D_CLOCKSOURCE_DIVIDER_64
clockingMode is the selected clock mode register values. Valid values are:
TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK [Default]
TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK
TIMER_D_CLOCKINGMODE_AUXILIARY_CLK
timerPeriod is the specified timer period. This is the value that gets written into the CCR0. Limited to 16 bits [uint16_t]
timerInterruptEnable_TDIE is to enable or disable timer interrupt Valid values are:
TIMER_D_TDIE_INTERRUPT_ENABLE
TIMER_D_TDIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable timer CCR0 captureComapre interrupt. Valid values are:
TIMER_D_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_D_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_D_DO_CLEAR
TIMER_D_SKIP_CLEAR [Default]
Modified bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_D_initUpModeParam::clockingMode, TIMER_D_initUpModeParam::clockSource, TIMER_D_initUpModeParam::clockSourceDivider, TIMER_D_initUpMode(), TIMER_D_initUpModeParam::timerClear, TIMER_D_initUpModeParam::timerInterruptEnable_TDIE, and TIMER_D_initUpModeParam::timerPeriod.
void TIMER_D_initUpDownMode (uint16_t baseAddress, TIMER_D_initUpDownModeParam * param)
Configures timer in up down mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_D_start API.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for up-down mode initialization.
Modified bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_D_initUpDownModeParam::clockingMode, TIMER_D_initUpDownModeParam::clockSource, TIMER_D_initUpDownModeParam::clockSourceDivider, HWREG16, ID__8, OFS_TDxCCR0, OFS_TDxCCTL0, OFS_TDxCTL0, OFS_TDxCTL1, TDCLKM0, TDCLKM1, TDIDEX_7, TIMER_D_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_D_CLOCKINGMODE_AUXILIARY_CLK, TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK, TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK, TIMER_D_CLOCKSOURCE_ACLK, TIMER_D_CLOCKSOURCE_DIVIDER_1, TIMER_D_CLOCKSOURCE_DIVIDER_10, TIMER_D_CLOCKSOURCE_DIVIDER_12, TIMER_D_CLOCKSOURCE_DIVIDER_14, TIMER_D_CLOCKSOURCE_DIVIDER_16, TIMER_D_CLOCKSOURCE_DIVIDER_2, TIMER_D_CLOCKSOURCE_DIVIDER_20, TIMER_D_CLOCKSOURCE_DIVIDER_24, TIMER_D_CLOCKSOURCE_DIVIDER_28, TIMER_D_CLOCKSOURCE_DIVIDER_3, TIMER_D_CLOCKSOURCE_DIVIDER_32, TIMER_D_CLOCKSOURCE_DIVIDER_4, TIMER_D_CLOCKSOURCE_DIVIDER_40, TIMER_D_CLOCKSOURCE_DIVIDER_48, TIMER_D_CLOCKSOURCE_DIVIDER_5, TIMER_D_CLOCKSOURCE_DIVIDER_56, TIMER_D_CLOCKSOURCE_DIVIDER_6, TIMER_D_CLOCKSOURCE_DIVIDER_64, TIMER_D_CLOCKSOURCE_DIVIDER_7, TIMER_D_CLOCKSOURCE_DIVIDER_8, TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_SMCLK, TIMER_D_DO_CLEAR, TIMER_D_SKIP_CLEAR, TIMER_D_STOP_MODE, TIMER_D_TDIE_INTERRUPT_ENABLE, TIMER_D_UPDOWN_MODE, TIMER_D_initUpDownModeParam::timerClear, TIMER_D_initUpDownModeParam::timerInterruptEnable_TDIE, and TIMER_D_initUpDownModeParam::timerPeriod.
Referenced by TIMER_D_configureUpDownMode().
void TIMER_D_configureUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t timerInterruptEnable_TDIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures timer in up down mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_D_start API.
Parameters
baseAddress is the base address of the TIMER_D module.
clockSource selects Clock source. Valid values are:
TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK [Default]
TIMER_D_CLOCKSOURCE_ACLK
TIMER_D_CLOCKSOURCE_SMCLK
TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK
clockSourceDivider is the divider for clock source. Valid values are:
TIMER_D_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_D_CLOCKSOURCE_DIVIDER_2
TIMER_D_CLOCKSOURCE_DIVIDER_3
TIMER_D_CLOCKSOURCE_DIVIDER_4
TIMER_D_CLOCKSOURCE_DIVIDER_5
TIMER_D_CLOCKSOURCE_DIVIDER_6
TIMER_D_CLOCKSOURCE_DIVIDER_7
TIMER_D_CLOCKSOURCE_DIVIDER_8
TIMER_D_CLOCKSOURCE_DIVIDER_10
TIMER_D_CLOCKSOURCE_DIVIDER_12
TIMER_D_CLOCKSOURCE_DIVIDER_14
TIMER_D_CLOCKSOURCE_DIVIDER_16
TIMER_D_CLOCKSOURCE_DIVIDER_20
TIMER_D_CLOCKSOURCE_DIVIDER_24
TIMER_D_CLOCKSOURCE_DIVIDER_28
TIMER_D_CLOCKSOURCE_DIVIDER_32
TIMER_D_CLOCKSOURCE_DIVIDER_40
TIMER_D_CLOCKSOURCE_DIVIDER_48
TIMER_D_CLOCKSOURCE_DIVIDER_56
TIMER_D_CLOCKSOURCE_DIVIDER_64
clockingMode is the selected clock mode register values. Valid values are:
TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK [Default]
TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK
TIMER_D_CLOCKINGMODE_AUXILIARY_CLK
timerPeriod is the specified timer period
timerInterruptEnable_TDIE is to enable or disable timer interrupt Valid values are:
TIMER_D_TDIE_INTERRUPT_ENABLE
TIMER_D_TDIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable timer CCR0 captureComapre interrupt. Valid values are:
TIMER_D_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_D_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_D_DO_CLEAR
TIMER_D_SKIP_CLEAR [Default]
Modified bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_D_initUpDownModeParam::clockingMode, TIMER_D_initUpDownModeParam::clockSource, TIMER_D_initUpDownModeParam::clockSourceDivider, TIMER_D_initUpDownMode(), TIMER_D_initUpDownModeParam::timerClear, TIMER_D_initUpDownModeParam::timerInterruptEnable_TDIE, and TIMER_D_initUpDownModeParam::timerPeriod.
void TIMER_D_initCaptureMode (uint16_t baseAddress, TIMER_D_initCaptureModeParam * param)
Initializes Capture Mode.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for capture mode initialization.
Modified bits of TDxCCTLn register and bits of TDxCTL2 register.
Returns
None
References CAP, TIMER_D_initCaptureModeParam::captureInputSelect, TIMER_D_initCaptureModeParam::captureInterruptEnable, TIMER_D_initCaptureModeParam::captureMode, TIMER_D_initCaptureModeParam::captureOutputMode, TIMER_D_initCaptureModeParam::captureRegister, TIMER_D_initCaptureModeParam::channelCaptureMode, CM_3, HWREG16, HWREG8, OFS_TDxCTL2, TIMER_D_initCaptureModeParam::synchronizeCaptureSource, TIMER_D_CAPTURE_ASYNCHRONOUS, TIMER_D_CAPTURE_INPUTSELECT_CCIxA, TIMER_D_CAPTURE_INPUTSELECT_CCIxB, TIMER_D_CAPTURE_INPUTSELECT_GND, TIMER_D_CAPTURE_INPUTSELECT_Vcc, TIMER_D_CAPTURE_SYNCHRONOUS, TIMER_D_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_D_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, TIMER_D_CAPTURECOMPARE_REGISTER_6, TIMER_D_CAPTUREMODE_FALLING_EDGE, TIMER_D_CAPTUREMODE_NO_CAPTURE, TIMER_D_CAPTUREMODE_RISING_AND_FALLING_EDGE, TIMER_D_CAPTUREMODE_RISING_EDGE, TIMER_D_DO_CLEAR, TIMER_D_DUAL_CAPTURE_MODE, TIMER_D_OUTPUTMODE_OUTBITVALUE, TIMER_D_OUTPUTMODE_RESET, TIMER_D_OUTPUTMODE_RESET_SET, TIMER_D_OUTPUTMODE_SET, TIMER_D_OUTPUTMODE_SET_RESET, TIMER_D_OUTPUTMODE_TOGGLE, TIMER_D_OUTPUTMODE_TOGGLE_RESET, TIMER_D_OUTPUTMODE_TOGGLE_SET, TIMER_D_SINGLE_CAPTURE_MODE, and TIMER_D_TDIE_INTERRUPT_ENABLE.
Referenced by TIMER_D_initCapture().
void TIMER_D_initCapture (uint16_t baseAddress, uint16_t captureRegister, uint16_t captureMode, uint16_t captureInputSelect, uint16_t synchronizeCaptureSource, uint16_t captureInterruptEnable, uint16_t captureOutputMode, uint8_t channelCaptureMode)
DEPRECATED - Initializes Capture Mode.
Parameters
baseAddress is the base address of the TIMER_D module.
captureRegister selects the Capture register being used. Refer to datasheet to ensure the device has the capture compare register being used Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
captureMode is the capture mode selected. Valid values are:
TIMER_D_CAPTUREMODE_NO_CAPTURE [Default]
TIMER_D_CAPTUREMODE_RISING_EDGE
TIMER_D_CAPTUREMODE_FALLING_EDGE
TIMER_D_CAPTUREMODE_RISING_AND_FALLING_EDGE
captureInputSelect decides the Input Select Valid values are:
TIMER_D_CAPTURE_INPUTSELECT_CCIxA [Default]
TIMER_D_CAPTURE_INPUTSELECT_CCIxB
TIMER_D_CAPTURE_INPUTSELECT_GND
TIMER_D_CAPTURE_INPUTSELECT_Vcc
synchronizeCaptureSource decides if capture source should be synchronized with timer clock Valid values are:
TIMER_D_CAPTURE_ASYNCHRONOUS [Default]
TIMER_D_CAPTURE_SYNCHRONOUS
Modified bits of TDxCCTLn register and bits of TDxCTL2 register.
Returns
None
References TIMER_D_initCaptureModeParam::captureInputSelect, TIMER_D_initCaptureModeParam::captureInterruptEnable, TIMER_D_initCaptureModeParam::captureMode, TIMER_D_initCaptureModeParam::captureOutputMode, TIMER_D_initCaptureModeParam::captureRegister, TIMER_D_initCaptureModeParam::channelCaptureMode, TIMER_D_initCaptureModeParam::synchronizeCaptureSource, and TIMER_D_initCaptureMode().
void TIMER_D_initCompareMode (uint16_t baseAddress, TIMER_D_initCompareModeParam * param)
Initializes Compare Mode.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for compare mode initialization.
Modified bits of TDxCCTLn register and bits of TDxCCRn register.
Returns
None
References CAP, TIMER_D_initCompareModeParam::compareInterruptEnable, TIMER_D_initCompareModeParam::compareOutputMode, TIMER_D_initCompareModeParam::compareRegister, TIMER_D_initCompareModeParam::compareValue, HWREG16, TIMER_D_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_D_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, TIMER_D_CAPTURECOMPARE_REGISTER_6, TIMER_D_OUTPUTMODE_OUTBITVALUE, TIMER_D_OUTPUTMODE_RESET, TIMER_D_OUTPUTMODE_RESET_SET, TIMER_D_OUTPUTMODE_SET, TIMER_D_OUTPUTMODE_SET_RESET, TIMER_D_OUTPUTMODE_TOGGLE, TIMER_D_OUTPUTMODE_TOGGLE_RESET, and TIMER_D_OUTPUTMODE_TOGGLE_SET.
Referenced by TIMER_D_initCompare().
void TIMER_D_initCompare (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareInterruptEnable, uint16_t compareOutputMode, uint16_t compareValue)
DEPRECATED - Initializes Compare Mode.
Parameters
baseAddress is the base address of the TIMER_D module.
compareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
compareInterruptEnable is to enable or disable timer captureComapre interrupt. Valid values are:
TIMER_D_CAPTURECOMPARE_INTERRUPT_ENABLE
TIMER_D_CAPTURECOMPARE_INTERRUPT_DISABLE [Default]
compareOutputMode specifies the output mode. Valid values are:
TIMER_D_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_D_OUTPUTMODE_SET
TIMER_D_OUTPUTMODE_TOGGLE_RESET
TIMER_D_OUTPUTMODE_SET_RESET
TIMER_D_OUTPUTMODE_TOGGLE
TIMER_D_OUTPUTMODE_RESET
TIMER_D_OUTPUTMODE_TOGGLE_SET
TIMER_D_OUTPUTMODE_RESET_SET
compareValue is the count to be compared with in compare mode
Modified bits of TDxCCTLn register and bits of TDxCCRn register.
Returns
None
References TIMER_D_initCompareModeParam::compareInterruptEnable, TIMER_D_initCompareModeParam::compareOutputMode, TIMER_D_initCompareModeParam::compareRegister, TIMER_D_initCompareModeParam::compareValue, and TIMER_D_initCompareMode().
void TIMER_D_enableTimerInterrupt (uint16_t baseAddress)
Enable timer interrupt.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits of TDxCTL0 register.
Returns
None
References HWREG8, OFS_TDxCTL0, TDIE, and TDIFG.
void TIMER_D_enableHighResInterrupt (uint16_t baseAddress, uint16_t mask)
Enable High Resolution interrupt.
Parameters
baseAddress is the base address of the TIMER_D module.
mask is the mask of interrupts to enable Mask value is the logical OR of any of the following:
TIMER_D_HIGH_RES_FREQUENCY_UNLOCK
TIMER_D_HIGH_RES_FREQUENCY_LOCK
TIMER_D_HIGH_RES_FAIL_HIGH
TIMER_D_HIGH_RES_FAIL_LOW
Modified bits of TDxHINT register.
Returns
None
References HWREG16, and OFS_TDxHINT.
void TIMER_D_disableTimerInterrupt (uint16_t baseAddress)
Disable timer interrupt.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits of TDxCTL0 register.
Returns
None
References HWREG8, OFS_TDxCTL0, and TDIE.
void TIMER_D_disableHighResInterrupt (uint16_t baseAddress, uint16_t mask)
Disable High Resolution interrupt.
Parameters
baseAddress is the base address of the TIMER_D module.
mask is the mask of interrupts to disable Mask value is the logical OR of any of the following:
TIMER_D_HIGH_RES_FREQUENCY_UNLOCK
TIMER_D_HIGH_RES_FREQUENCY_LOCK
TIMER_D_HIGH_RES_FAIL_HIGH
TIMER_D_HIGH_RES_FAIL_LOW
Modified bits of TDxHINT register.
Returns
None
References HWREG16, and OFS_TDxHINT.
uint32_t TIMER_D_getTimerInterruptStatus (uint16_t baseAddress)
Get timer interrupt status.
Parameters
baseAddress is the base address of the TIMER_D module.
Returns
One of the following:
TIMER_D_INTERRUPT_NOT_PENDING
TIMER_D_INTERRUPT_PENDING
indicating the timer interrupt status
References HWREG8, OFS_TDxCTL0, and TDIFG.
void TIMER_D_enableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Enable capture compare interrupt.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister is the selected capture compare register Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Modified bits of TDxCCTLn register.
Returns
None
References CCIE, CCIFG, HWREG16, HWREG8, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
void TIMER_D_disableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Disable capture compare interrupt.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister is the selected capture compare register Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Modified bits of TDxCCTLn register.
Returns
None
References CCIE, HWREG16, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
uint32_t TIMER_D_getCaptureCompareInterruptStatus (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t mask)
Return capture compare interrupt status.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister is the selected capture compare register Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
mask is the mask for the interrupt status Mask value is the logical OR of any of the following:
TIMER_D_CAPTURE_OVERFLOW
TIMER_D_CAPTURECOMPARE_INTERRUPT_FLAG
Returns
Logical OR of any of the following:
TIMER_D_CAPTURE_OVERFLOW
TIMER_D_CAPTURECOMPARE_INTERRUPT_FLAG
indicating the status of the masked flags
References HWREG16.
uint16_t TIMER_D_getHighResInterruptStatus (uint16_t baseAddress, uint16_t mask)
Returns High Resolution interrupt status.
Parameters
baseAddress is the base address of the TIMER_D module.
mask is the mask for the interrupt status Mask value is the logical OR of any of the following:
TIMER_D_HIGH_RES_FREQUENCY_UNLOCK
TIMER_D_HIGH_RES_FREQUENCY_LOCK
TIMER_D_HIGH_RES_FAIL_HIGH
TIMER_D_HIGH_RES_FAIL_LOW
Modified bits of TDxHINT register.
Returns
Logical OR of any of the following:
TIMER_D_HIGH_RES_FREQUENCY_UNLOCK
TIMER_D_HIGH_RES_FREQUENCY_LOCK
TIMER_D_HIGH_RES_FAIL_HIGH
TIMER_D_HIGH_RES_FAIL_LOW
indicating the status of the masked interrupts
References HWREG16, and OFS_TDxHINT.
void TIMER_D_clear (uint16_t baseAddress)
Reset/Clear the timer clock divider, count direction, count.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits of TDxCTL0 register.
Returns
None
References HWREG16, OFS_TDxCTL0, and TDCLR.
void TIMER_D_clearHighResInterruptStatus (uint16_t baseAddress, uint16_t mask)
Clears High Resolution interrupt status.
Parameters
baseAddress is the base address of the TIMER_D module.
mask is the mask for the interrupts to clear Mask value is the logical OR of any of the following:
TIMER_D_HIGH_RES_FREQUENCY_UNLOCK
TIMER_D_HIGH_RES_FREQUENCY_LOCK
TIMER_D_HIGH_RES_FAIL_HIGH
TIMER_D_HIGH_RES_FAIL_LOW
Modified bits of TDxHINT register.
Returns
None
References HWREG16, and OFS_TDxHINT.
uint8_t TIMER_D_getSynchronizedCaptureCompareInput (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t synchronized)
Get synchronized capturecompare input.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
synchronized is to select type of capture compare input. Valid values are:
TIMER_D_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT
TIMER_D_READ_CAPTURE_COMPARE_INPUT
Returns
One of the following:
TIMER_D_CAPTURECOMPARE_INPUT_HIGH
TIMER_D_CAPTURECOMPARE_INPUT_LOW
References HWREG16, TIMER_D_CAPTURECOMPARE_INPUT_HIGH, TIMER_D_CAPTURECOMPARE_INPUT_LOW, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, TIMER_D_CAPTURECOMPARE_REGISTER_6, TIMER_D_READ_CAPTURE_COMPARE_INPUT, and TIMER_D_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT.
uint8_t TIMER_D_getOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister)
Get output bit for output mode.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Returns
One of the following:
TIMER_D_OUTPUTMODE_OUTBITVALUE_HIGH
TIMER_D_OUTPUTMODE_OUTBITVALUE_LOW
References HWREG16, OUT, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, TIMER_D_CAPTURECOMPARE_REGISTER_6, TIMER_D_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_D_OUTPUTMODE_OUTBITVALUE_LOW.
uint16_t TIMER_D_getCaptureCompareCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare count.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Returns
current count as uint16_t
References HWREG16, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
uint16_t TIMER_D_getCaptureCompareLatchCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capture compare latch register count.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Returns
current count as uint16_t
References HWREG16, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
uint8_t TIMER_D_getCaptureCompareInputSignal (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare input signal.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Returns
One of the following:
TIMER_D_CAPTURECOMPARE_INPUT
0x00
indicating the current input signal
References CCI, HWREG8, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
void TIMER_D_setOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister, uint8_t outputModeOutBitValue)
Set output bit for output mode.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
outputModeOutBitValue the value to be set for out bit Valid values are:
TIMER_D_OUTPUTMODE_OUTBITVALUE_HIGH
TIMER_D_OUTPUTMODE_OUTBITVALUE_LOW
Modified bits of TDxCCTLn register.
Returns
None
References HWREG16, OUT, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, TIMER_D_CAPTURECOMPARE_REGISTER_6, TIMER_D_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_D_OUTPUTMODE_OUTBITVALUE_LOW.
void TIMER_D_outputPWM (uint16_t baseAddress, TIMER_D_outputPWMParam * param)
Generate a PWM with timer running in up mode.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for PWM configuration.
Modified bits of TDxCCTLn register, bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_outputPWMParam::clockingMode, TIMER_D_outputPWMParam::clockSource, TIMER_D_outputPWMParam::clockSourceDivider, TIMER_D_outputPWMParam::compareOutputMode, TIMER_D_outputPWMParam::compareRegister, TIMER_D_outputPWMParam::dutyCycle, HWREG16, ID__8, OFS_TDxCCR0, OFS_TDxCCTL0, OFS_TDxCTL0, OFS_TDxCTL1, TDCLKM0, TDCLKM1, TDIDEX_7, TIMER_D_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, TIMER_D_CAPTURECOMPARE_REGISTER_6, TIMER_D_CLOCKINGMODE_AUXILIARY_CLK, TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK, TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK, TIMER_D_CLOCKSOURCE_ACLK, TIMER_D_CLOCKSOURCE_DIVIDER_1, TIMER_D_CLOCKSOURCE_DIVIDER_10, TIMER_D_CLOCKSOURCE_DIVIDER_12, TIMER_D_CLOCKSOURCE_DIVIDER_14, TIMER_D_CLOCKSOURCE_DIVIDER_16, TIMER_D_CLOCKSOURCE_DIVIDER_2, TIMER_D_CLOCKSOURCE_DIVIDER_20, TIMER_D_CLOCKSOURCE_DIVIDER_24, TIMER_D_CLOCKSOURCE_DIVIDER_28, TIMER_D_CLOCKSOURCE_DIVIDER_3, TIMER_D_CLOCKSOURCE_DIVIDER_32, TIMER_D_CLOCKSOURCE_DIVIDER_4, TIMER_D_CLOCKSOURCE_DIVIDER_40, TIMER_D_CLOCKSOURCE_DIVIDER_48, TIMER_D_CLOCKSOURCE_DIVIDER_5, TIMER_D_CLOCKSOURCE_DIVIDER_56, TIMER_D_CLOCKSOURCE_DIVIDER_6, TIMER_D_CLOCKSOURCE_DIVIDER_64, TIMER_D_CLOCKSOURCE_DIVIDER_7, TIMER_D_CLOCKSOURCE_DIVIDER_8, TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_SMCLK, TIMER_D_DO_CLEAR, TIMER_D_OUTPUTMODE_OUTBITVALUE, TIMER_D_OUTPUTMODE_RESET, TIMER_D_OUTPUTMODE_RESET_SET, TIMER_D_OUTPUTMODE_SET, TIMER_D_OUTPUTMODE_SET_RESET, TIMER_D_OUTPUTMODE_TOGGLE, TIMER_D_OUTPUTMODE_TOGGLE_RESET, TIMER_D_OUTPUTMODE_TOGGLE_SET, TIMER_D_TDIE_INTERRUPT_ENABLE, TIMER_D_UP_MODE, TIMER_D_UPDOWN_MODE, and TIMER_D_outputPWMParam::timerPeriod.
Referenced by TIMER_D_generatePWM().
void TIMER_D_generatePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t compareRegister, uint16_t compareOutputMode, uint16_t dutyCycle)
DEPRECATED - Generate a PWM with timer running in up mode.
Parameters
baseAddress is the base address of the TIMER_D module.
clockSource selects Clock source. Valid values are:
TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK [Default]
TIMER_D_CLOCKSOURCE_ACLK
TIMER_D_CLOCKSOURCE_SMCLK
TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK
clockSourceDivider is the divider for clock source. Valid values are:
TIMER_D_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_D_CLOCKSOURCE_DIVIDER_2
TIMER_D_CLOCKSOURCE_DIVIDER_3
TIMER_D_CLOCKSOURCE_DIVIDER_4
TIMER_D_CLOCKSOURCE_DIVIDER_5
TIMER_D_CLOCKSOURCE_DIVIDER_6
TIMER_D_CLOCKSOURCE_DIVIDER_7
TIMER_D_CLOCKSOURCE_DIVIDER_8
TIMER_D_CLOCKSOURCE_DIVIDER_10
TIMER_D_CLOCKSOURCE_DIVIDER_12
TIMER_D_CLOCKSOURCE_DIVIDER_14
TIMER_D_CLOCKSOURCE_DIVIDER_16
TIMER_D_CLOCKSOURCE_DIVIDER_20
TIMER_D_CLOCKSOURCE_DIVIDER_24
TIMER_D_CLOCKSOURCE_DIVIDER_28
TIMER_D_CLOCKSOURCE_DIVIDER_32
TIMER_D_CLOCKSOURCE_DIVIDER_40
TIMER_D_CLOCKSOURCE_DIVIDER_48
TIMER_D_CLOCKSOURCE_DIVIDER_56
TIMER_D_CLOCKSOURCE_DIVIDER_64
clockingMode is the selected clock mode register values. Valid values are:
TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK [Default]
TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK
TIMER_D_CLOCKINGMODE_AUXILIARY_CLK
timerPeriod is the specified timer period
compareRegister selects the compare register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
compareOutputMode specifies the output mode. Valid values are:
TIMER_D_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_D_OUTPUTMODE_SET
TIMER_D_OUTPUTMODE_TOGGLE_RESET
TIMER_D_OUTPUTMODE_SET_RESET
TIMER_D_OUTPUTMODE_TOGGLE
TIMER_D_OUTPUTMODE_RESET
TIMER_D_OUTPUTMODE_TOGGLE_SET
TIMER_D_OUTPUTMODE_RESET_SET
dutyCycle specifies the dutycycle for the generated waveform
Modified bits of TDxCCTLn register, bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_outputPWMParam::clockingMode, TIMER_D_outputPWMParam::clockSource, TIMER_D_outputPWMParam::clockSourceDivider, TIMER_D_outputPWMParam::compareOutputMode, TIMER_D_outputPWMParam::compareRegister, TIMER_D_outputPWMParam::dutyCycle, TIMER_D_outputPWM(), and TIMER_D_outputPWMParam::timerPeriod.
void TIMER_D_stop (uint16_t baseAddress)
Stops the timer.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits of TDxCTL0 register.
Returns
None
References HWREG16, MC_0, MC_3, and OFS_TDxCTL0.
void TIMER_D_setCompareValue (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareValue)
Sets the value of the capture-compare register.
Parameters
baseAddress is the base address of the TIMER_D module.
compareRegister selects the Capture register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
compareValue is the count to be compared with in compare mode
Modified bits of TDxCCRn register.
Returns
None
References HWREG16, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
void TIMER_D_clearTimerInterruptFlag (uint16_t baseAddress)
Clears the Timer TDIFG interrupt flag.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDIFG of TDxCTL0 register.
Returns
None
References HWREG16, OFS_TDxCTL0, and TDIFG.
void TIMER_D_clearCaptureCompareInterruptFlag (uint16_t baseAddress, uint16_t captureCompareRegister)
Clears the capture-compare interrupt flag.
Parameters
baseAddress is the base address of the TIMER_D module.
captureCompareRegister selects the Capture-compare register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
Modified bits are CCIFG of TDxCCTLn register.
Returns
None
References CCIFG, HWREG16, TIMER_D_CAPTURECOMPARE_REGISTER_0, TIMER_D_CAPTURECOMPARE_REGISTER_1, TIMER_D_CAPTURECOMPARE_REGISTER_2, TIMER_D_CAPTURECOMPARE_REGISTER_3, TIMER_D_CAPTURECOMPARE_REGISTER_4, TIMER_D_CAPTURECOMPARE_REGISTER_5, and TIMER_D_CAPTURECOMPARE_REGISTER_6.
uint8_t TIMER_D_initHighResGeneratorInFreeRunningMode (uint16_t baseAddress, uint8_t desiredHighResFrequency)
Configures TIMER_D in free running mode.
Parameters
baseAddress is the base address of the TIMER_D module.
desiredHighResFrequency selects the desired High Resolution frequency used. Valid values are:
TIMER_D_HIGHRES_64MHZ
TIMER_D_HIGHRES_128MHZ
TIMER_D_HIGHRES_200MHZ
TIMER_D_HIGHRES_256MHZ
Modified bits of TDxHCTL1 register, bits of TDxHCTL0 register and bits of TDxCTL1 register.
Returns
STATUS_SUCCESS or STATUS_FAIL
References HWREG16, OFS_TDxCTL1, OFS_TDxHCTL0, OFS_TDxHCTL1, STATUS_FAIL, STATUS_SUCCESS, TDCLKM_1, s_TLV_Timer_D_Cal_Data::TDH0CTL1_128, s_TLV_Timer_D_Cal_Data::TDH0CTL1_200, s_TLV_Timer_D_Cal_Data::TDH0CTL1_256, s_TLV_Timer_D_Cal_Data::TDH0CTL1_64, TDHCLKTRIM6, TDHEN, TDHM_1, TIMER_D_HIGHRES_128MHZ, TIMER_D_HIGHRES_200MHZ, TIMER_D_HIGHRES_256MHZ, TIMER_D_HIGHRES_64MHZ, TLV_getInfo(), and TLV_TAG_TIMER_D_CAL.
void TIMER_D_initHighResGeneratorInRegulatedMode (uint16_t baseAddress, TIMER_D_initHighResGeneratorInRegulatedModeParam * param)
Configures TIMER_D in Regulated mode.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for high resolution generator in regulated mode.
Modified bits of TDxHCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initHighResGeneratorInRegulatedModeParam::clockingMode, TIMER_D_initHighResGeneratorInRegulatedModeParam::clockSource, TIMER_D_initHighResGeneratorInRegulatedModeParam::clockSourceDivider, TIMER_D_initHighResGeneratorInRegulatedModeParam::highResClockDivider, TIMER_D_initHighResGeneratorInRegulatedModeParam::highResClockMultiplyFactor, HWREG16, ID__8, OFS_TDxCTL0, OFS_TDxCTL1, OFS_TDxHCTL0, TDCLKM0, TDCLKM1, TDCLKM_1, TDCLR, TDHD_3, TDHEN, TDHREGEN, TDIDEX_7, TDSSEL_3, TIMER_D_CLOCKINGMODE_AUXILIARY_CLK, TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK, TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK, TIMER_D_CLOCKSOURCE_ACLK, TIMER_D_CLOCKSOURCE_DIVIDER_1, TIMER_D_CLOCKSOURCE_DIVIDER_10, TIMER_D_CLOCKSOURCE_DIVIDER_12, TIMER_D_CLOCKSOURCE_DIVIDER_14, TIMER_D_CLOCKSOURCE_DIVIDER_16, TIMER_D_CLOCKSOURCE_DIVIDER_2, TIMER_D_CLOCKSOURCE_DIVIDER_20, TIMER_D_CLOCKSOURCE_DIVIDER_24, TIMER_D_CLOCKSOURCE_DIVIDER_28, TIMER_D_CLOCKSOURCE_DIVIDER_3, TIMER_D_CLOCKSOURCE_DIVIDER_32, TIMER_D_CLOCKSOURCE_DIVIDER_4, TIMER_D_CLOCKSOURCE_DIVIDER_40, TIMER_D_CLOCKSOURCE_DIVIDER_48, TIMER_D_CLOCKSOURCE_DIVIDER_5, TIMER_D_CLOCKSOURCE_DIVIDER_56, TIMER_D_CLOCKSOURCE_DIVIDER_6, TIMER_D_CLOCKSOURCE_DIVIDER_64, TIMER_D_CLOCKSOURCE_DIVIDER_7, TIMER_D_CLOCKSOURCE_DIVIDER_8, TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_SMCLK, TIMER_D_HIGHRES_CLK_DIVIDER_1, TIMER_D_HIGHRES_CLK_DIVIDER_2, TIMER_D_HIGHRES_CLK_DIVIDER_4, TIMER_D_HIGHRES_CLK_DIVIDER_8, TIMER_D_HIGHRES_CLK_MULTIPLY_FACTOR_16x, and TIMER_D_HIGHRES_CLK_MULTIPLY_FACTOR_8x.
Referenced by TIMER_D_configureHighResGeneratorInRegulatedMode().
void TIMER_D_configureHighResGeneratorInRegulatedMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint8_t highResClockMultiplyFactor, uint8_t highResClockDivider)
DEPRECATED - Configures TIMER_D in Regulated mode.
Parameters
baseAddress is the base address of the TIMER_D module.
clockSource selects Clock source. Valid values are:
TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK [Default]
TIMER_D_CLOCKSOURCE_ACLK
TIMER_D_CLOCKSOURCE_SMCLK
TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK
clockSourceDivider is the divider for clock source. Valid values are:
TIMER_D_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_D_CLOCKSOURCE_DIVIDER_2
TIMER_D_CLOCKSOURCE_DIVIDER_3
TIMER_D_CLOCKSOURCE_DIVIDER_4
TIMER_D_CLOCKSOURCE_DIVIDER_5
TIMER_D_CLOCKSOURCE_DIVIDER_6
TIMER_D_CLOCKSOURCE_DIVIDER_7
TIMER_D_CLOCKSOURCE_DIVIDER_8
TIMER_D_CLOCKSOURCE_DIVIDER_10
TIMER_D_CLOCKSOURCE_DIVIDER_12
TIMER_D_CLOCKSOURCE_DIVIDER_14
TIMER_D_CLOCKSOURCE_DIVIDER_16
TIMER_D_CLOCKSOURCE_DIVIDER_20
TIMER_D_CLOCKSOURCE_DIVIDER_24
TIMER_D_CLOCKSOURCE_DIVIDER_28
TIMER_D_CLOCKSOURCE_DIVIDER_32
TIMER_D_CLOCKSOURCE_DIVIDER_40
TIMER_D_CLOCKSOURCE_DIVIDER_48
TIMER_D_CLOCKSOURCE_DIVIDER_56
TIMER_D_CLOCKSOURCE_DIVIDER_64
clockingMode is the selected clock mode register values. Valid values are:
TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK [Default]
TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK
TIMER_D_CLOCKINGMODE_AUXILIARY_CLK
highResClockMultiplyFactor selects the high resolution multiply factor. Valid values are:
TIMER_D_HIGHRES_CLK_MULTIPLY_FACTOR_8x
TIMER_D_HIGHRES_CLK_MULTIPLY_FACTOR_16x
highResClockDivider selects the high resolution divider. Valid values are:
TIMER_D_HIGHRES_CLK_DIVIDER_1
TIMER_D_HIGHRES_CLK_DIVIDER_2
TIMER_D_HIGHRES_CLK_DIVIDER_4
TIMER_D_HIGHRES_CLK_DIVIDER_8
Modified bits of TDxHCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_initHighResGeneratorInRegulatedModeParam::clockingMode, TIMER_D_initHighResGeneratorInRegulatedModeParam::clockSource, TIMER_D_initHighResGeneratorInRegulatedModeParam::clockSourceDivider, TIMER_D_initHighResGeneratorInRegulatedModeParam::highResClockDivider, TIMER_D_initHighResGeneratorInRegulatedModeParam::highResClockMultiplyFactor, and TIMER_D_initHighResGeneratorInRegulatedMode().
void TIMER_D_combineTDCCRToOutputPWM (uint16_t baseAddress, TIMER_D_combineTDCCRToOutputPWMParam * param)
Combine TDCCR to get PWM.
Parameters
baseAddress is the base address of the TIMER_D module.
param is the pointer to struct for PWM generation using two CCRs.
Modified bits of TDxCCTLn register, bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_combineTDCCRToOutputPWMParam::clockingMode, TIMER_D_combineTDCCRToOutputPWMParam::clockSource, TIMER_D_combineTDCCRToOutputPWMParam::clockSourceDivider, TIMER_D_combineTDCCRToOutputPWMParam::combineCCRRegistersCombination, TIMER_D_combineTDCCRToOutputPWMParam::compareOutputMode, TIMER_D_combineTDCCRToOutputPWMParam::dutyCycle1, TIMER_D_combineTDCCRToOutputPWMParam::dutyCycle2, HWREG16, ID__8, OFS_TDxCCR0, OFS_TDxCCR1, OFS_TDxCCR2, OFS_TDxCCTL2, OFS_TDxCTL0, OFS_TDxCTL1, OUTMOD_7, TD2CMB, TDCLKM0, TDCLKM1, TDIDEX_7, TIMER_D_CLOCKINGMODE_AUXILIARY_CLK, TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK, TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK, TIMER_D_CLOCKSOURCE_ACLK, TIMER_D_CLOCKSOURCE_DIVIDER_1, TIMER_D_CLOCKSOURCE_DIVIDER_10, TIMER_D_CLOCKSOURCE_DIVIDER_12, TIMER_D_CLOCKSOURCE_DIVIDER_14, TIMER_D_CLOCKSOURCE_DIVIDER_16, TIMER_D_CLOCKSOURCE_DIVIDER_2, TIMER_D_CLOCKSOURCE_DIVIDER_20, TIMER_D_CLOCKSOURCE_DIVIDER_24, TIMER_D_CLOCKSOURCE_DIVIDER_28, TIMER_D_CLOCKSOURCE_DIVIDER_3, TIMER_D_CLOCKSOURCE_DIVIDER_32, TIMER_D_CLOCKSOURCE_DIVIDER_4, TIMER_D_CLOCKSOURCE_DIVIDER_40, TIMER_D_CLOCKSOURCE_DIVIDER_48, TIMER_D_CLOCKSOURCE_DIVIDER_5, TIMER_D_CLOCKSOURCE_DIVIDER_56, TIMER_D_CLOCKSOURCE_DIVIDER_6, TIMER_D_CLOCKSOURCE_DIVIDER_64, TIMER_D_CLOCKSOURCE_DIVIDER_7, TIMER_D_CLOCKSOURCE_DIVIDER_8, TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK, TIMER_D_CLOCKSOURCE_SMCLK, TIMER_D_COMBINE_CCR1_CCR2, TIMER_D_COMBINE_CCR3_CCR4, TIMER_D_COMBINE_CCR5_CCR6, TIMER_D_OUTPUTMODE_OUTBITVALUE, TIMER_D_OUTPUTMODE_RESET, TIMER_D_OUTPUTMODE_RESET_SET, TIMER_D_OUTPUTMODE_SET, TIMER_D_OUTPUTMODE_SET_RESET, TIMER_D_OUTPUTMODE_TOGGLE, TIMER_D_OUTPUTMODE_TOGGLE_RESET, TIMER_D_OUTPUTMODE_TOGGLE_SET, and TIMER_D_combineTDCCRToOutputPWMParam::timerPeriod.
Referenced by TIMER_D_combineTDCCRToGeneratePWM().
void TIMER_D_combineTDCCRToGeneratePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t clockingMode, uint16_t timerPeriod, uint16_t combineCCRRegistersCombination, uint16_t compareOutputMode, uint16_t dutyCycle1, uint16_t dutyCycle2)
DEPRECATED - Combine TDCCR to get PWM.
Parameters
baseAddress is the base address of the TIMER_D module.
clockSource selects Clock source. Valid values are:
TIMER_D_CLOCKSOURCE_EXTERNAL_TDCLK [Default]
TIMER_D_CLOCKSOURCE_ACLK
TIMER_D_CLOCKSOURCE_SMCLK
TIMER_D_CLOCKSOURCE_INVERTED_EXTERNAL_TDCLK
clockSourceDivider is the divider for clock source. Valid values are:
TIMER_D_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_D_CLOCKSOURCE_DIVIDER_2
TIMER_D_CLOCKSOURCE_DIVIDER_3
TIMER_D_CLOCKSOURCE_DIVIDER_4
TIMER_D_CLOCKSOURCE_DIVIDER_5
TIMER_D_CLOCKSOURCE_DIVIDER_6
TIMER_D_CLOCKSOURCE_DIVIDER_7
TIMER_D_CLOCKSOURCE_DIVIDER_8
TIMER_D_CLOCKSOURCE_DIVIDER_10
TIMER_D_CLOCKSOURCE_DIVIDER_12
TIMER_D_CLOCKSOURCE_DIVIDER_14
TIMER_D_CLOCKSOURCE_DIVIDER_16
TIMER_D_CLOCKSOURCE_DIVIDER_20
TIMER_D_CLOCKSOURCE_DIVIDER_24
TIMER_D_CLOCKSOURCE_DIVIDER_28
TIMER_D_CLOCKSOURCE_DIVIDER_32
TIMER_D_CLOCKSOURCE_DIVIDER_40
TIMER_D_CLOCKSOURCE_DIVIDER_48
TIMER_D_CLOCKSOURCE_DIVIDER_56
TIMER_D_CLOCKSOURCE_DIVIDER_64
clockingMode is the selected clock mode register values. Valid values are:
TIMER_D_CLOCKINGMODE_EXTERNAL_CLOCK [Default]
TIMER_D_CLOCKINGMODE_HIRES_LOCAL_CLOCK
TIMER_D_CLOCKINGMODE_AUXILIARY_CLK
timerPeriod is the specified timer period
combineCCRRegistersCombination selects desired CCR registers to combine Valid values are:
TIMER_D_COMBINE_CCR1_CCR2
TIMER_D_COMBINE_CCR3_CCR4 - (available on TIMER_D5, TIMER_D7)
TIMER_D_COMBINE_CCR5_CCR6 - (available only on TIMER_D7)
compareOutputMode specifies the output mode. Valid values are:
TIMER_D_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_D_OUTPUTMODE_SET
TIMER_D_OUTPUTMODE_TOGGLE_RESET
TIMER_D_OUTPUTMODE_SET_RESET
TIMER_D_OUTPUTMODE_TOGGLE
TIMER_D_OUTPUTMODE_RESET
TIMER_D_OUTPUTMODE_TOGGLE_SET
TIMER_D_OUTPUTMODE_RESET_SET
dutyCycle1 specifies the dutycycle for the generated waveform
dutyCycle2 specifies the dutycycle for the generated waveform
Modified bits of TDxCCTLn register, bits of TDxCCR0 register, bits of TDxCCTL0 register, bits of TDxCTL0 register and bits of TDxCTL1 register.
Returns
None
References TIMER_D_combineTDCCRToOutputPWMParam::clockingMode, TIMER_D_combineTDCCRToOutputPWMParam::clockSource, TIMER_D_combineTDCCRToOutputPWMParam::clockSourceDivider, TIMER_D_combineTDCCRToOutputPWMParam::combineCCRRegistersCombination, TIMER_D_combineTDCCRToOutputPWMParam::compareOutputMode, TIMER_D_combineTDCCRToOutputPWMParam::dutyCycle1, TIMER_D_combineTDCCRToOutputPWMParam::dutyCycle2, TIMER_D_combineTDCCRToOutputPWM(), and TIMER_D_combineTDCCRToOutputPWMParam::timerPeriod.
void TIMER_D_selectLatchingGroup (uint16_t baseAddress, uint16_t groupLatch)
Selects TIMER_D Latching Group.
Parameters
baseAddress is the base address of the TIMER_D module.
groupLatch selects the group latch Valid values are:
TIMER_D_GROUP_NONE [Default]
TIMER_D_GROUP_CL12_CL23_CL56
TIMER_D_GROUP_CL123_CL456
TIMER_D_GROUP_ALL
Modified bits are TDCLGRP of TDxCTL0 register.
Returns
None
References HWREG16, OFS_TDxCTL0, TDCLGRP_3, TIMER_D_GROUP_ALL, TIMER_D_GROUP_CL123_CL456, TIMER_D_GROUP_CL12_CL23_CL56, and TIMER_D_GROUP_NONE.
void TIMER_D_selectCounterLength (uint16_t baseAddress, uint16_t counterLength)
Selects TIMER_D counter length.
Parameters
baseAddress is the base address of the TIMER_D module.
counterLength selects the value of counter length. Valid values are:
TIMER_D_COUNTER_16BIT [Default]
TIMER_D_COUNTER_12BIT
TIMER_D_COUNTER_10BIT
TIMER_D_COUNTER_8BIT
Modified bits are CNTL of TDxCTL0 register.
Returns
None
References CNTL_3, HWREG16, OFS_TDxCTL0, TIMER_D_COUNTER_10BIT, TIMER_D_COUNTER_12BIT, TIMER_D_COUNTER_16BIT, and TIMER_D_COUNTER_8BIT.
void TIMER_D_initCompareLatchLoadEvent (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareLatchLoadEvent)
Selects Compare Latch Load Event.
Parameters
baseAddress is the base address of the TIMER_D module.
compareRegister selects the compare register being used. Valid values are:
TIMER_D_CAPTURECOMPARE_REGISTER_0
TIMER_D_CAPTURECOMPARE_REGISTER_1
TIMER_D_CAPTURECOMPARE_REGISTER_2
TIMER_D_CAPTURECOMPARE_REGISTER_3
TIMER_D_CAPTURECOMPARE_REGISTER_4
TIMER_D_CAPTURECOMPARE_REGISTER_5
TIMER_D_CAPTURECOMPARE_REGISTER_6
compareLatchLoadEvent selects the latch load event Valid values are:
TIMER_D_LATCH_ON_WRITE_TO_TDxCCRn_COMPARE_REGISTER [Default]
TIMER_D_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UP_OR_CONT_MODE
TIMER_D_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UPDOWN_MODE
TIMER_D_LATCH_WHEN_COUNTER_COUNTS_TO_CURRENT_COMPARE_LATCH_VALUE
Modified bits are CLLD of TDxCCTLn register.
Returns
None
References CLLD_3, HWREG16, TIMER_D_LATCH_ON_WRITE_TO_TDxCCRn_COMPARE_REGISTER, TIMER_D_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UP_OR_CONT_MODE, TIMER_D_LATCH_WHEN_COUNTER_COUNTS_TO_0_IN_UPDOWN_MODE, and TIMER_D_LATCH_WHEN_COUNTER_COUNTS_TO_CURRENT_COMPARE_LATCH_VALUE.
void TIMER_D_disableHighResFastWakeup (uint16_t baseAddress)
Disable High Resolution fast wakeup.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDHFW of TDxHCTL0 register.
Returns
None
References HWREG16, OFS_TDxHCTL0, and TDHFW.
void TIMER_D_enableHighResFastWakeup (uint16_t baseAddress)
Enable High Resolution fast wakeup.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDHFW of TDxHCTL0 register.
Returns
None
References HWREG16, OFS_TDxHCTL0, and TDHFW.
void TIMER_D_disableHighResClockEnhancedAccuracy (uint16_t baseAddress)
Disable High Resolution Clock Enhanced Accuracy.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDHEAEN of TDxHCTL0 register.
Returns
None
References HWREG16, OFS_TDxHCTL0, and TDHEAEN.
void TIMER_D_enableHighResClockEnhancedAccuracy (uint16_t baseAddress)
Enable High Resolution Clock Enhanced Accuracy.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDHEAEN of TDxHCTL0 register.
Returns
None
References HWREG16, OFS_TDxHCTL0, and TDHEAEN.
void TIMER_D_DisableHighResGeneratorForceON (uint16_t baseAddress)
Disable High Resolution Clock Enhanced Accuracy.
High-resolution generator is on if the TIMER_D counter
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDHRON of TDxHCTL0 register.
Returns
None
References HWREG16, OFS_TDxHCTL0, and TDHRON.
void TIMER_D_EnableHighResGeneratorForceON (uint16_t baseAddress)
Enable High Resolution Clock Enhanced Accuracy.
High-resolution generator is on in all TIMER_D MCx modes. The PMM remains in high-current mode.
Parameters
baseAddress is the base address of the TIMER_D module.
Modified bits are TDHRON of TDxHCTL0 register.
Returns
None
References HWREG16, OFS_TDxHCTL0, and TDHRON.
void TIMER_D_selectHighResCoarseClockRange (uint16_t baseAddress, uint16_t highResCoarseClockRange)
Select High Resolution Coarse Clock Range.
Parameters
baseAddress is the base address of the TIMER_D module.
highResCoarseClockRange selects the High Resolution Coarse Clock Range Valid values are:
TIMER_D_HIGHRES_BELOW_15MHz [Default]
TIMER_D_HIGHRES_ABOVE_15MHz
Modified bits are TDHCLKCR of TDxHCTL1 register.
Returns
None
References HWREG16, OFS_TDxHCTL1, TDHCLKCR, TIMER_D_HIGHRES_ABOVE_15MHz, and TIMER_D_HIGHRES_BELOW_15MHz.
void TIMER_D_selectHighResClockRange (uint16_t baseAddress, uint16_t highResClockRange)
Select High Resolution Clock Range Selection.
Parameters
baseAddress is the base address of the TIMER_D module.
highResClockRange selects the High Resolution Clock Range. Refer to datasheet for frequency details Valid values are:
TIMER_D_CLOCK_RANGE0 [Default]
TIMER_D_CLOCK_RANGE1
TIMER_D_CLOCK_RANGE2
Returns
None
References HWREG16, OFS_TDxHCTL1, TDHCLKCR, TIMER_D_CLOCK_RANGE0, TIMER_D_CLOCK_RANGE1, and TIMER_D_CLOCK_RANGE2.
uint16_t TIMER_D_getCounterValue (uint16_t baseAddress)
Reads the current timer count value.
Reads the current count value of the timer. There is a majority vote system in place to confirm an accurate value is returned. The TIMER_D_THRESHOLD #define in the corresponding header file can be modified so that the votes must be closer together for a consensus to occur.
Parameters
baseAddress is the base address of the TIMER_D module.
Returns
Majority vote of timer count value
References HWREG16, OFS_TDxR, and TIMER_D_THRESHOLD.
Copyright 2014, Texas Instruments Incorporated