Timer_a_api
Timer_a_api
Functions
void TIMER_A_startCounter (uint16_t baseAddress, uint16_t timerMode)
Starts TIMER_A counter.
void TIMER_A_initContinuousMode (uint16_t baseAddress, TIMER_A_initContinuousModeParam *param)
Configures TIMER_A in continuous mode.
void TIMER_A_configureContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TAIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_A in continuous mode.
void TIMER_A_initUpMode (uint16_t baseAddress, TIMER_A_initUpModeParam *param)
Configures TIMER_A in up mode.
void TIMER_A_configureUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_A in up mode.
void TIMER_A_initUpDownMode (uint16_t baseAddress, TIMER_A_initUpDownModeParam *param)
Configures TIMER_A in up down mode.
void TIMER_A_configureUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_A in up down mode.
void TIMER_A_startContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TAIE, uint16_t timerClear)
DEPRECATED - Starts timer in continuous mode.
void TIMER_A_startContinousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TAIE, uint16_t timerClear)
DEPRECATED - Spelling Error Fixed. Starts timer in continuous mode.
void TIMER_A_startUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_A_configureUpMode and TIMER_A_startCounter API. Starts timer in up mode.
void TIMER_A_startUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_A_configureUpMode and TIMER_A_startCounter API. Starts timer in up down mode.
void TIMER_A_initCaptureMode (uint16_t baseAddress, TIMER_A_initCaptureModeParam *param)
Initializes Capture Mode.
void TIMER_A_initCapture (uint16_t baseAddress, uint16_t captureRegister, uint16_t captureMode, uint16_t captureInputSelect, uint16_t synchronizeCaptureSource, uint16_t captureInterruptEnable, uint16_t captureOutputMode)
DEPRECATED - Initializes Capture Mode.
void TIMER_A_initCompareMode (uint16_t baseAddress, TIMER_A_initCompareModeParam *param)
Initializes Compare Mode.
void TIMER_A_initCompare (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareInterruptEnable, uint16_t compareOutputMode, uint16_t compareValue)
DEPRECATED - Initializes Compare Mode.
void TIMER_A_enableInterrupt (uint16_t baseAddress)
Enable timer interrupt.
void TIMER_A_disableInterrupt (uint16_t baseAddress)
Disable timer interrupt.
uint32_t TIMER_A_getInterruptStatus (uint16_t baseAddress)
Get timer interrupt status.
void TIMER_A_enableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Enable capture compare interrupt.
void TIMER_A_disableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Disable capture compare interrupt.
uint32_t TIMER_A_getCaptureCompareInterruptStatus (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t mask)
Return capture compare interrupt status.
void TIMER_A_clear (uint16_t baseAddress)
Reset/Clear the timer clock divider, count direction, count.
uint8_t TIMER_A_getSynchronizedCaptureCompareInput (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t synchronized)
Get synchronized capturecompare input.
uint8_t TIMER_A_getOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister)
Get output bit for output mode.
uint16_t TIMER_A_getCaptureCompareCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare count.
void TIMER_A_setOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister, uint8_t outputModeOutBitValue)
Set output bit for output mode.
void TIMER_A_outputPWM (uint16_t baseAddress, TIMER_A_outputPWMParam *param)
Generate a PWM with timer running in up mode.
void TIMER_A_generatePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t compareRegister, uint16_t compareOutputMode, uint16_t dutyCycle)
DEPRECATED - Generate a PWM with timer running in up mode.
void TIMER_A_stop (uint16_t baseAddress)
Stops the timer.
void TIMER_A_setCompareValue (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareValue)
Sets the value of the capture-compare register.
void TIMER_A_clearTimerInterruptFlag (uint16_t baseAddress)
Clears the Timer TAIFG interrupt flag.
void TIMER_A_clearCaptureCompareInterruptFlag (uint16_t baseAddress, uint16_t captureCompareRegister)
Clears the capture-compare interrupt flag.
uint16_t TIMER_A_getCounterValue (uint16_t baseAddress)
Reads the current timer count value.
Detailed Description
Function Documentation
void TIMER_A_startCounter (uint16_t baseAddress, uint16_t timerMode)
Starts TIMER_A counter.
This function assumes that the timer has been previously configured using TIMER_A_configureContinuousMode, TIMER_A_configureUpMode or TIMER_A_configureUpDownMode.
Parameters
baseAddress is the base address of the TIMER_A module.
timerMode mode to put the timer in Valid values are:
TIMER_A_STOP_MODE
TIMER_A_UP_MODE
TIMER_A_CONTINUOUS_MODE [Default]
TIMER_A_UPDOWN_MODE
Modified bits of TAxCTL register.
Returns
None
References HWREG16, OFS_TAxCTL, TIMER_A_CONTINUOUS_MODE, TIMER_A_UP_MODE, and TIMER_A_UPDOWN_MODE.
void TIMER_A_initContinuousMode (uint16_t baseAddress, TIMER_A_initContinuousModeParam * param)
Configures TIMER_A in continuous mode.
Parameters
baseAddress is the base address of the TIMER_A module.
param is the pointer to struct for continuous mode initialization.
Modified bits of TAxCTL register.
Returns
None
References TIMER_A_initContinuousModeParam::clockSource, TIMER_A_initContinuousModeParam::clockSourceDivider, HWREG16, ID__8, OFS_TAxCTL, OFS_TAxEX0, TIMER_A_initContinuousModeParam::startTimer, TAIDEX_7, TIMER_A_CLOCKSOURCE_ACLK, TIMER_A_CLOCKSOURCE_DIVIDER_1, TIMER_A_CLOCKSOURCE_DIVIDER_10, TIMER_A_CLOCKSOURCE_DIVIDER_12, TIMER_A_CLOCKSOURCE_DIVIDER_14, TIMER_A_CLOCKSOURCE_DIVIDER_16, TIMER_A_CLOCKSOURCE_DIVIDER_2, TIMER_A_CLOCKSOURCE_DIVIDER_20, TIMER_A_CLOCKSOURCE_DIVIDER_24, TIMER_A_CLOCKSOURCE_DIVIDER_28, TIMER_A_CLOCKSOURCE_DIVIDER_3, TIMER_A_CLOCKSOURCE_DIVIDER_32, TIMER_A_CLOCKSOURCE_DIVIDER_4, TIMER_A_CLOCKSOURCE_DIVIDER_40, TIMER_A_CLOCKSOURCE_DIVIDER_48, TIMER_A_CLOCKSOURCE_DIVIDER_5, TIMER_A_CLOCKSOURCE_DIVIDER_56, TIMER_A_CLOCKSOURCE_DIVIDER_6, TIMER_A_CLOCKSOURCE_DIVIDER_64, TIMER_A_CLOCKSOURCE_DIVIDER_7, TIMER_A_CLOCKSOURCE_DIVIDER_8, TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_SMCLK, TIMER_A_CONTINUOUS_MODE, TIMER_A_DO_CLEAR, TIMER_A_SKIP_CLEAR, TIMER_A_TAIE_INTERRUPT_DISABLE, TIMER_A_TAIE_INTERRUPT_ENABLE, TIMER_A_UPDOWN_MODE, TIMER_A_initContinuousModeParam::timerClear, and TIMER_A_initContinuousModeParam::timerInterruptEnable_TAIE.
Referenced by TIMER_A_configureContinuousMode(), and TIMER_A_startContinuousMode().
void TIMER_A_configureContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TAIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_A in continuous mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_A_startCounter API.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TAIE is to enable or disable TIMER_A interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_A clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register.
Returns
None
References TIMER_A_initContinuousModeParam::clockSource, TIMER_A_initContinuousModeParam::clockSourceDivider, TIMER_A_initContinuousModeParam::startTimer, TIMER_A_initContinuousMode(), TIMER_A_initContinuousModeParam::timerClear, and TIMER_A_initContinuousModeParam::timerInterruptEnable_TAIE.
void TIMER_A_initUpMode (uint16_t baseAddress, TIMER_A_initUpModeParam * param)
Configures TIMER_A in up mode.
Parameters
baseAddress is the base address of the TIMER_A module.
param is the pointer to struct for up mode initialization.
Modified bits of TAxCTL register, bits of TAxCCTL0 register and bits of TAxCCR0 register.
Returns
None
References TIMER_A_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_A_initUpModeParam::clockSource, TIMER_A_initUpModeParam::clockSourceDivider, HWREG16, ID__8, OFS_TAxCCR0, OFS_TAxCCTL0, OFS_TAxCTL, OFS_TAxEX0, TIMER_A_initUpModeParam::startTimer, TAIDEX_7, TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_A_CLOCKSOURCE_ACLK, TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_SMCLK, TIMER_A_DO_CLEAR, TIMER_A_SKIP_CLEAR, TIMER_A_TAIE_INTERRUPT_ENABLE, TIMER_A_UP_MODE, TIMER_A_UPDOWN_MODE, TIMER_A_initUpModeParam::timerClear, TIMER_A_initUpModeParam::timerInterruptEnable_TAIE, and TIMER_A_initUpModeParam::timerPeriod.
Referenced by TIMER_A_configureUpMode(), and TIMER_A_startUpMode().
void TIMER_A_configureUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_A in up mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_A_startCounter API.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified TIMER_A period. This is the value that gets written into the CCR0. Limited to 16 bits[uint16_t]
timerInterruptEnable_TAIE is to enable or disable TIMER_A interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable TIMER_A CCR0 captureComapre interrupt. Valid values are:
TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_A_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_A clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register, bits of TAxCCTL0 register and bits of TAxCCR0 register.
Returns
None
References TIMER_A_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_A_initUpModeParam::clockSource, TIMER_A_initUpModeParam::clockSourceDivider, TIMER_A_initUpModeParam::startTimer, TIMER_A_initUpMode(), TIMER_A_initUpModeParam::timerClear, TIMER_A_initUpModeParam::timerInterruptEnable_TAIE, and TIMER_A_initUpModeParam::timerPeriod.
void TIMER_A_initUpDownMode (uint16_t baseAddress, TIMER_A_initUpDownModeParam * param)
Configures TIMER_A in up down mode.
Parameters
baseAddress is the base address of the TIMER_A module.
param is the pointer to struct for up-down mode initialization.
Modified bits of TAxCTL register, bits of TAxCCTL0 register and bits of TAxCCR0 register.
Returns
None
References TIMER_A_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_A_initUpDownModeParam::clockSource, TIMER_A_initUpDownModeParam::clockSourceDivider, HWREG16, ID__8, OFS_TAxCCR0, OFS_TAxCCTL0, OFS_TAxCTL, OFS_TAxEX0, TIMER_A_initUpDownModeParam::startTimer, TAIDEX_7, TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE, TIMER_A_CLOCKSOURCE_ACLK, TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_SMCLK, TIMER_A_DO_CLEAR, TIMER_A_SKIP_CLEAR, TIMER_A_TAIE_INTERRUPT_ENABLE, TIMER_A_UPDOWN_MODE, TIMER_A_initUpDownModeParam::timerClear, TIMER_A_initUpDownModeParam::timerInterruptEnable_TAIE, and TIMER_A_initUpDownModeParam::timerPeriod.
Referenced by TIMER_A_configureUpDownMode(), and TIMER_A_startUpDownMode().
void TIMER_A_configureUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Configures TIMER_A in up down mode.
This API does not start the timer. Timer needs to be started when required using the TIMER_A_startCounter API.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified TIMER_A period
timerInterruptEnable_TAIE is to enable or disable TIMER_A interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable TIMER_A CCR0 captureComapre interrupt. Valid values are:
TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_A_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if TIMER_A clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register, bits of TAxCCTL0 register and bits of TAxCCR0 register.
Returns
None
References TIMER_A_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_A_initUpDownModeParam::clockSource, TIMER_A_initUpDownModeParam::clockSourceDivider, TIMER_A_initUpDownModeParam::startTimer, TIMER_A_initUpDownMode(), TIMER_A_initUpDownModeParam::timerClear, TIMER_A_initUpDownModeParam::timerInterruptEnable_TAIE, and TIMER_A_initUpDownModeParam::timerPeriod.
void TIMER_A_startContinuousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TAIE, uint16_t timerClear)
DEPRECATED - Starts timer in continuous mode.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register.
Returns
None
References TIMER_A_initContinuousModeParam::clockSource, TIMER_A_initContinuousModeParam::clockSourceDivider, TIMER_A_initContinuousModeParam::startTimer, TIMER_A_initContinuousMode(), TIMER_A_initContinuousModeParam::timerClear, and TIMER_A_initContinuousModeParam::timerInterruptEnable_TAIE.
Referenced by TIMER_A_startContinousMode().
void TIMER_A_startContinousMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerInterruptEnable_TAIE, uint16_t timerClear)
DEPRECATED - Spelling Error Fixed. Starts timer in continuous mode.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register.
Returns
None
References TIMER_A_startContinuousMode().
void TIMER_A_startUpMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_A_configureUpMode and TIMER_A_startCounter API. Starts timer in up mode.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified timer period. This is the value that gets written into the CCR0. Limited to 16 bits[uint16_t]
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable timer CCR0 captureComapre interrupt. Valid values are:
TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_A_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register, bits of TAxCCTL0 register and bits of TAxCCR0 register.
Returns
None
References TIMER_A_initUpModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_A_initUpModeParam::clockSource, TIMER_A_initUpModeParam::clockSourceDivider, TIMER_A_initUpModeParam::startTimer, TIMER_A_initUpMode(), TIMER_A_initUpModeParam::timerClear, TIMER_A_initUpModeParam::timerInterruptEnable_TAIE, and TIMER_A_initUpModeParam::timerPeriod.
void TIMER_A_startUpDownMode (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t timerInterruptEnable_TAIE, uint16_t captureCompareInterruptEnable_CCR0_CCIE, uint16_t timerClear)
DEPRECATED - Replaced by TIMER_A_configureUpMode and TIMER_A_startCounter API. Starts timer in up down mode.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerPeriod is the specified timer period
timerInterruptEnable_TAIE is to enable or disable timer interrupt Valid values are:
TIMER_A_TAIE_INTERRUPT_ENABLE
TIMER_A_TAIE_INTERRUPT_DISABLE [Default]
captureCompareInterruptEnable_CCR0_CCIE is to enable or disable timer CCR0 captureComapre interrupt. Valid values are:
TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE
TIMER_A_CCIE_CCR0_INTERRUPT_DISABLE [Default]
timerClear decides if timer clock divider, count direction, count need to be reset. Valid values are:
TIMER_A_DO_CLEAR
TIMER_A_SKIP_CLEAR [Default]
Modified bits of TAxCTL register, bits of TAxCCTL0 register and bits of TAxCCR0 register.
Returns
None
References TIMER_A_initUpDownModeParam::captureCompareInterruptEnable_CCR0_CCIE, TIMER_A_initUpDownModeParam::clockSource, TIMER_A_initUpDownModeParam::clockSourceDivider, TIMER_A_initUpDownModeParam::startTimer, TIMER_A_initUpDownMode(), TIMER_A_initUpDownModeParam::timerClear, TIMER_A_initUpDownModeParam::timerInterruptEnable_TAIE, and TIMER_A_initUpDownModeParam::timerPeriod.
void TIMER_A_initCaptureMode (uint16_t baseAddress, TIMER_A_initCaptureModeParam * param)
Initializes Capture Mode.
Parameters
baseAddress is the base address of the TIMER_A module.
param is the pointer to struct for capture mode initialization.
Modified bits of TAxCCTLn register.
Returns
None
References CAP, TIMER_A_initCaptureModeParam::captureInputSelect, TIMER_A_initCaptureModeParam::captureInterruptEnable, TIMER_A_initCaptureModeParam::captureMode, TIMER_A_initCaptureModeParam::captureOutputMode, TIMER_A_initCaptureModeParam::captureRegister, CM_3, HWREG16, TIMER_A_initCaptureModeParam::synchronizeCaptureSource, TIMER_A_CAPTURE_ASYNCHRONOUS, TIMER_A_CAPTURE_INPUTSELECT_CCIxA, TIMER_A_CAPTURE_INPUTSELECT_CCIxB, TIMER_A_CAPTURE_INPUTSELECT_GND, TIMER_A_CAPTURE_INPUTSELECT_Vcc, TIMER_A_CAPTURE_SYNCHRONOUS, TIMER_A_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, TIMER_A_CAPTURECOMPARE_REGISTER_6, TIMER_A_CAPTUREMODE_FALLING_EDGE, TIMER_A_CAPTUREMODE_NO_CAPTURE, TIMER_A_CAPTUREMODE_RISING_AND_FALLING_EDGE, TIMER_A_CAPTUREMODE_RISING_EDGE, TIMER_A_DO_CLEAR, TIMER_A_OUTPUTMODE_OUTBITVALUE, TIMER_A_OUTPUTMODE_RESET, TIMER_A_OUTPUTMODE_RESET_SET, TIMER_A_OUTPUTMODE_SET, TIMER_A_OUTPUTMODE_SET_RESET, TIMER_A_OUTPUTMODE_TOGGLE, TIMER_A_OUTPUTMODE_TOGGLE_RESET, TIMER_A_OUTPUTMODE_TOGGLE_SET, and TIMER_A_TAIE_INTERRUPT_ENABLE.
Referenced by TIMER_A_initCapture().
void TIMER_A_initCapture (uint16_t baseAddress, uint16_t captureRegister, uint16_t captureMode, uint16_t captureInputSelect, uint16_t synchronizeCaptureSource, uint16_t captureInterruptEnable, uint16_t captureOutputMode)
DEPRECATED - Initializes Capture Mode.
Parameters
baseAddress is the base address of the TIMER_A module.
captureRegister selects the Capture register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
captureMode is the capture mode selected. Valid values are:
TIMER_A_CAPTUREMODE_NO_CAPTURE [Default]
TIMER_A_CAPTUREMODE_RISING_EDGE
TIMER_A_CAPTUREMODE_FALLING_EDGE
TIMER_A_CAPTUREMODE_RISING_AND_FALLING_EDGE
captureInputSelect decides the Input Select Valid values are:
TIMER_A_CAPTURE_INPUTSELECT_CCIxA
TIMER_A_CAPTURE_INPUTSELECT_CCIxB
TIMER_A_CAPTURE_INPUTSELECT_GND
TIMER_A_CAPTURE_INPUTSELECT_Vcc
synchronizeCaptureSource decides if capture source should be synchronized with timer clock Valid values are:
TIMER_A_CAPTURE_ASYNCHRONOUS [Default]
TIMER_A_CAPTURE_SYNCHRONOUS
captureInterruptEnable is to enable or disable timer captureComapre interrupt. Valid values are:
TIMER_A_CAPTURECOMPARE_INTERRUPT_DISABLE [Default]
TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE
captureOutputMode specifies the output mode. Valid values are:
TIMER_A_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_A_OUTPUTMODE_SET
TIMER_A_OUTPUTMODE_TOGGLE_RESET
TIMER_A_OUTPUTMODE_SET_RESET
TIMER_A_OUTPUTMODE_TOGGLE
TIMER_A_OUTPUTMODE_RESET
TIMER_A_OUTPUTMODE_TOGGLE_SET
TIMER_A_OUTPUTMODE_RESET_SET
Modified bits of TAxCCTLn register.
Returns
None
References TIMER_A_initCaptureModeParam::captureInputSelect, TIMER_A_initCaptureModeParam::captureInterruptEnable, TIMER_A_initCaptureModeParam::captureMode, TIMER_A_initCaptureModeParam::captureOutputMode, TIMER_A_initCaptureModeParam::captureRegister, TIMER_A_initCaptureModeParam::synchronizeCaptureSource, and TIMER_A_initCaptureMode().
void TIMER_A_initCompareMode (uint16_t baseAddress, TIMER_A_initCompareModeParam * param)
Initializes Compare Mode.
Parameters
baseAddress is the base address of the TIMER_A module.
param is the pointer to struct for compare mode initialization.
Modified bits of TAxCCRn register and bits of TAxCCTLn register.
Returns
None
References CAP, TIMER_A_initCompareModeParam::compareInterruptEnable, TIMER_A_initCompareModeParam::compareOutputMode, TIMER_A_initCompareModeParam::compareRegister, TIMER_A_initCompareModeParam::compareValue, HWREG16, OFS_TAxR, TIMER_A_CAPTURECOMPARE_INTERRUPT_DISABLE, TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, TIMER_A_CAPTURECOMPARE_REGISTER_6, TIMER_A_OUTPUTMODE_OUTBITVALUE, TIMER_A_OUTPUTMODE_RESET, TIMER_A_OUTPUTMODE_RESET_SET, TIMER_A_OUTPUTMODE_SET, TIMER_A_OUTPUTMODE_SET_RESET, TIMER_A_OUTPUTMODE_TOGGLE, TIMER_A_OUTPUTMODE_TOGGLE_RESET, and TIMER_A_OUTPUTMODE_TOGGLE_SET.
Referenced by TIMER_A_initCompare().
void TIMER_A_initCompare (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareInterruptEnable, uint16_t compareOutputMode, uint16_t compareValue)
DEPRECATED - Initializes Compare Mode.
Parameters
baseAddress is the base address of the TIMER_A module.
compareRegister selects the Capture register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
compareInterruptEnable is to enable or disable timer captureComapre interrupt. Valid values are:
TIMER_A_CAPTURECOMPARE_INTERRUPT_DISABLE [Default]
TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE
compareOutputMode specifies the output mode. Valid values are:
TIMER_A_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_A_OUTPUTMODE_SET
TIMER_A_OUTPUTMODE_TOGGLE_RESET
TIMER_A_OUTPUTMODE_SET_RESET
TIMER_A_OUTPUTMODE_TOGGLE
TIMER_A_OUTPUTMODE_RESET
TIMER_A_OUTPUTMODE_TOGGLE_SET
TIMER_A_OUTPUTMODE_RESET_SET
compareValue is the count to be compared with in compare mode
Modified bits of TAxCCRn register and bits of TAxCCTLn register.
Returns
None
References TIMER_A_initCompareModeParam::compareInterruptEnable, TIMER_A_initCompareModeParam::compareOutputMode, TIMER_A_initCompareModeParam::compareRegister, TIMER_A_initCompareModeParam::compareValue, and TIMER_A_initCompareMode().
void TIMER_A_enableInterrupt (uint16_t baseAddress)
Enable timer interrupt.
Does not clear interrupt flags
Parameters
baseAddress is the base address of the TIMER_A module.
Modified bits of TAxCTL register.
Returns
None
References HWREG16, OFS_TAxCTL, and TAIE.
void TIMER_A_disableInterrupt (uint16_t baseAddress)
Disable timer interrupt.
Parameters
baseAddress is the base address of the TIMER_A module.
Modified bits of TAxCTL register.
Returns
None
References HWREG16, OFS_TAxCTL, and TAIE.
uint32_t TIMER_A_getInterruptStatus (uint16_t baseAddress)
Get timer interrupt status.
Parameters
baseAddress is the base address of the TIMER_A module.
Returns
One of the following:
TIMER_A_INTERRUPT_NOT_PENDING
TIMER_A_INTERRUPT_PENDING
indicating the TIMER_A interrupt status
References HWREG16, OFS_TAxCTL, and TAIFG.
void TIMER_A_enableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Enable capture compare interrupt.
Does not clear interrupt flags
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister is the selected capture compare register Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
Modified bits of TAxCCTLn register.
Returns
None
References CCIE, HWREG16, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, and TIMER_A_CAPTURECOMPARE_REGISTER_6.
void TIMER_A_disableCaptureCompareInterrupt (uint16_t baseAddress, uint16_t captureCompareRegister)
Disable capture compare interrupt.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister is the selected capture compare register Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
Modified bits of TAxCCTLn register.
Returns
None
References CCIE, HWREG16, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, and TIMER_A_CAPTURECOMPARE_REGISTER_6.
uint32_t TIMER_A_getCaptureCompareInterruptStatus (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t mask)
Return capture compare interrupt status.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister is the selected capture compare register Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
mask is the mask for the interrupt status Mask value is the logical OR of any of the following:
TIMER_A_CAPTURE_OVERFLOW
TIMER_A_CAPTURECOMPARE_INTERRUPT_FLAG
Returns
Logical OR of any of the following:
TIMER_A_CAPTURE_OVERFLOW
TIMER_A_CAPTURECOMPARE_INTERRUPT_FLAG
indicating the status of the masked interrupts
References HWREG16.
void TIMER_A_clear (uint16_t baseAddress)
Reset/Clear the timer clock divider, count direction, count.
Parameters
baseAddress is the base address of the TIMER_A module.
Modified bits of TAxCTL register.
Returns
None
References HWREG16, OFS_TAxCTL, and TACLR.
uint8_t TIMER_A_getSynchronizedCaptureCompareInput (uint16_t baseAddress, uint16_t captureCompareRegister, uint16_t synchronized)
Get synchronized capturecompare input.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
synchronized Valid values are:
TIMER_A_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT
TIMER_A_READ_CAPTURE_COMPARE_INPUT
Returns
One of the following:
TIMER_A_CAPTURECOMPARE_INPUT_HIGH
TIMER_A_CAPTURECOMPARE_INPUT_LOW
References HWREG16, TIMER_A_CAPTURECOMPARE_INPUT_HIGH, TIMER_A_CAPTURECOMPARE_INPUT_LOW, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, TIMER_A_CAPTURECOMPARE_REGISTER_6, TIMER_A_READ_CAPTURE_COMPARE_INPUT, and TIMER_A_READ_SYNCHRONIZED_CAPTURECOMPAREINPUT.
uint8_t TIMER_A_getOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister)
Get output bit for output mode.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
Returns
One of the following:
TIMER_A_OUTPUTMODE_OUTBITVALUE_HIGH
TIMER_A_OUTPUTMODE_OUTBITVALUE_LOW
References HWREG16, OUT, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, TIMER_A_CAPTURECOMPARE_REGISTER_6, TIMER_A_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_A_OUTPUTMODE_OUTBITVALUE_LOW.
uint16_t TIMER_A_getCaptureCompareCount (uint16_t baseAddress, uint16_t captureCompareRegister)
Get current capturecompare count.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
Returns
Current count as an uint16_t
References HWREG16, OFS_TAxR, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, and TIMER_A_CAPTURECOMPARE_REGISTER_6.
void TIMER_A_setOutputForOutputModeOutBitValue (uint16_t baseAddress, uint16_t captureCompareRegister, uint8_t outputModeOutBitValue)
Set output bit for output mode.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
outputModeOutBitValue is the value to be set for out bit Valid values are:
TIMER_A_OUTPUTMODE_OUTBITVALUE_HIGH
TIMER_A_OUTPUTMODE_OUTBITVALUE_LOW
Modified bits of TAxCCTLn register.
Returns
None
References HWREG16, OUT, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, TIMER_A_CAPTURECOMPARE_REGISTER_6, TIMER_A_OUTPUTMODE_OUTBITVALUE_HIGH, and TIMER_A_OUTPUTMODE_OUTBITVALUE_LOW.
void TIMER_A_outputPWM (uint16_t baseAddress, TIMER_A_outputPWMParam * param)
Generate a PWM with timer running in up mode.
Parameters
baseAddress is the base address of the TIMER_A module.
param is the pointer to struct for PWM configuration.
Modified bits of TAxCTL register, bits of TAxCCTL0 register, bits of TAxCCR0 register and bits of TAxCCTLn register.
Returns
None
References TIMER_A_outputPWMParam::clockSource, TIMER_A_outputPWMParam::clockSourceDivider, TIMER_A_outputPWMParam::compareOutputMode, TIMER_A_outputPWMParam::compareRegister, TIMER_A_outputPWMParam::dutyCycle, HWREG16, ID__8, OFS_TAxCCR0, OFS_TAxCCTL0, OFS_TAxCTL, OFS_TAxEX0, OFS_TAxR, TAIDEX_7, TIMER_A_CAPTURECOMPARE_INTERRUPT_ENABLE, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, TIMER_A_CAPTURECOMPARE_REGISTER_6, TIMER_A_CLOCKSOURCE_ACLK, TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK, TIMER_A_CLOCKSOURCE_SMCLK, TIMER_A_DO_CLEAR, TIMER_A_OUTPUTMODE_OUTBITVALUE, TIMER_A_OUTPUTMODE_RESET, TIMER_A_OUTPUTMODE_RESET_SET, TIMER_A_OUTPUTMODE_SET, TIMER_A_OUTPUTMODE_SET_RESET, TIMER_A_OUTPUTMODE_TOGGLE, TIMER_A_OUTPUTMODE_TOGGLE_RESET, TIMER_A_OUTPUTMODE_TOGGLE_SET, TIMER_A_TAIE_INTERRUPT_ENABLE, TIMER_A_UP_MODE, TIMER_A_UPDOWN_MODE, and TIMER_A_outputPWMParam::timerPeriod.
Referenced by TIMER_A_generatePWM().
void TIMER_A_generatePWM (uint16_t baseAddress, uint16_t clockSource, uint16_t clockSourceDivider, uint16_t timerPeriod, uint16_t compareRegister, uint16_t compareOutputMode, uint16_t dutyCycle)
DEPRECATED - Generate a PWM with timer running in up mode.
Parameters
baseAddress is the base address of the TIMER_A module.
clockSource selects Clock source. Valid values are:
TIMER_A_CLOCKSOURCE_EXTERNAL_TXCLK [Default]
TIMER_A_CLOCKSOURCE_ACLK
TIMER_A_CLOCKSOURCE_SMCLK
TIMER_A_CLOCKSOURCE_INVERTED_EXTERNAL_TXCLK
clockSourceDivider is the desired divider for the clock source Valid values are:
TIMER_A_CLOCKSOURCE_DIVIDER_1 [Default]
TIMER_A_CLOCKSOURCE_DIVIDER_2
TIMER_A_CLOCKSOURCE_DIVIDER_3
TIMER_A_CLOCKSOURCE_DIVIDER_4
TIMER_A_CLOCKSOURCE_DIVIDER_5
TIMER_A_CLOCKSOURCE_DIVIDER_6
TIMER_A_CLOCKSOURCE_DIVIDER_7
TIMER_A_CLOCKSOURCE_DIVIDER_8
TIMER_A_CLOCKSOURCE_DIVIDER_10
TIMER_A_CLOCKSOURCE_DIVIDER_12
TIMER_A_CLOCKSOURCE_DIVIDER_14
TIMER_A_CLOCKSOURCE_DIVIDER_16
TIMER_A_CLOCKSOURCE_DIVIDER_20
TIMER_A_CLOCKSOURCE_DIVIDER_24
TIMER_A_CLOCKSOURCE_DIVIDER_28
TIMER_A_CLOCKSOURCE_DIVIDER_32
TIMER_A_CLOCKSOURCE_DIVIDER_40
TIMER_A_CLOCKSOURCE_DIVIDER_48
TIMER_A_CLOCKSOURCE_DIVIDER_56
TIMER_A_CLOCKSOURCE_DIVIDER_64
timerPeriod selects the desired timer period
compareRegister selects the compare register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
compareOutputMode specifies the output mode. Valid values are:
TIMER_A_OUTPUTMODE_OUTBITVALUE [Default]
TIMER_A_OUTPUTMODE_SET
TIMER_A_OUTPUTMODE_TOGGLE_RESET
TIMER_A_OUTPUTMODE_SET_RESET
TIMER_A_OUTPUTMODE_TOGGLE
TIMER_A_OUTPUTMODE_RESET
TIMER_A_OUTPUTMODE_TOGGLE_SET
TIMER_A_OUTPUTMODE_RESET_SET
dutyCycle specifies the dutycycle for the generated waveform
Modified bits of TAxCTL register, bits of TAxCCTL0 register, bits of TAxCCR0 register and bits of TAxCCTLn register.
Returns
None
References TIMER_A_outputPWMParam::clockSource, TIMER_A_outputPWMParam::clockSourceDivider, TIMER_A_outputPWMParam::compareOutputMode, TIMER_A_outputPWMParam::compareRegister, TIMER_A_outputPWMParam::dutyCycle, TIMER_A_outputPWM(), and TIMER_A_outputPWMParam::timerPeriod.
void TIMER_A_stop (uint16_t baseAddress)
Stops the timer.
Parameters
baseAddress is the base address of the TIMER_A module.
Modified bits of TAxCTL register.
Returns
None
References HWREG16, MC_0, MC_3, and OFS_TAxCTL.
void TIMER_A_setCompareValue (uint16_t baseAddress, uint16_t compareRegister, uint16_t compareValue)
Sets the value of the capture-compare register.
Parameters
baseAddress is the base address of the TIMER_A module.
compareRegister selects the Capture register being used. Refer to datasheet to ensure the device has the capture compare register being used. Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
compareValue is the count to be compared with in compare mode
Modified bits of TAxCCRn register.
Returns
None
References HWREG16, OFS_TAxR, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, and TIMER_A_CAPTURECOMPARE_REGISTER_6.
void TIMER_A_clearTimerInterruptFlag (uint16_t baseAddress)
Clears the Timer TAIFG interrupt flag.
Parameters
baseAddress is the base address of the TIMER_A module.
Modified bits are TAIFG of TAxCTL register.
Returns
None
References HWREG16, OFS_TAxCTL, and TAIFG.
void TIMER_A_clearCaptureCompareInterruptFlag (uint16_t baseAddress, uint16_t captureCompareRegister)
Clears the capture-compare interrupt flag.
Parameters
baseAddress is the base address of the TIMER_A module.
captureCompareRegister selects the Capture-compare register being used. Valid values are:
TIMER_A_CAPTURECOMPARE_REGISTER_0
TIMER_A_CAPTURECOMPARE_REGISTER_1
TIMER_A_CAPTURECOMPARE_REGISTER_2
TIMER_A_CAPTURECOMPARE_REGISTER_3
TIMER_A_CAPTURECOMPARE_REGISTER_4
TIMER_A_CAPTURECOMPARE_REGISTER_5
TIMER_A_CAPTURECOMPARE_REGISTER_6
Modified bits are CCIFG of TAxCCTLn register.
Returns
None
References CCIFG, HWREG16, TIMER_A_CAPTURECOMPARE_REGISTER_0, TIMER_A_CAPTURECOMPARE_REGISTER_1, TIMER_A_CAPTURECOMPARE_REGISTER_2, TIMER_A_CAPTURECOMPARE_REGISTER_3, TIMER_A_CAPTURECOMPARE_REGISTER_4, TIMER_A_CAPTURECOMPARE_REGISTER_5, and TIMER_A_CAPTURECOMPARE_REGISTER_6.
uint16_t TIMER_A_getCounterValue (uint16_t baseAddress)
Reads the current timer count value.
Reads the current count value of the timer. There is a majority vote system in place to confirm an accurate value is returned. The TIMER_A_THRESHOLD #define in the corresponding header file can be modified so that the votes must be closer together for a consensus to occur.
Parameters
baseAddress is the base address of the TIMER_A module.
Returns
Majority vote of timer count value
References HWREG16, OFS_TAxR, and TIMER_A_THRESHOLD.
Copyright 2014, Texas Instruments Incorporated